### ISSUE TITLE
Implement support for default values

### ISSUE THREAD

**Issue by alextmz** [mvantellingen/python-zeep#100]
Hi, using zeep 0.10. The following

```python
from zeep import Client

client = Client('http://cms.acme.local/axis2/services/UcmdbService?wsdl')

print client.service._binding.create_message('getCIsById', {'callerApplication': 'someapp'}, {'typedProperties': ''}, {'ID': 'someid'})
```
gives this error:

```
Traceback (most recent call last):
  File "C:/code/test.py", line 5, in <module>
    print client.service._binding.create_message('getCIsById', {'callerApplication': 'someapp'}, {'typedProperties': ''}, {'ID': 'someid'})
  File "C:\Python27\lib\site-packages\zeep\wsdl\soap.py", line 56, in create_message
    serialized = operation.create(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\definitions.py", line 245, in create
    return self.input.serialize(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\messages.py", line 77, in serialize
    self.body.render(body, body_value)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements.py", line 153, in render
    return self.type.render(node, value)
  File "C:\Python27\lib\site-packages\zeep\xsd\types.py", line 177, in render
    element.render(parent, sub_value)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements.py", line 153, in render
    return self.type.render(node, value)
  File "C:\Python27\lib\site-packages\zeep\xsd\types.py", line 177, in render
    element.render(parent, sub_value)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements.py", line 193, in render
    super(ListElement, self).render(parent, val)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements.py", line 153, in render
    return self.type.render(node, value)
  File "C:\Python27\lib\site-packages\zeep\xsd\types.py", line 177, in render
    element.render(parent, sub_value)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements.py", line 142, in render
    node = etree.SubElement(parent, self.qname)
  File "src/lxml/lxml.etree.pyx", line 3112, in lxml.etree.SubElement (src\lxml\lxml.etree.c:76595)
  File "src/lxml/apihelpers.pxi", line 177, in lxml.etree._makeSubElement (src\lxml\lxml.etree.c:16861)
  File "src/lxml/apihelpers.pxi", line 1549, in lxml.etree._getNsTag (src\lxml\lxml.etree.c:31640)
  File "src/lxml/apihelpers.pxi", line 1567, in lxml.etree.__getNsTag (src\lxml\lxml.etree.c:31799)
  File "src/lxml/apihelpers.pxi", line 1437, in lxml.etree._utf8 (src\lxml\lxml.etree.c:30194)
TypeError: Argument must be bytes or unicode, got 'NoneType'
```
[WSDL and extra xsds attached... they are a bit complex...](https://github.com/mvantellingen/python-zeep/files/333644/wsdl.zip)

I'm I doing something wrong or it is a bug? I'm free to test anytime.

**Comment by alextmz** [comment]
Hi,

I've added a bunch of debug statements before the calls mentioned on the traceback. Something funny came up: notice the "render.value 0" and "sub_value: none" at the end, looks like something is overshooting when scanning, maybe related to ComplexType?

Thanks for zeep btw, it rocks! :)

```
DEBUG:zeep.wsdl.soap:args                           : ({'callerApplication': 'someapp'}, {'typedProperties': ''}, {'ID': 'someid'}), args type: <type 'tuple'>
DEBUG:zeep.wsdl.soap:KWargs                         : {}, args type: <type 'dict'>
DEBUG:zeep.wsdl.definitions:args                    : ({'callerApplication': 'someapp'}, {'typedProperties': ''}, {'ID': 'someid'}), args type: <type 'tuple'>
DEBUG:zeep.wsdl.definitions:KWargs                  : {}, args type: <type 'dict'>
DEBUG:zeep.wsdl.messages:body                       : <Element {http://schemas.xmlsoap.org/soap/envelope/}Body at 0x31dca80>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.wsdl.messages:body_value                 : {   'CIsTypedProperties': {   '_xsd_elm': <Element(name=u'CIsTypedProperties', type=<zeep.xsd.dynamic_types.TypedPropertiesCollection object at 0x030E0C90>)>, 'typedProperties': ''}, 'IDs': {   'ID': 'someid', '_xsd_elm': <Element(name=u'IDs', type=<zeep.xsd.dynamic_types.IDs object at 0x02F93F70>)>}, '_xsd_elm': <Element(name=u'getCIsById', type=<zeep.xsd.dynamic_types.getCIsById object at 0x030EDAB0>)>, 'cmdbContext': {   '_xsd_elm': <Element(name=u'cmdbContext', type=<zeep.xsd.dynamic_types.CmdbContext object at 0x02F93990>)>, 'callerApplication': 'someapp'}}, args type: <class 'zeep.objects.getCIsById'>
DEBUG:zeep.xsd.elements:element.render.node         : <Element {http://schemas.hp.com/ucmdb/1/params/query}getCIsById at 0x31dcad0>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:element.render.value        : {   'CIsTypedProperties': {   '_xsd_elm': <Element(name=u'CIsTypedProperties', type=<zeep.xsd.dynamic_types.TypedPropertiesCollection object at 0x030E0C90>)>, 'typedProperties': ''}, 'IDs': {   'ID': 'someid', '_xsd_elm': <Element(name=u'IDs', type=<zeep.xsd.dynamic_types.IDs object at 0x02F93F70>)>}, '_xsd_elm': <Element(name=u'getCIsById', type=<zeep.xsd.dynamic_types.getCIsById object at 0x030EDAB0>)>, 'cmdbContext': {   '_xsd_elm': <Element(name=u'cmdbContext', type=<zeep.xsd.dynamic_types.CmdbContext object at 0x02F93990>)>, 'callerApplication': 'someapp'}}, args type: <class 'zeep.objects.getCIsById'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/params/query}getCIsById at 0x31dcad0>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : {   '_xsd_elm': <Element(name=u'cmdbContext', type=<zeep.xsd.dynamic_types.CmdbContext object at 0x02F93990>)>, 'callerApplication': 'someapp'}, sub_value type: <class 'zeep.objects.CmdbContext'>
DEBUG:zeep.xsd.elements:element.render.node         : <Element {http://schemas.hp.com/ucmdb/1/params/query}cmdbContext at 0x31dcb70>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:element.render.value        : {   '_xsd_elm': <Element(name=u'cmdbContext', type=<zeep.xsd.dynamic_types.CmdbContext object at 0x02F93990>)>, 'callerApplication': 'someapp'}, args type: <class 'zeep.objects.CmdbContext'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/params/query}cmdbContext at 0x31dcb70>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : someapp, sub_value type: <type 'str'>
DEBUG:zeep.xsd.elements:element.render.node         : <Element {http://schemas.hp.com/ucmdb/1/types}callerApplication at 0x31dcbc0>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:element.render.value        : someapp, args type: <type 'str'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/params/query}getCIsById at 0x31dcad0>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : {   '_xsd_elm': <Element(name=u'CIsTypedProperties', type=<zeep.xsd.dynamic_types.TypedPropertiesCollection object at 0x030E0C90>)>, 'typedProperties': ''}, sub_value type: <class 'zeep.objects.TypedPropertiesCollection'>
DEBUG:zeep.xsd.elements:element.render.node         : <Element {http://schemas.hp.com/ucmdb/1/params/query}CIsTypedProperties at 0x31dcb48>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:element.render.value        : {   '_xsd_elm': <Element(name=u'CIsTypedProperties', type=<zeep.xsd.dynamic_types.TypedPropertiesCollection object at 0x030E0C90>)>, 'typedProperties': ''}, args type: <class 'zeep.objects.TypedPropertiesCollection'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/params/query}CIsTypedProperties at 0x31dcb48>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : , sub_value type: <type 'str'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/params/query}getCIsById at 0x31dcad0>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : {   'ID': 'someid', '_xsd_elm': <Element(name=u'IDs', type=<zeep.xsd.dynamic_types.IDs object at 0x02F93F70>)>}, sub_value type: <class 'zeep.objects.IDs'>
DEBUG:zeep.xsd.elements:element.render.node         : <Element {http://schemas.hp.com/ucmdb/1/params/query}IDs at 0x31dcb48>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:element.render.value        : {   'ID': 'someid', '_xsd_elm': <Element(name=u'IDs', type=<zeep.xsd.dynamic_types.IDs object at 0x02F93F70>)>}, args type: <class 'zeep.objects.IDs'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/params/query}IDs at 0x31dcb48>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : someid, sub_value type: <type 'str'>
DEBUG:zeep.xsd.elements:ListElement.render.ListEleme: <class 'zeep.xsd.elements.ListElement'>, ListElement type : <type 'type'>
DEBUG:zeep.xsd.elements:ListElement.render.parent   : <Element {http://schemas.hp.com/ucmdb/1/params/query}IDs at 0x31dcb48>, parent type      : <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:ListElement.render.val      : 0, val type         : <type 'str'>
DEBUG:zeep.xsd.elements:element.render.node         : <Element {http://schemas.hp.com/ucmdb/1/types}ID at 0x31dcbe8>, args type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.elements:element.render.value        : 0, args type: <type 'str'>
DEBUG:zeep.xsd.types:ComplexType.render.parent      : <Element {http://schemas.hp.com/ucmdb/1/types}ID at 0x31dcbe8>,    parent type: <type 'lxml.etree._Element'>
DEBUG:zeep.xsd.types:ComplexType.render.sub_value   : None, sub_value type: <type 'NoneType'>
```

**Comment by alextmz** [comment]
Found out what was wrong. Even though xsd7 specifies an attribute "temp" with default "false" and use="optional', 
```
   <xs:complexType name="ID">
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute default="false" name="temp" type="xs:boolean" use="optional">
               <xs:annotation>
                  <xs:documentation>If true, this is a temporary ID. If false, it is the instance's ID in the UCMDB.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
```
I had to manually specify temp=False for it to work. So, doing:

```
print etree.tostring(client.service._binding.create_message('getCIsById', {'callerApplication': 'someapp'}, {'typedProperties': ''}, IDs={'ID': {'_value': '0d24c63453cade702d343e12ed015f11', 'temp': False}}), pretty_print=True)
```

Worked as expected.

Thanks for the great library!
