### ISSUE TITLE
zeep.exceptions.Fault: The formatter threw an exception while trying to deserialize the message

### ISSUE THREAD

**Issue by andreabisello** [mvantellingen/python-zeep#1022]
with python and zeep updated,

i'm not able to call the createDocument method of this wsdl

https://testsdc2csolution.solutiondocondemand.com/Basic/RepositoryService.svc?singleWsdl

the calls works with soapui

![image](https://user-images.githubusercontent.com/2149815/67615766-92d1ec00-f7d0-11e9-8487-2ff9fb64ef25.png)

this is what i tried

```


from lib.configuration import *
from zeep import Client
from zeep.wsse.username import UsernameToken
from lib.utils import file_to_b64bytes
client = Client(CONSERVAZIONE_WSDL_ENDPOINT, wsse=UsernameToken(CONSERVAZIONE_USERNAME, CONSERVAZIONE_PASSWORD))


c_stream = file_to_b64bytes("assets/pdv/packagePdV.zip")
c_length = len(c_stream)
prop = client.get_type('ns4:ArrayOfKeyValueOfstringanyType')(
    [
        {
            "Key": "PdV_VerificaFirmaFiles",
            "Value" : False
        },
        {
            "Key": "Firma_OggettiProduttore",
            "Value": False
        }
    ]
)

contentStream = client.get_type('ns3:ContentStream')(
    filename="packagePdV.zip",
    length=c_length,
    stream=c_stream
)

answer = client.service.createDocument(
    repositoryId="1",
    properties=prop,
    contentStream=contentStream,
    versioningState="none"
)

print(answer)

```

and this is what i obtain

> 
> Traceback (most recent call last):
>   File "C:/src/qa-lsd-webservices/qa-lsd-webservices/tryzeep.py", line 34, in <module>
>     versioningState="none"
>   File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\proxy.py", line 45, in __call__
>     kwargs,
>   File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 130, in send
>     return self.process_reply(client, operation_obj, response)
>   File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 195, in process_reply
>     return self.process_error(doc, operation)
>   File "C:\Users\Andrea-Fisso\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 299, in process_error
>     detail=fault_node.find("detail"),
> zeep.exceptions.Fault: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://tempuri.org/:properties. The InnerException message was 'Element Value from namespace http://schemas.microsoft.com/2003/10/Serialization/Arrays cannot have child contents to be deserialized as an object. Please use XmlNode[] to deserialize this pattern of XML.'.  Please see InnerException for more details.
> 
> 

any suggestion please?

thanks

**Comment by andreabisello** [comment]
the problem looks related to the webservices 

the backend needs something like

         <ns1:properties>
            <ns2:Key>PdV_VerificaFirmaFiles</ns2:Key>
            <ns2:Value>False</ns2:Value>
            <ns2:Key>Firma_OggettiProduttore</ns2:Key>
            <ns2:Value>False</ns2:Value>
         </ns1:properties>

even the wsdl creates something like 

         <tem:properties>
            
            <arr:KeyValueOfstringanyType>
               <arr:Key>?</arr:Key>
               <arr:Value>?</arr:Value>
            </arr:KeyValueOfstringanyType>
         </tem:properties>


even with soap ui.
