### ISSUE TITLE
Exception raised decoding hasmaps in array as xsd:anyType generated by php-soap

### ISSUE THREAD

**Issue by julien-lang** [mvantellingen/python-zeep#1025]
When php-soap server response is `[ {"id: "foo"}, {"id": "bar} ]`, zeep fails with exception:

    NamespaceError: Unable to resolve type {http://xml.apache.org/xml-soap}Map. No schema available for the namespace u'http://xml.apache.org/xml-soap'.

I don't have enough expertise in SOAP / WSDL to find out whether the issue comes from php-soap , zeep or simply the WSDL...
But what I know is that using the same server, SOAPpy is able to decode the response.

I have an existing system with php-soap server side and SOAPpy client side. I want to migrate from SOAPpy to zeep because SOAPpy does not provide a version for Python 3 and I must migrate my infrastructure to Python 3.

# Reproduction scenario

* Install php-soap (Debian/Ubuntu: `apt install php-soap`)
* Create a workspace folder with 3 files:
* **api.wsdl**
```xml
<?xml version="1.0" encoding="UTF-8" ?>

<definitions name="API" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:ns2="http://xml.apache.org/xml-soap" 
	xmlns:urn="uri:api" targetNamespace="uri:api">
	
	<message name="voidRequest" />
	
	<message name="Any">
		<part name="parameters" type="xsd:anyType"/>
	</message>

	<portType name="API.PortType">
		<operation name="test_bool">
			<input message="urn:voidRequest"/>
			<output message="urn:Any" />
		</operation>

		<operation name="test_string">
			<input message="urn:voidRequest"/>
			<output message="urn:Any" />
		</operation>

		<operation name="test_hash">
			<input message="urn:voidRequest"/>
			<output message="urn:Any" />
		</operation>

		<operation name="test_array">
			<input message="urn:voidRequest"/>
			<output message="urn:Any" />
		</operation>

		<operation name="test_double_array">
			<input message="urn:voidRequest" />
			<output message="urn:Any" />
		</operation>
	</portType>
	
	<binding name="API.Binding" type="urn:API.PortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="test_bool">
			<soap:operation soapAction="urn:API#test_bool"/>
			<input>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>

		<operation name="test_string">
			<soap:operation soapAction="urn:API#test_string"/>
			<input>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>

		<operation name="test_hash">
			<soap:operation soapAction="urn:API#test_hash"/>
			<input>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>

		<operation name="test_array">
			<soap:operation soapAction="urn:API#test_array"/>
			<input>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>

		<operation name="test_double_array">
			<soap:operation soapAction="urn:API#test_double_array"/>
			<input>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:API" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	
	<service name="API.Service">
		<port name="APIPort" binding="API.Binding">
			<soap:address location="localhost"/>
		</port>
	</service>
</definitions>
```
* **api.php**
```php
<?php

class API {
	public function test_bool() {
		return true;
	}

	public function test_string() {
		return 'string';
	}

	public function test_array() {
		return ["a", "b", "c"];
	}

	public function test_hash() {
		return [
			"a" => ["id" => "foo"],
			"b" => ["id" => "bar"],
		];
	}

	public function test_double_array() {
		return [
			["id" => "001"],
			["id" => "002"],
		];
	}
}

ini_set('soap.wsdl_cache_enabled', 0);
$server = new SoapServer('api.wsdl');
$server->setClass('API');
$server->handle();
```
* **test.py**
 ```python
# -*- coding: utf-8 -*-

import unittest
import zeep

class Test(unittest.TestCase):
	def setUp(self):
		host = "localhost:8080"

		client = zeep.Client(
			"http://{host}/api.wsdl".format(
				host=host,
			),
		)

		self.api = client.create_service(
			"{uri:api}API.Binding",
			"http://{host}/api.php".format(
				host=host,
			),
		)

	def test_bool(self):
		self.assertEqual(self.api.test_bool(), True)

	def test_string(self):
		self.assertEqual(self.api.test_string(), "string")

	def test_array(self):
		self.assertEqual(self.api.test_array(), ["a", "b", "c"])

	def test_hash(self):
		self.assertEqual(
			self.api.test_hash(),
			{
				"a": {"id": "foo"},
				"b": {"id": "bar"},
			}
		)

	def test_double_array(self):
		self.assertEqual(
			self.api.test_double_array(),
			[
				{"id": "001"},
				{"id": "002"},
			]
		)

if __name__ == '__main__':
	unittest.main()
```

## Test process

1. Launch server
  `php -S localhost:8080`
2. Run test client
  `python test.py`

### Results
```
$ python test.py 
F.EF.
======================================================================
ERROR: test_double_array (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 48, in test_double_array
    self.api.test_double_array(),
  File "pyenv2/local/lib/python2.7/site-packages/zeep/proxy.py", line 45, in __call__
    kwargs,
  File "pyenv2/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 130, in send
    return self.process_reply(client, operation_obj, response)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 197, in process_reply
    result = operation.process_reply(doc)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 396, in process_reply
    return self.output.deserialize(envelope)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/wsdl/messages/soap.py", line 94, in deserialize
    body_result = self._deserialize_body(body)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/wsdl/messages/soap.py", line 519, in _deserialize_body
    result = self.body.parse(response_element, self.wsdl.types, context=context)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 130, in parse
    schema_type=self.type,
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/types/complex.py", line 194, in parse_xmlelement
    elements, schema, name, context=context
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/indicators.py", line 609, in parse_xmlelements
    xmlelements, schema, name, context=context
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 176, in parse_xmlelements
    item = self.parse(xmlelement, schema, allow_none=True, context=context)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 130, in parse
    schema_type=self.type,
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/types/complex.py", line 194, in parse_xmlelement
    elements, schema, name, context=context
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/indicators.py", line 723, in parse_xmlelements
    self.child.parse_xmlelements(xmlelements, schema, name, context=context)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/indicators.py", line 609, in parse_xmlelements
    xmlelements, schema, name, context=context
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/any.py", line 114, in parse_xmlelements
    item = self.parse(xmlelement, schema, context=context)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/elements/any.py", line 75, in parse
    xsd_type = schema.get_type(xsd_type)
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 145, in get_type
    return self._get_instance(qname, "get_type", "type")
  File "pyenv2/local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 261, in _get_instance
    % (name, qname.text, qname.namespace)
NamespaceError: Unable to resolve type {http://xml.apache.org/xml-soap}Map. No schema available for the namespace u'http://xml.apache.org/xml-soap'.

======================================================================
FAIL: test_array (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 34, in test_array
    self.assertEqual(self.api.test_array(), ["a", "b", "c"])
AssertionError: {
    '_value_1': [
        'a',
        'b',
        'c'
    ],
    'arrayType': 'xsd:string[3]',
    'offset': None,
    'id': None,
    'href': None,
    '_attr_1': {
}
} != ['a', 'b', 'c']

======================================================================
FAIL: test_hash (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 42, in test_hash
    "b": {"id": "bar"},
AssertionError: [<Element item at 0x7f58b0382a28>, <Element item at 0x7f58b0382908>] != {'a': {'id': 'foo'}, 'b': {'id': 'bar'}}

----------------------------------------------------------------------
Ran 5 tests in 0.571s

FAILED (failures=2, errors=1)
```

------

* zeep version: 3.4.0
* same result with Python 3.7 and Python 2.7
* php-soap version: 7.3.11-1~deb10u1

**Comment by tvannahl** [comment]
I do have the same Issue running zeep 4.0.0

**Comment by tvannahl-eht** [comment]
A response of the above described service on which zeep dies is:

```xml


<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:ns1="urn:API" xmlns:ns2="http://xml.apache.org/xml-soap"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
   <SOAP-ENV:Body>
      <ns1:test_double_arrayResponse>
         <parameters SOAP-ENC:arrayType="ns2:Map[2]" xsi:type="SOAP-ENC:Array">
            <item xsi:type="ns2:Map">
               <item>
                  <key xsi:type="xsd:string">id</key>
                  <value xsi:type="xsd:string">001</value>
               </item>
            </item>
            <item xsi:type="ns2:Map">
               <item>
                  <key xsi:type="xsd:string">id</key>
                  <value xsi:type="xsd:string">002</value>
               </item>
            </item>
         </parameters>
      </ns1:test_double_arrayResponse>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

Problem being that `http://xml.apache.org/xml-soap` is not a downloadable schema, so the schema would need to be hard coded in zeep.

**Comment by claudep** [comment]
Also affected by this error. Does this mean that zeep is not usable for reading such responses? Or are they workarounds?
