### ISSUE TITLE
kwargs doesn't work with XSD:Choice

### ISSUE THREAD

**Issue by msci-wanglei** [mvantellingen/python-zeep#1068]
Hi,

I'm using zeep 3.3.1 and I got error below after I use kwargs for XSD:Choice element.

  File "C:\python36\lib\site-packages\zeep\xsd\elements\indicators.py", line 130, in parse_args
    raise TypeError("Choice elements only work with keyword arguments")

Test Code:

from lxml import etree
from zeep import Client

client = Client('https://www.barraone.com/axis2/services/BDTService?wsdl')

type_factory = client.type_factory('ns0')

element  = client.get_element('ns0:SubmitReportJobRequest')
obj = element()
obj = {'User':'username','Client':'clientid','Password':'password'}

repDef = type_factory.ReturnAttribution()
repDef.TimeSeriesSettings = 'a'
repDef.Portfolios = 'b'
repDef.AnalysisSettings = 'c'

#obj.PAAttributionParam=repDef
node=client.create_message(client.service, 'SubmitReportJob', obj, repDef)

print(etree.tostring(node, pretty_print=True))

**Comment by kurtabersold** [comment]
Seeing the same issue with Zeep 3.4.0 on Python 2.7

**Comment by kurtabersold** [comment]
To elaborate on @msci-wanglei's report, here is the complete stack trace using the code from above:

```
Traceback (most recent call last):
  File "test_zeep_bug.py", line 18, in <module>
    node=client.create_message(client.service, 'SubmitReportJob', obj, repDef)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/client.py", line 139, in create_message
    operation_name, args, kwargs, client=self
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/wsdl/definitions.py", line 215, in create
    return self.input.serialize(*args, **kwargs)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/wsdl/messages/soap.py", line 68, in serialize
    body_value = self.body(*args, **kwargs)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/xsd/elements/element.py", line 57, in __call__
    instance = self.type(*args, **kwargs)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/xsd/types/complex.py", line 49, in __call__
    return self._value_class(*args, **kwargs)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/xsd/valueobjects.py", line 95, in __init__
    items = _process_signature(self._xsd_type, args, kwargs)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/xsd/valueobjects.py", line 185, in _process_signature
    values, args, index = element.parse_args(args, index)
  File "/home/kabersold/src/python-packages/python-zeep/src/zeep/xsd/elements/indicators.py", line 129, in parse_args
    raise TypeError("Choice elements only work with keyword arguments")
TypeError: Choice elements only work with keyword arguments
```
