### ISSUE TITLE
AttributeError: 'RefElement' object has no attribute 'name'

### ISSUE THREAD

**Issue by sassur** [mvantellingen/python-zeep#108]
I'm trying to use the save function in the following wsdl https://service.web-ta.net/ws/services/ConsignmentWS?wsdl with this code

```
import logging
import httplib as http_client

from zeep import Client


http_client.HTTPConnection.debuglevel = 1
logging.basicConfig()
logging.getLogger().setLevel(logging.DEBUG)
requests_log = logging.getLogger("requests.packages.urllib3")
requests_log.setLevel(logging.DEBUG)
requests_log.propagate = True

client = Client(wsdl='https://service.web-ta.net:443/ws/services/ConsignmentWS?wsdl')

authenticationToken = client.get_type('ns2:AuthenticationToken')(
    userName='X',
    groupName='X',
    password='X',
)

consignment = client.get_type('ns1:Consignment')(
    Part=[],
    GoodsItem=[client.get_type('ns1:GoodsItem')(noOfPackages=1,weight=1.0,)],
    TransportProduct=client.get_type('ns1:TransportProduct')(
        PaymentInstruction=client.get_type('ns1:PaymentInstruction')(value='P',)
        ,)
)

consignmentResult = client.service.save(authenticationToken, consignment, 1)
```
Zeep can't parse the result with the following error "AttributeError: 'RefElement' object has no attribute 'name'"

I think the source of the error is this element
```
	<xsd:complexType name="Transport">
		<xsd:sequence>
			<xsd:element ref="tns:instruction" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element ref="tns:cooling"/>
				<xsd:element ref="tns:heating"/>
				<xsd:element ref="tns:frozen"/>
			</xsd:choice>
			<xsd:element ref="tns:tempLow" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="tns:tempHigh" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="tns:subsidyNo" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="tns:valuableGoods" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="tns:carryIn" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="tns:extraCrew" minOccurs="0" maxOccurs="1"/>
			<xsd:element ref="tns:eurPallets" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
	</xsd:complexType>
```

I'm using commit 390baeb on the master branch.

The actual values for authenticationToken can be sent on request.

Traceback, the resulting xml and the sent xml is attached.
[request.txt](https://github.com/mvantellingen/python-zeep/files/344954/request.txt)
[response.txt](https://github.com/mvantellingen/python-zeep/files/344956/response.txt)
[traceback.txt](https://github.com/mvantellingen/python-zeep/files/344955/traceback.txt)

**Comment by mvantellingen** [comment]
Shoud be fixed ;-)

**Comment by sassur** [comment]
Sort of, don't know if it is the same problem or a new one, but i get "TypeError: 'NoneType' object is not iterable".

I'm using zeep-0.12.0.dev0 according to pip.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Projects/python/lib/python2.7/site-packages/zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "/Projects/python/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 94, in send
    return self.process_reply(client, operation_obj, response)
  File "/Projects/python/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 125, in process_reply
    return operation.process_reply(doc)
  File "/Projects/python/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 249, in process_reply
    return self.output.deserialize(node)
  File "/Projects/python/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 208, in deserialize
    result.append(part.element.parse(elm, self.wsdl.types))
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 170, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/types.py", line 223, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/indicators.py", line 385, in parse_xmlelements
    xmlelements, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 178, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 170, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/types.py", line 223, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/indicators.py", line 385, in parse_xmlelements
    xmlelements, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 178, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 170, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/types.py", line 223, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/indicators.py", line 385, in parse_xmlelements
    xmlelements, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 178, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 170, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/types.py", line 223, in parse_xmlelement
    result = element.parse_xmlelements(children, schema, name)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/indicators.py", line 385, in parse_xmlelements
    xmlelements, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 178, in parse_xmlelements
    item = self.parse(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/elements.py", line 170, in parse
    return self.type.parse_xmlelement(xmlelement, schema)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/types.py", line 226, in parse_xmlelement
    return self(**init_kwargs)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/types.py", line 157, in __call__
    return self._value_class(*args, **kwargs)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/valueobjects.py", line 37, in __init__
    items = _process_signature(self._xsd_type, args, kwargs)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/valueobjects.py", line 112, in _process_signature
    values, kwargs = element.parse_kwargs(kwargs, None)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/indicators.py", line 149, in parse_kwargs
    sub_result, kwargs = element.parse_kwargs(kwargs, elm_name)
  File "/Projects/python/lib/python2.7/site-packages/zeep/xsd/indicators.py", line 295, in parse_kwargs
    for value in values:
TypeError: 'NoneType' object is not iterable
```

**Comment by mvantellingen** [comment]
Should be fixed now, if not could you open a new issue instead of re-using this one? That makes it easier for me to keep track of. Thanks!

**Comment by sassur** [comment]
Thanks for the fast fixes, great work!

Yes, I realised it would have been better as soon as I had posted.
