### ISSUE TITLE
Can't create authentication header

### ISSUE THREAD

**Issue by pryg-skok** [mvantellingen/python-zeep#109]
This is how I try to prepare authorization header:
```
from zeep import Client
client = Client("http://example.com?WSDL")
header = client.get_element("{http://example.com/soapservice/}AuthHeaderType")
h = header(username="login", password="password")
print(client.service.GetContent(parameter="param", _soapheader=h))
```

That's what I get:
```
(u'username', <Attribute(name=u'username', type=<zeep.xsd.builtins.String object at 0x1088cf610>)>)
(u'password', <Attribute(name=u'password', type=<zeep.xsd.builtins.String object at 0x1088cf610>)>)
(None, <Any(name=None)>)
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(client.service.GetContent(parameter="param", _soapheader=h))
  File "//zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "//zeep/wsdl/soap.py", line 79, in send
    serialized = operation_obj.create(*args, **kwargs)
  File "//zeep/wsdl/definitions.py", line 245, in create
    return self.input.serialize(*args, **kwargs)
  File "//zeep/wsdl/messages.py", line 85, in serialize
    self.header.render(header, header_value)
  File "//zeep/xsd/elements.py", line 194, in render
    self._render_value_item(parent, value)
  File "//zeep/xsd/elements.py", line 210, in _render_value_item
    return self.type.render(node, value)
  File "//zeep/xsd/types.py", line 231, in render
    attr_value = getattr(value, name, None)
TypeError: getattr(): attribute name must be string
```

Also I've tried to use simple dict to prepare authentication header - same problem:
```
hd = {"username": "login", "password": "password"}
```

Tried also on current git. What am I doing wrong?

**Comment by pryg-skok** [comment]
Problem not exists in version 0.10 (checkout from git)

**Comment by mvantellingen** [comment]
Yeah, must be a regression indeed. I'll add a test-case and fix for it later today

**Comment by mvantellingen** [comment]
I've fixed some bugs with the XSD handling on the master branch. Can you give that a try. If it doesn't work are you able to provide the wsdl or a snipper of the AuthHeaderType schema definition?

**Comment by pryg-skok** [comment]
Sad, but no. It's not fixed in last master.
I can send you link to schema in private message. Where I should write?

**Comment by mvantellingen** [comment]
You can mail it to michaelvantelligen@gmail.com Thanks!

**Comment by mvantellingen** [comment]
Closed it for now. If this is still and issue then let me know

**Comment by pryg-skok** [comment]
Sorry, I've just stop using any third-party library and write my own simple implementation for own needs. So I don't know whether or not the issues still reproduces or not.

**Comment by dilipptt** [comment]
@pryg-skok can you please share your implementation. Even I have the same issue.

**Comment by pryg-skok** [comment]
@dilipptt well, implementation is quite loudly said :)
I just prepare correct soap messages from examples provided for my case by writing templates and then send request to HTTP server with correct headers. 
Something like this:
```python

import requests

CreateEvent = """<?xml version="1.0" encoding="utf-8"?>
<soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Header>
    <ServiceHeader m_sUsername="{login}" m_sPassword="{password}"
        xmlns="http://man.entriq.net/livedrmservice/" />
  </soap12:Header>
  <soap12:Body>
     ... body ...
  </soap12:Body>
</soap12:Envelope>
"""

headers = {"content-type": "application/soap+xml; charset=utf-8"}
conn = requests.Session()
resp = conn.post(url, headers=headers, data=CreateTmpl.format(**params))
```

And it solves my issue :)
