### ISSUE TITLE
XMLParseError: Unable to resolve type

### ISSUE THREAD

**Issue by damianstaro** [mvantellingen/python-zeep#112]
Hi, I am trying to integrate with a SOAP web service and I am getting a failure in the parsing of the WSDL. I think it may be caused by order of types in the schema but I could be wrong.

Here's a code snippet that will reproduce:

``` python
import zeep

def main():

    client = zeep.Client(wsdl='https://s01.cloud-xip.miteksystems.com/'
                         'Plugins/ProductServices.PhotoVerify/services/'
                         'v1.0/PhotoVerifyService.svc?wsdl')

if __name__ == '__main__':
    main()
```

And the stack trace:

```
Traceback (most recent call last):
  File "mitek2.py", line 10, in <module>
    main()
  File "mitek2.py", line 5, in main
    client = zeep.Client(wsdl='https://s01.cloud-xip.miteksystems.com/'
  File "/vagrant/zeep/client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/vagrant/zeep/wsdl/wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/vagrant/zeep/wsdl/wsdl.py", line 144, in __init__
    self.parse_imports(doc)
  File "/vagrant/zeep/wsdl/wsdl.py", line 237, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "/vagrant/zeep/wsdl/wsdl.py", line 146, in __init__
    self.types = self.parse_types(doc)
  File "/vagrant/zeep/wsdl/wsdl.py", line 289, in parse_types
    self.wsdl._parser_context)
  File "/vagrant/zeep/xsd/schema.py", line 28, in __init__
    node, transport, location, self._parser_context, location)
  File "/vagrant/zeep/xsd/schema.py", line 148, in __init__
    visitor.visit_schema(node)
  File "/vagrant/zeep/xsd/visitor.py", line 101, in visit_schema
    self.process(node, parent=parent)
  File "/vagrant/zeep/xsd/visitor.py", line 47, in process
    result = visit_func(self, node, parent)
  File "/vagrant/zeep/xsd/visitor.py", line 156, in visit_import
    self.parser_context, base_url)
  File "/vagrant/zeep/xsd/schema.py", line 148, in __init__
    visitor.visit_schema(node)
  File "/vagrant/zeep/xsd/visitor.py", line 101, in visit_schema
    self.process(node, parent=parent)
  File "/vagrant/zeep/xsd/visitor.py", line 47, in process
    result = visit_func(self, node, parent)
  File "/vagrant/zeep/xsd/visitor.py", line 156, in visit_import
    self.parser_context, base_url)
  File "/vagrant/zeep/xsd/schema.py", line 148, in __init__
    visitor.visit_schema(node)
  File "/vagrant/zeep/xsd/visitor.py", line 101, in visit_schema
    self.process(node, parent=parent)
  File "/vagrant/zeep/xsd/visitor.py", line 47, in process
    result = visit_func(self, node, parent)
  File "/vagrant/zeep/xsd/visitor.py", line 156, in visit_import
    self.parser_context, base_url)
  File "/vagrant/zeep/xsd/schema.py", line 148, in __init__
    visitor.visit_schema(node)
  File "/vagrant/zeep/xsd/visitor.py", line 101, in visit_schema
    self.process(node, parent=parent)
  File "/vagrant/zeep/xsd/visitor.py", line 47, in process
    result = visit_func(self, node, parent)
  File "/vagrant/zeep/xsd/visitor.py", line 426, in visit_complex_type
    element = self.process(child, node)
  File "/vagrant/zeep/xsd/visitor.py", line 47, in process
    result = visit_func(self, node, parent)
  File "/vagrant/zeep/xsd/visitor.py", line 623, in visit_sequence
    item = self.process(child, node)
  File "/vagrant/zeep/xsd/visitor.py", line 47, in process
    result = visit_func(self, node, parent)
  File "/vagrant/zeep/xsd/visitor.py", line 242, in visit_element
    xsd_type = self._get_type(node_type.text)
  File "/vagrant/zeep/xsd/visitor.py", line 792, in _get_type
    retval = self.schema.get_type(name, default=None)
  File "/vagrant/zeep/xsd/schema.py", line 210, in get_type
    return self._imports[name.namespace].get_type(name)
  File "/vagrant/zeep/xsd/schema.py", line 207, in get_type
    "Unable to resolve type with QName '%s'" % name.text)
zeep.exceptions.XMLParseError: Unable to resolve type with QName '{http://miteksystems.com/}ImageFormat'
```

**Comment by mvantellingen** [comment]
Thanks, should be fixed now!

**Comment by damianstaro** [comment]
I tested this and it works. Thanks for fixing it so fast! Great library!
