### ISSUE TITLE
Error UnicodeDecodeError on Debian (not on windows)

### ISSUE THREAD

**Issue by pepitovadecurt** [mvantellingen/python-zeep#1120]
The following code runs correct on Windows (Python 3.8)

```
    #!python3
    # -*- coding: utf-8 -*-
    
    from zeep import Client
    from zeep.transports import Transport
    import requests
    
    exercici = '2020'
    periode = '06'
    wsdl_emeses = 'https://www.agenciatributaria.es/static_files/AEAT/Contenidos_Comune/La_Agencia_Tributaria/Modelos_y_formularios/Suministro_inmediato_informacion/FicherosSuministros/V_1_1/SuministroFactEmitidas.wsdl'
    cert = ('data/cert/publicCert.crt', 'data/cert/privateKey.pem')
    session = requests.Session()
    session.cert = (cert)
    transport = Transport(session=session)
    capcalera = {
        'IDVersionSii': '1.1',
        'Titular': {
            'NombreRazon': 'nombreempresa',
            'NIF': 'A43344565'
        }
    }
    filtreConsulta = {
        'PeriodoLiquidacion': {
            'Ejercicio': exercici,
            'Periodo': periode.zfill(2)
        }
    }

    ce = Client(wsdl=wsdl_emeses, transport=transport)
    fe = ce.service.ConsultaLRFacturasEmitidas(self.capcalera, self.filtreConsulta)
    print(fe)
```

but on Debian 9 (Python 3.6 with the same pip modules) fails with the return:

```
    Traceback (most recent call last):   File "test.py", line 29, in <module>
    ce = Client(wsdl=wsdl_emeses, transport=transport)   File "/usr/local/lib/python3.6/site-packages/zeep/client.py", line 68, in
    __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)   File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 80, in __init__
    document = self._get_xml_document(location)   File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 143, in _get_xml_document
    location, self.transport, self.location, settings=self.settings   File "/usr/local/lib/python3.6/site-packages/zeep/loader.py", line 78, in load_external
    content = transport.load(url)   File "/usr/local/lib/python3.6/site-packages/zeep/transports.py", line 110, in load
    content = self._load_remote_data(url)   File "/usr/local/lib/python3.6/site-packages/zeep/transports.py", line 126, in _load_remote_data
    response = self.session.get(url, timeout=self.load_timeout)   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context,   File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 360, in ssl_wrap_socket
    if keyfile and key_password is None and _is_key_file_encrypted(keyfile):   File "/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 409, in _is_key_file_encrypted
    for line in f:   File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 65: invalid continuation byte
```

The language of the documents are in Spanish.
Any idea of this error or bug?
Thanks.

**Comment by da1910** [comment]
The error suggests that zeep cannot read your 'data/cert/privateKey.pem' file, is it saved with utf-8 encoding?

**Comment by pepitovadecurt** [comment]
> 
> 
> The error suggests that zeep cannot read your 'data/cert/privateKey.pem' file, is it saved with utf-8 encoding?

Exactly! I exported the certificate from Firefox and contains a tilde. I have converted the certificates to UTF8 with Notepad ++ removing the accents and now it works.
Many thanks.
