### ISSUE TITLE
updated from 0.11.0 to 0.12.0 and am now unable to import my WSDL

### ISSUE THREAD

**Issue by janos97** [mvantellingen/python-zeep#121]
I'm limited on what I can post publicly, but will make certain you have the necessary info (^_^)

0.11.0: Imports WSDL perfectly (sanitized output)
(zeep_0.11.0) C:\Users\janos\Documents\zeep_test\w2oss_wsdl>python -mzeep Service.wsdl
Prefixes:
     ns0: http://www.python-zeep.org/Imports
     ns2: http://www.sample.com/schemas/public/cm/open-api/persistency/operations
     ns3: http://www.sample.com/schemas/public/cm/open-api/common
     ns4: http://www.sample.com/schemas/public/cm/open-api/persistency/model
     ns5: http://www.sample.com/schemas/public/cm/open-api/persistency/metadata
     ns6: http://www.sample.com/schemas/public/cm/open-api/persistency/query

0.12.0: WSDL Import fails
(zeep_0.12.0) C:\Users\janos\Documents\zeep_test\saved_wsdl>python -mzeep Service.wsdl
Traceback (most recent call last):
  File "c:\python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\__main__.py", line 80, in <module>
    main(args)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\__main__.py", line 69, in main
    client = Client(args.wsdl_file, transport=transport)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\wsdl\wsdl.py", line 146, in __init__
    self.types = self.parse_types(doc)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\wsdl\wsdl.py", line 331, in parse_types
    self.wsdl._parser_context)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\xsd\schema.py", line 28, in __init__
    node, transport, location, self._parser_context, location)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\xsd\schema.py", line 161, in __init__
    visitor.visit_schema(node)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\xsd\visitor.py", line 96, in visit_schema
    self.process(node, parent=parent)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\xsd\visitor.py", line 48, in process
    result = visit_func(self, node, parent)
  File "C:\Users\janos\Documents\zeep_test\ENV\lib\site-packages\zeep\xsd\visitor.py", line 129, in visit_import
    ) % (location, namespace or '(null)', schema._location))
zeep.exceptions.XMLParseError: Conflicting import of schema located at 'intschema:xsd1' for the namespace '(null)', since the namespace was already imported with the schema located at 'intschema:xsd0'

**Comment by mvantellingen** [comment]
I'll look into it. But if you could e-mail me the wsdl that would make things easier for me

**Comment by janos97** [comment]
As requested, I sent examples directly via email. I cannot thank you enough for all your hard work!

**Comment by mvantellingen** [comment]
Should be fixed now; I've also updated the python -mzeep output to list the namespace prefix of each type and element.
