### ISSUE TITLE
Async Client initialised with a file-url for the wsdl results in httpcore.UnsupportedProtocol: Unsupported URL protocol 'file'

### ISSUE THREAD

**Issue by AndrewMagerman** [mvantellingen/python-zeep#1211]
Async Client initialised with a file-url for the wsdl

    wsdl_file = BASE_DIR / 'mywsdl.wsdl'
    client = zeep.AsyncClient(wsdl=wsdl_file.as_uri(),
                              transport=AsyncTransport(verify_ssl=False),
                              settings=Session(),
                              )

results in 

    Traceback (most recent call last):
      File "venv\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
        yield
      File "venv\lib\site-packages\httpx\_client.py", line 861, in _send_single_request
        ext={"timeout": timeout.as_dict()},
      File "venv\lib\site-packages\httpx\_transports\default.py", line 102, in request
        return self._pool.request(method, url, headers=headers, stream=stream, ext=ext)
      File "venv\lib\site-packages\httpcore\_sync\connection_pool.py", line 191, in request
        raise UnsupportedProtocol(f"Unsupported URL protocol {scheme!r}")
    httpcore.UnsupportedProtocol: Unsupported URL protocol 'file'

Looks like a basic restriction from httpcore, perhaps include this in the known issues?

**Comment by lxop** [comment]
The easiest solution to this problem is to specify the WSDL file location as a path without the `file://` schema, and then it loads fine. The synchronous client also accepts local WSDL paths without the `file://` schema.

The code could be updated to work with a path including the schema by updating `Transport.load()` to perform the equivalent of the `else:` block in that method when the `file` schema is detected, after stripping it off the front.

**Comment by AndrewMagerman** [comment]
I can confirm that this works. Both the synchronous and asynchronous clients accept the file as a direct input. Caveat: this is old-style os.paths, so if you're using the wonderful pathlib library you'll have to convert it to string.
