### ISSUE TITLE
Loading scheme with empty restriction

### ISSUE THREAD

**Issue by alex-eri** [mvantellingen/python-zeep#1259]
xsd part is:

```
<xs:simpleType name="DocumentRef.ЗаданиеТорговомуПредставителю">
<xs:restriction/>
</xs:simpleType>
```

fails on function [visit_restriction_simple_type](https://github.com/mvantellingen/python-zeep/blob/4e16b7726b5027e83d0dbe911bd45f153b7a09dc/src/zeep/xsd/visitor.py#L698) because there is no children.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/client.py", line 73, in __init__
    self.wsdl = Document(wsdl, self.transport, settings=self.settings)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/wsdl/wsdl.py", line 92, in __init__
    self.load(location)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/wsdl/wsdl.py", line 97, in load
    root_definitions = Definition(self, document, self.location)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/wsdl/wsdl.py", line 193, in __init__
    self._load(doc)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/wsdl/wsdl.py", line 198, in _load
    self.parse_types(doc)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/wsdl/wsdl.py", line 330, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/schema.py", line 111, in add_documents
    document = self.create_new_document(node, location)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/schema.py", line 195, in create_new_document
    schema.load(self, node)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/schema.py", line 421, in load
    visitor.visit_schema(node)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/visitor.py", line 165, in visit_schema
    self.process(child, parent=node)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/visitor.py", line 93, in process
    result = visit_func(self, node, parent)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/visitor.py", line 544, in visit_simple_type
    base_type = self.visit_restriction_simple_type(child, node)
  File "/home/eri/.local/lib/python3.9/site-packages/zeep/xsd/visitor.py", line 725, in visit_restriction_simple_type
    if children[0].tag == tags.simpleType:
IndexError: list index out of range
```

**Comment by blackhold** [comment]
Hi! I have the same problem, the wsdl file I have the type definition is to "xsd:Array". I'm trying the possibility to pass a schema to enable this type (https://schemas.xmlsoap.org/soap/encoding/) but I don't know if is the correct way.

<message name="getLineasRequest">
  <part name="datos" type="xsd:Array" /></message>

My provider offers me the service like this. I will try if he can fix this, but I think is so complicated.

Where can I go now? if I load a custom wsdl file changing Array to string, zeep loads services OK, but then if I try to send a string formated as array it returns error:

(Pdb) client.service.getLineas('"user": "XXXX", "pass": "XXXX"')
'0003'

Some help will be grateful!

Thanks you much.
