### ISSUE TITLE
Error when WSDL file contains '[]'

### ISSUE THREAD

**Issue by gsw945** [mvantellingen/python-zeep#132]
When i test [Chamilo WSDL](https://campus.chamilo.org/main/webservices/soap.php?wsdl) with zeep:
```python
from zeep import Client

wsdl_url = 'https://campus.chamilo.org/main/webservices/soap.php?wsdl'
client = Client(wsdl_url)
# ...other code...
```
I got error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/__main__.py", line 80, in <module>
    main(args)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/__main__.py", line 69, in main
    client = Client(args.wsdl_file, transport=transport)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/wsdl/wsdl.py", line 62, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/wsdl/wsdl.py", line 156, in __init__
    self.messages = self.parse_messages(doc)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/wsdl/wsdl.py", line 320, in parse_messages
    msg = definitions.AbstractMessage.parse(self, msg_node)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/wsdl/definitions.py", line 58, in parse
    part_type = qname_attr(part, 'type', tns)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/utils.py", line 16, in qname_attr
    return as_qname(value, node.nsmap, target_namespace)
  File "/home/gsw/vev_chamilo_py3/lib/python3.4/site-packages/zeep/utils.py", line 24, in as_qname
    return etree.QName(namespace, local)
  File "src/lxml/lxml.etree.pyx", line 1831, in lxml.etree.QName.__init__ (src/lxml/lxml.etree.c:61175)
  File "src/lxml/apihelpers.pxi", line 1626, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:32662)
ValueError: Invalid tag name 'user_id[]'
```
I don't know if it's wrong to the definition of WSDL, or until now zeep did not support to parse WSDL file which containing '[]'.

**Comment by mvantellingen** [comment]
The QName values are invalid according to libxml2. Not sure what I can do about that.  xmllint fails to parse it and tools like http://xsd2xml.com/ also fail. 

```xsd
<xsd:schema 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
  xmlns:tns="http://test.python-zeep.org/main"
  targetNamespace="http://test.python-zeep.org/main">
  <xsd:complexType name="test[]">
    <xsd:sequence>
      <xsd:element name="item" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:element name="container" type="tns:test[]"/>
</xsd:schema>
```

**Comment by gsw945** [comment]
thank you very much ,chamilo's wsdl is invalid.
