### ISSUE TITLE
Zeep does not correctly handle ONVIF WSDL 

### ISSUE THREAD

**Issue by EmpireofKings** [mvantellingen/python-zeep#1348]
Hello all, 

I am using zeep 4.2.0, with WSDL v1.1. 

I am attempting to implement ONVIF via zeep, but i am seeing many issues in the responses, they are either incomplete, incorrectly parsed or simply fail to work.

Quick and easy examples to reproduce failure cases.

python3.7 -m zeep https://www.onvif.org/ver10/device/wsdl/devicemgmt.wsdl
python3.7 -m zeep https://www.onvif.org/ver10/events/wsdl/event.wsdl
python3.7 -m zeep https://www.onvif.org/ver20/media/wsdl/media.wsdl

`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/__main__.py", line 92, in <module>
    main(args)
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/__main__.py", line 87, in main
    client.wsdl.dump()
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/wsdl/wsdl.py", line 124, in dump
    value = type_obj.signature(schema=self.types)
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/xsd/types/complex.py", line 506, in signature
    part = element.signature(schema, standalone=False)
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/xsd/elements/indicators.py", line 269, in signature
    value = element.signature(schema, standalone=False)
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/xsd/elements/element.py", line 315, in signature
    value = self.type.signature(schema, standalone=False)
  File "/usr/local/lib/python3.7/dist-packages/zeep-4.2.0-py3.7.egg/zeep/xsd/types/complex.py", line 513, in signature
    value = ", ".join(parts)
TypeError: sequence item 0: expected str instance, NoneType found
`

Is there something wrong with ONVIF WSDL ? Am i doing something wrong ? or can zeep only handle very simply WSDL docs ???

In my testing, suds works without issue, so zeep should be able to handle ONVIF aswell.

**Comment by EmpireofKings** [comment]
Okay so, you can edit zeep/xsd/types/complex.py and replace the function signature with this below... 

It simply, ignores the error, it does not solve the root issue of the problem, but will allow you to run the script.

```

def signature(self, schema=None, standalone=True):
        parts = []
        for name, element in self.elements_nested:
            part = element.signature(schema, standalone=standalone)
            parts.append(part)

        for name, attribute in self.attributes:
            part = "%s: %s" % (name, attribute.signature(schema, standalone=standalone))
            parts.append(part)
        try:
            value = ", ".join(parts)
        except:
            value = ""
        if standalone:
            return "%s(%s)" % (self.get_prefixed_name(schema), value)
        else:
            return value

```

The core issue of this library not being able to correctly parse complex SOAP commands still persists, i am not sure why, but its been an unresolved issue since 2016. 

I see that the library is being continuously updated, but most of the issues are unfortunately being ignored by the maintainer. 

The ONVIF community is one of the largest users of this library, so i will try to help as much as i can.

**Comment by kaburagisec** [comment]
You can see the example [pull_live_events.py](https://github.com/nirsimetri/onvif-python/blob/main/examples/pull_live_events.py) from the [nirsimetri/onvif-python](https://github.com/nirsimetri/onvif-python) library
