### ISSUE TITLE
Disable XML-verification

### ISSUE THREAD

**Issue by Mad-Onion** [mvantellingen/python-zeep#138]
Hi everyone,
I'm trying to use zeep with a SOAP-webservice on our HP MSM WLAN-controllers by loading their provided wsdl-file.
When calling the client-constructor, I get this error:
```
Traceback (most recent call last):                                                                                                                                                
  File "ap_monitor.py", line 9, in <module>                                                                                                                                       
    client = Client('https://172.16.96.5/soapapi.wsdl', transport = transport)                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 52, in __init__                                                                                              
    self.wsdl = Document(wsdl, self.transport)                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 62, in __init__                                                                                           
    root_definitions = Definition(self, document, self.location)                                                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 155, in __init__                                                                                          
    self.types = self.parse_types(doc)                                                                                                                                            
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 304, in parse_types                                                                                       
    self.wsdl._parser_context)                                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/schema.py", line 28, in __init__                                                                                          
    node, transport, location, self._parser_context, location)                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/schema.py", line 171, in __init__                                                                                         
    visitor.visit_schema(node)                                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 97, in visit_schema                                                                                     
    self.process(node, parent=parent)                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 49, in process                                                                                          
    result = visit_func(self, node, parent)                                                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 177, in visit_import                                                                                    
    self.parser_context, base_url)                                                                                                                                                
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/schema.py", line 171, in __init__                                                                                         
    visitor.visit_schema(node)                                                                                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 97, in visit_schema                                                                                     
    self.process(node, parent=parent)                                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 49, in process                                                                                          
    result = visit_func(self, node, parent)                                                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 439, in visit_complex_type                                                                              
    element = self.process(child, node)                                                                                                                                           
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 49, in process                                                                                          
    result = visit_func(self, node, parent)                                                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 637, in visit_sequence                                                                                  
    item = self.process(child, node)                                                                                                                                              
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 49, in process                                                                                          
    result = visit_func(self, node, parent)                                                                                                                                       
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 263, in visit_element                                                                                   
    xsd_type = self._get_type(node_type.text)                                                                                                                                     
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/visitor.py", line 806, in _get_type                                                                                       
    retval = self.schema.get_type(name, default=None)                                                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/schema.py", line 226, in get_type                                                                                         
    self._check_namespace_reference(name)                                                                                                                                         
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/schema.py", line 306, in _check_namespace_reference                                                                       
    ) % (self._target_namespace, ns))                                                                                                                                             
zeep.exceptions.XMLParseError: References from this schema ('http://www.procurve_mobility_msm.com/SOAP/API/1.0/') to components in the namespace 'http://www.procurve_mobility_msm
.com/SOAP/API/1.7/' are not allowed, since not indicated by an import statement.
```

As I have no influence on the wsdl-file, my question is, if it's possible to disable the XML-verification or if there is a workaround.

Best regards
Tobias

**Comment by mvantellingen** [comment]
It's not possible to disable xml verification. Do you have a wsdl available so that i can check if this is a valid error or a bug?

**Comment by Mad-Onion** [comment]
Sure, see the file attached.
[MSM_soapapi.wsdl.txt](https://github.com/mvantellingen/python-zeep/files/373336/MSM_soapapi.wsdl.txt)

**Comment by mvantellingen** [comment]
The wsdl contains two xsd:schema elements. The second one references the first one but is missing an import statement. You can modify the wsdl and add:

     <import namespace="http://www.procurve_mobility_msm.com/SOAP/API/1.7/"/>

As first child to the second schema (line ~35914).
