### ISSUE TITLE
SSL Self signed certificate error

### ISSUE THREAD

**Issue by Kozubi** [mvantellingen/python-zeep#14]
Hello,
First thank for awesome library. Second is there possibility to turn off ssl signature verification?

Becasue I have this error:

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python34\lib\site-packages\zeep\client.py", line 45, in __init__
    self.wsdl = WSDL(wsdl, self.transport)
  File "C:\Python34\lib\site-packages\zeep\wsdl\wsdl.py", line 32, in __init__
    document = self._load_content(location)
  File "C:\Python34\lib\site-packages\zeep\wsdl\wsdl.py", line 79, in _load_content
    location, self.transport, self._parser_context, self.location)
  File "C:\Python34\lib\site-packages\zeep\parser.py", line 39, in load_external
    response = transport.load(url)
  File "C:\Python34\lib\site-packages\zeep\transports.py", line 19, in load
    response = requests.get(url, timeout=self.timeout, verify=self.verify)
  File "C:\Python34\lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python34\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

**Comment by mvantellingen** [comment]
hi @Kozubi, that is possible since the last release (0.5). You can use the following:
```python
from zeep import Client
from zeep.transport import Transport

transport = Transport(verify=False)
client = Client(wsdl, transport=transport)
```

**Comment by Kozubi** [comment]
Thanks is working, well almost im my case
Now when I try to connect with this url i have this:

> C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "C:/Users/xxx/PycharmProjects/test/to_Delete.py", line 8, in <module>
    client = Client(url, transport=transport)
  File "C:\Python34\lib\site-packages\zeep\client.py", line 48, in __init__
    self.service = self.bind()
  File "C:\Python34\lib\site-packages\zeep\client.py", line 63, in bind
    service = list(self.wsdl.services.values())[0]
IndexError: list index out of range

**Comment by mvantellingen** [comment]
Is the wsdl publicly available?

**Comment by Kozubi** [comment]
No

**Comment by mvantellingen** [comment]
Ok, well it seems that the wsdl has no services defined. You can check that by loading it into soap-ui or open the file and look for a <service> definition at the bottom.

**Comment by Kozubi** [comment]
Yes it could be so.. thanks :)

**Comment by onimisionipe** [comment]
please note that it is 'zeep.transports' and not 'zeep.transport'

**Comment by arash7** [comment]
What if I do have the crt file and I want to use the certificate to verify my connection?

**Comment by steers** [comment]
You should be able to provide a path to the certificate as a value for verify:
http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification
