### ISSUE TITLE
AttributeError: 'QName' object has no attribute 'name'

### ISSUE THREAD

**Issue by cheuel-novero** [mvantellingen/python-zeep#15]
I trying to use zeep to get access to Polarion. When I try to inspect the wsdl file, I get an error:

```
python3 -mzeep http://almdemo.polarion.com/polarion/ws/services/TrackerWebService?wsdl

Prefixes:
     ns0: http://ws.polarion.com/TrackerWebService-impl
     ns2: http://ws.polarion.com/TrackerWebService-types
     ns1: http://ws.polarion.com/types
     ns4: http://ws.polarion.com/PlanningWebService-types
     ns3: http://ws.polarion.com/ProjectWebService-types
     ns5: http://ws.polarion.com/TrackerWebService

Global types:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/zeep/__main__.py", line 73, in <module>
    main(args)
  File "/usr/lib/python3/dist-packages/zeep/__main__.py", line 68, in main
    client.wsdl.dump()
  File "/usr/lib/python3/dist-packages/zeep/wsdl/wsdl.py", line 57, in dump
    for type_obj in sorted(type_instances, key=lambda k: six.text_type(k)):
  File "/usr/lib/python3/dist-packages/zeep/wsdl/wsdl.py", line 57, in <lambda>
    for type_obj in sorted(type_instances, key=lambda k: six.text_type(k)):
  File "/usr/lib/python3/dist-packages/zeep/xsd/types.py", line 208, in __str__
    return '%s(%s)' % (self.__class__.__name__, self.signature())
  File "/usr/lib/python3/dist-packages/zeep/xsd/types.py", line 157, in signature
    for name, element, container in self.fields()
  File "/usr/lib/python3/dist-packages/zeep/xsd/types.py", line 157, in <listcomp>
    for name, element, container in self.fields()
  File "/usr/lib/python3/dist-packages/zeep/xsd/elements.py", line 81, in _signature
    self.type.name, '[]' if self.max_occurs != 1 else ''
AttributeError: 'QName' object has no attribute 'name'
```

**Comment by mvantellingen** [comment]
Thanks, should be fixed on master
