### ISSUE TITLE
'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by mattpepin** [mvantellingen/python-zeep#152]
In some cases, it seems that None is the value of a "Any" attribute. In that case, it crashes. If I add a simple None check, it works (in xsd/elements.py, lines 317-320):

```
    def render(self, parent, value):
        if value:
           for name, val in value.items():
               parent.set(name, val)
```

```
Traceback (most recent call last):
  File "onvif-test.py", line 94, in <module>
    print(o.media.GetStreamUri('prof0'))
  File "test/lib/python3.5/site-packages/zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "test/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 79, in send
    serialized = operation_obj.create(*args, **kwargs)
  File "test/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 245, in create
    return self.input.serialize(*args, **kwargs)
  File "test/lib/python3.5/site-packages/zeep/wsdl/messages.py", line 100, in serialize
    self.body.render(body, body_value)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 253, in render
    self._render_value_item(parent, value)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 270, in _render_value_item
    return self.type.render(node, value)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 271, in render
    element.render(parent, value)
  File "test/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 186, in render
    element.render(parent, element_value)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 253, in render
    self._render_value_item(parent, value)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 270, in _render_value_item
    return self.type.render(node, value)
  File "test/lib/python3.5/site-packages/zeep/xsd/types.py", line 262, in render
    attribute.render(parent, attr_value)
  File "test/lib/python3.5/site-packages/zeep/xsd/elements.py", line 318, in render
    for name, val in value.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

Thanks!

**Comment by mvantellingen** [comment]
Thanks!!
