### ISSUE TITLE
Error with xsd.AnyObject

### ISSUE THREAD

**Issue by DiegoAstiazaran** [mvantellingen/python-zeep#154]
I have this code.
```
import zeep
from zeep.transports import Transport
from zeep import xsd

ucmdb = None

def connect(): #checar wsdl
	global ucmdb
	credentials = ('admin', 'admin')
	t = Transport(cache=None, timeout=5000, http_auth=credentials)
	wsdl = "http://192.168.1.74:8080/axis2/services/UcmdbService?wsdl"
	ucmdb = zeep.Client(wsdl = wsdl, transport = t)
	#wsdl = "http://10.128.42.140:8080/axis2/services/UcmdbService?wsdl"
	#wsdl = "http://192.168.1.74:8080/axis2/services/UcmdbService?wsdl"
	#wsdl = "http://192.168.1.74:8080/IOrderExecutor/?wsdl"

def main():
	connect()
	intProp_type = ucmdb.get_element('ns17:IntProp')
	intProp = xsd.AnyObject(intProp_type, intProp_type(name = "slots", value = 56 ))

if __name__ == '__main__':
	main()
```
And this error occurs when executing the script, simple xsd anyobject is not being created.

```
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\zeep\xsd\schema.py", line 75, in get_element
    return schema._elements[qname]
KeyError: <lxml.etree.QName object at 0x000002159CEFA800>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ejemplo.py", line 23, in <module>
    main()
  File "ejemplo.py", line 19, in main
    intProp_type = ucmdb.get_element('ns17:IntProp')
  File "C:\Python\lib\site-packages\zeep\client.py", line 119, in get_element
    return self.wsdl.types.get_element(name)
  File "C:\Python\lib\site-packages\zeep\xsd\schema.py", line 85, in get_element
    qname.localname, qname.namespace, known_elements or ' - '))
KeyError: "No element 'IntProp' in namespace http://schemas.hp.com/ucmdb/ui/1/types. Available elements are:  - "
```

**Comment by mvantellingen** [comment]
Can you post the wsdl? Or the relevant output from ``python -mzeep <wsd>``

**Comment by DiegoAstiazaran** [comment]
If I try the command:
`pyhton -mzeep <http://192.168.1.74:8080/axis2/services/UcmdbService?wsdl>`
, this message appears: 
The command syntax is incorrect.

**Comment by mvantellingen** [comment]
You need to remove the <> ;-)

**Comment by DiegoAstiazaran** [comment]
I considered it but this appears in that case
"pyhton" is not recognized as an internal or external command, operable program or batch file .

**Comment by mvantellingen** [comment]
Yeah so you need to run 'python -mzeep <url>'. I'm closing this now :-)
