### ISSUE TITLE
zeep.exceptions.XMLParseError: References from this schema (xxx) to components in the namespace (xxx) are not allowed, since not indicated by an import statement

### ISSUE THREAD

**Issue by sulbig** [mvantellingen/python-zeep#159]
I am trying to use the Cisco MeetingPlace MeetingService WSDL (attached), and am getting the error below when creating a Client instance. Problem appears to be with {http://webservices.meetingplace.cisco.com}FaultDetail. I don't get this error in other XML/WSDL tools (e.g., Soap-UI or Visual Studio), and not sure how to satisfy the error or workaround it.

Error:

    Traceback (most recent call last):
      File "C:/Users/*****/PycharmProjects/misc_modules/meetingplace_test.py", line 9, in <module>
        client = zeep.Client(wsdl=wsdl_buffer)
      File "C:\Python27\lib\site-packages\zeep\client.py", line 52, in __init__
        self.wsdl = Document(wsdl, self.transport)
      File "C:\Python27\lib\site-packages\zeep\wsdl\wsdl.py", line 62, in __init__
        root_definitions = Definition(self, document, self.location)
      File "C:\Python27\lib\site-packages\zeep\wsdl\wsdl.py", line 156, in __init__
        self.types = self.parse_types(doc)
      File "C:\Python27\lib\site-packages\zeep\wsdl\wsdl.py", line 311, in parse_types
        self.wsdl._parser_context)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 28, in __init__
        node, transport, location, self._parser_context, location)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 182, in __init__
        visitor.visit_schema(node)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 104, in visit_schema
        self.process(node, parent=parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 50, in process
        result = visit_func(self, node, parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 184, in visit_import
        self.parser_context, base_url)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 182, in __init__
        visitor.visit_schema(node)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 104, in visit_schema
        self.process(node, parent=parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 50, in process
        result = visit_func(self, node, parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 184, in visit_import
        self.parser_context, base_url)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 182, in __init__
        visitor.visit_schema(node)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 104, in visit_schema
        self.process(node, parent=parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 50, in process
        result = visit_func(self, node, parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 184, in visit_import
        self.parser_context, base_url)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 182, in __init__
        visitor.visit_schema(node)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 104, in visit_schema
        self.process(node, parent=parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 50, in process
        result = visit_func(self, node, parent)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 275, in visit_element
        xsd_type = self._get_type(node_type.text)
      File "C:\Python27\lib\site-packages\zeep\xsd\visitor.py", line 839, in _get_type
        retval = self.schema.get_type(name, default=None)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 243, in get_type
        self._check_namespace_reference(name)
      File "C:\Python27\lib\site-packages\zeep\xsd\schema.py", line 341, in _check_namespace_reference
        ) % (self._target_namespace, ns))
    zeep.exceptions.XMLParseError: References from this schema ('http://mpe.cisco.com/webservices/services/MeetingService') to components in the namespace 'http://webservices.meetingplace.cisco.com' are not allowed, since not indicated by an import statement.

My code:

    from StringIO import StringIO
    import zeep

    wsdl_buffer = None
    with open('wsdl/MeetingService.wsdl', 'r') as wsdl_file:
        wsdl_buffer = StringIO(wsdl_file.read())

    client = zeep.Client(wsdl=wsdl_buffer)
    print(client.wsdl.dump())

Where the error is raised (schema.py, line 337):

    def _check_namespace_reference(self, name):   # self: <SchemaDocument(location='intschema:xsd3', tns='http://mpe.cisco.com/webservices/services/MeetingService', is_empty=False)>
        """See https://www.w3.org/TR/xmlschema-1/#src-resolve"""
        ns = name.namespace
        if ns != self._target_namespace and ns not in self._imports.keys():
            raise exceptions.XMLParseError((
                "References from this schema (%r) to components in the " +
                "namespace '%s' are not allowed, since not indicated by an "
                "import statement."
            ) % (self._target_namespace, ns))

Variable values at time of error:

    self:  <SchemaDocument(location='intschema:xsd3', tns='http://mpe.cisco.com/webservices/services/MeetingService', is_empty=False)>
    self._target_namespace:  'http://mpe.cisco.com/webservices/services/MeetingService'
    self._imports:  OrderedDict([('http://beans.systemConfiguration.businesslayer.meetingplace.cisco.com', <SchemaDocument(location='intschema:xsd8', tns='http://beans.systemConfiguration.businesslayer.meetingplace.cisco.com', is_empty=False)>), ('http://beans.meeting.businesslayer.meetingplace.cisco.com', <SchemaDocument(location='intschema:xsd0', tns='http://beans.meeting.businesslayer.meetingplace.cisco.com', is_empty=False)>), ('http://custom.data.meetingplace.cisco.com', <SchemaDocument(location='intschema:xsd5', tns='http://custom.data.meetingplace.cisco.com', is_empty=False)>), ('http://beans.webservices.meetingplace.cisco.com', <SchemaDocument(location='intschema:xsd4', tns='http://beans.webservices.meetingplace.cisco.com', is_empty=False)>), ('http://enums.meeting.businesslayer.meetingplace.cisco.com', <SchemaDocument(location='intschema:xsd2', tns='http://enums.meeting.businesslayer.meetingplace.cisco.com', is_empty=False)>)])
    name:  {http://webservices.meetingplace.cisco.com}FaultDetail
    ns:  u'http://webservices.meetingplace.cisco.com'

[MeetingService.zip](https://github.com/mvantellingen/python-zeep/files/405883/MeetingService.zip)

**Comment by sergray** [comment]
I have the same issue as well with multiple WSDLs for private services.

**Comment by mvantellingen** [comment]
It seems that the xsd schema's within the wsdl file don't import each other. Which should be necessary according to my reading of the really vague specs. 

I've decided to just get maximum compatibility with all the wsdl's around and try to work around this by making the schema's accessible to each other, this will take some work and testing however. I might have some time later this week.

**Comment by sergray** [comment]
@mvantellingen I will be glad to help with testing

**Comment by mvantellingen** [comment]
See #171

**Comment by mvantellingen** [comment]
Just merged that the branch in master, it now parses the wsdl correctly.
