### ISSUE TITLE
ValueError inspecting wsdl file

### ISSUE THREAD

**Issue by joestubbs** [mvantellingen/python-zeep#168]
Hi,

I am trying to inspect a wsdl file UserAdmin-am19.wsdl.txt (attached) with zeep using 
python -mzeep UserAdmin-am19.wsdl.txt 
but I get:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jstubbs/virtualenvs/wsdl/lib/python2.7/site-packages/zeep/__main__.py", line 80, in <module>
    main(args)
  File "/home/jstubbs/virtualenvs/wsdl/lib/python2.7/site-packages/zeep/__main__.py", line 69, in main
    client = Client(args.wsdl_file, transport=transport)
  File "/home/jstubbs/virtualenvs/wsdl/local/lib/python2.7/site-packages/zeep/client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/home/jstubbs/virtualenvs/wsdl/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 63, in __init__
    root_definitions.resolve_imports()
  File "/home/jstubbs/virtualenvs/wsdl/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 217, in resolve_imports
    binding.resolve(self)
  File "/home/jstubbs/virtualenvs/wsdl/local/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 187, in resolve
    operation.resolve(definitions)
  File "/home/jstubbs/virtualenvs/wsdl/local/lib/python2.7/site-packages/zeep/wsdl/http.py", line 166, in resolve
    self.output.resolve(definitions, self.abstract.output)
  File "/home/jstubbs/virtualenvs/wsdl/local/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 436, in resolve
    "Multiple parts for message while no matching part found")
ValueError: Multiple parts for message while no matching part found

I am a bit new to SOAP, but I have been able to load this file in soapUI without errors. I will continue to investigate, but thought I would post here in case I am missing something obvious.

Thanks!

[UserAdmin-am19.wsdl.txt](https://github.com/mvantellingen/python-zeep/files/421141/UserAdmin-am19.wsdl.txt)

**Comment by joestubbs** [comment]
Hi,

In case it is helpful, the Python suds library (as well as this Python3 port: https://bitbucket.org/jurko/suds/overview) are able to parse the same wsdl file. I apologize for not spending more time digging into the issue. I hope to have more time in September.

**Comment by mvantellingen** [comment]
Should be fixed in master now, thanks for the report. Could you let me know if it isn't?
