### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Netex** [mvantellingen/python-zeep#223]
The below occurs on zeep 0.19.0, it worked on 0.18.1.

```
zeep.transports: HTTP Post to https://127.0.0.1:8015/management/services/UDPService:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:ns5="http://webservice.edge.arcserve.ca.com/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns5:login>
      <username>administrator</username>
      <password>BBB</password>
    </ns5:login>
  </soap-env:Body>
</soap-env:Envelope>

zeep.transports: HTTP Response from https://127.0.0.1:8015/management/services/UDPService (status: 200):
<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:loginResponse xmlns:ns2="http://webservice.edge.arcserve.ca.com/" xmlns:ns3="http://data.webservice.arcflash.ca.com/xsd" xmlns:ns4="http://backup.data.webservice.arcflash.ca.com/xsd" xmlns:ns5="http://export.data.webservice.arcflash.ca.com/xsd" xmlns:ns6="http://vsphere.data.webservice.arcflash.ca.com/xsd"/></S:Body></S:Envelope>
Traceback (most recent call last):
  File "D:/Projects/zeep_test/arcserve.py", line 36, in <module>
    client.service.login('administrator', 'BBB')
  File "D:\venv\zeep\lib\site-packages\zeep\client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "D:\venv\zeep\lib\site-packages\zeep\wsdl\bindings\soap.py", line 109, in send
    return self.process_reply(client, operation_obj, response)
  File "D:\venv\zeep\lib\site-packages\zeep\wsdl\bindings\soap.py", line 147, in process_reply
    return operation.process_reply(doc)
  File "D:\venv\zeep\lib\site-packages\zeep\wsdl\bindings\soap.py", line 300, in process_reply
    return self.output.deserialize(envelope)
  File "D:\venv\zeep\lib\site-packages\zeep\wsdl\messages\soap.py", line 86, in deserialize
    if len(result) > 1:
TypeError: object of type 'NoneType' has no len()
```

Appears that commit "[Dry-up message handling between document/rpc](https://github.com/mvantellingen/python-zeep/commit/89e00ee41cf2c54c8a66eeae80b272d55c4ea8b2)" broke it

**Comment by TheHugoZ** [comment]
Same issue here

**Comment by mvantellingen** [comment]
That's a big oops. I've already have a fix locally, just need to add a unittest for it and then i'll commit it and release a 0.19.1

**Comment by mvantellingen** [comment]
Should be fixed now
