### ISSUE TITLE
AttributeError: 'String' object has no attribute '_value_class'

### ISSUE THREAD

**Issue by bjarnagin** [mvantellingen/python-zeep#226]
Hi, I'm having trouble either executing a wsdl function or parsing its response--I'm not sure which.

Zeep appears to be formatting the request correctly, but an exception is thrown when the `administrationServiceRequest` function is called. Exception text below.

I'm using Zeep version 0.18.1.

```py
import base64
from zeep import Client

class YFImport:
    url = 'http://bi.croptrak.com/services/{name}?wsdl'
    services = {
        'admin': 'AdministrationService',
        'report': 'ReportService',
        'version': 'VersionService'
    }

    def __init__(self, username='', password='', service='admin'):
        self.username = username
        self.password = password
        if service not in YFImport.services.keys():
            raise TypeError('Invalid service')
        else:
            self.service = service
        self.client = Client(YFImport.url.format(
            name=YFImport.services[self.service]))

    def get_import_content(self, org_id, file_path):
        service_request = self.client.get_type('ns0:AdministrationServiceRequest')
        params_fn = self.client.get_type('ns0:ArrayOf_soapenc_string')

        encoded_file = []
        with open(file_path, 'rb') as f:
            for line in f:
                encoded_file.append(base64.b64encode(line))

        request_data = {
            'loginId': self.username,
            'password': self.password,
            'orgId': org_id,
            'function': 'GETIMPORTCONTENT',
            'parameters': encoded_file
        }
        
        req = service_request(**request_data)
        # return req

        res = self.client.service.remoteAdministrationCall(req)
        return res.getContentResources()

f = ''
client = YFImport()
client.get_import_content(12602, f)
```

```py
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    res = c.client.service.remoteAdministrationCall(req)
  File "/usr/local/lib/python3.5/site-packages/zeep/client.py", line 24, in __call__
    self._op_name, args, kwargs)
  File "/usr/local/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 103, in send
    options=options)
  File "/usr/local/lib/python3.5/site-packages/zeep/wsdl/soap.py", line 61, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 266, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/zeep/wsdl/messages.py", line 101, in serialize
    self.body.render(body, body_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 300, in render
    self._render_value_item(parent, value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 324, in _render_value_item
    return self.type.render(node, value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/types.py", line 339, in render
    element.render(parent, element_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 197, in render
    element.render(parent, element_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 300, in render
    self._render_value_item(parent, value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 324, in _render_value_item
    return self.type.render(node, value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/types.py", line 339, in render
    element.render(parent, element_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 197, in render
    element.render(parent, element_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 300, in render
    self._render_value_item(parent, value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 324, in _render_value_item
    return self.type.render(node, value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/types.py", line 339, in render
    element.render(parent, element_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/indicators.py", line 197, in render
    element.render(parent, element_value)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 123, in render
    self._render_value_item(parent, val)
  File "/usr/local/lib/python3.5/site-packages/zeep/xsd/elements.py", line 135, in _render_value_item
    isinstance(value, (etree._Element, self.restrict._value_class))
AttributeError: 'String' object has no attribute '_value_class'
```

**Comment by mvantellingen** [comment]
Should be fixed in master, let me know

**Comment by bjarnagin** [comment]
Fix confirmed. Thank you!
