### ISSUE TITLE
Attempting to iterate base_element when its type is Element fails

### ISSUE THREAD

**Issue by magixx** [mvantellingen/python-zeep#248]
Version: 0.21.0 w/ Python 3.5
WSDL: Not available
Example:

```python
from zeep import Client
wsdl3 = 'OssCoreAuthenticationService.xml'
client = Client(wsdl3)
```

Getting the following error when trying to get my wsdl:
```
Traceback (most recent call last):
  File "/home/magixx/PycharmProjects/soap_testing/simple_client.py", line 6, in <module>
    client = Client(wsdl3)
  File "/home/magixx/src/zeep/src/zeep/client.py", line 53, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/home/magixx/src/zeep/src/zeep/wsdl/wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/home/magixx/src/zeep/src/zeep/wsdl/wsdl.py", line 152, in __init__
    self.parse_imports(doc)
  File "/home/magixx/src/zeep/src/zeep/wsdl/wsdl.py", line 231, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "/home/magixx/src/zeep/src/zeep/wsdl/wsdl.py", line 154, in __init__
    self.parse_types(doc)
  File "/home/magixx/src/zeep/src/zeep/wsdl/wsdl.py", line 268, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "/home/magixx/src/zeep/src/zeep/xsd/schema.py", line 42, in add_documents
    document.resolve()
  File "/home/magixx/src/zeep/src/zeep/xsd/schema.py", line 262, in resolve
    schema.resolve()
  File "/home/magixx/src/zeep/src/zeep/xsd/schema.py", line 262, in resolve
    schema.resolve()
  File "/home/magixx/src/zeep/src/zeep/xsd/schema.py", line 272, in resolve
    _resolve_dict(self._elements)
  File "/home/magixx/src/zeep/src/zeep/xsd/schema.py", line 266, in _resolve_dict
    new = obj.resolve()
  File "/home/magixx/src/zeep/src/zeep/xsd/elements.py", line 351, in resolve
    self.resolve_type()
  File "/home/magixx/src/zeep/src/zeep/xsd/elements.py", line 348, in resolve_type
    self.type = self.type.resolve()
  File "/home/magixx/src/zeep/src/zeep/xsd/types.py", line 90, in resolve
    return retval.resolve()
  File "/home/magixx/src/zeep/src/zeep/xsd/types.py", line 411, in resolve
    self._resolved = self.extend(self._extension)
  File "/home/magixx/src/zeep/src/zeep/xsd/types.py", line 453, in extend
    for item in reversed(base_element):
TypeError: argument to reversed() must be a sequence
```
Which is around /home/alex/src/zeep/src/zeep/xsd/types.py:450:
```python
            if isinstance(element, OrderIndicator):
                #if not isinstance(base_element, Sequence):
                #    print(base_element)
                for item in reversed(base_element):
                    element.insert(0, item)
```
Where base_element is the following object:
```python
base_element = {Element} _value_1()
 accepts_multiple = {bool} False
 attr_name = {str} '_value_1'
 default = {NoneType} None
 default_value = {NoneType} None
 is_global = {bool} False
 is_optional = {bool} False
 max_occurs = {int} 1
 min_occurs = {int} 1
 name = {str} '_value_1'
 nillable = {bool} False
 qname = {QName} _value_1
  localname = {str} '_value_1'
  namespace = {NoneType} None
  text = {str} '_value_1'
 type = {transferObject} transferObject()
  _attributes = {list} <class 'list'>: []
  _attributes_unwrapped = {list} <class 'list'>: []
  _element = {NoneType} None
  _extension = {NoneType} None
  _resolved = {transferObject} transferObject()
  _restriction = {NoneType} None
  _value_class = {type} <class 'zeep.objects.transferObject'>
  _xsd_name = {QName} {http://www.telcordia.com/fullfillment/platform/dto/v2}transferObject
  accepted_types = {tuple} <class 'tuple'>: (<class 'zeep.objects.transferObject'>,)
  attributes = {list} <class 'list'>: []
  elements = {list} <class 'list'>: []
  elements_nested = {list} <class 'list'>: []
  is_global = {bool} False
  name = {str} 'transferObject'
  qname = {QName} {http://www.telcordia.com/fullfillment/platform/dto/v2}transferObject
```

Any ideas what would cause this?

**Comment by mvantellingen** [comment]
I'm not able to reproduce it, so I'll need either access to the wsdl (you can mail it if you want) or the a part of the wsdl where the type is defined

**Comment by moiseshiraldo** [comment]
I'm getting the same `TypeError: argument to reversed() must be a sequence` at the same place (the `extend` method for the `ComplexType` class) when it tries to parse an element like this one:

```xml
<decodedCharacteristics sourcedFrom="QCE">
    <CSC13>M</CSC13>
    <CSE1>T</CSE1>
    <CSE13>T</CSE13>
    ...
    <ns3:VRD101 xmlns:ns3="http://...">0</ns3:VRD101>
    <ns3:ETD941 xmlns:ns3="http://...">M</ns3:ETD941>
    <option>1</option>
</decodedCharacteristics>
``` 

This is the corresponding part of the WSDL:

```xml
<xs:complexType abstract="true" name="DataItem">
    <xs:sequence/>
    <xs:attribute name="sourcedFrom" use="optional">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:minLength value="3"/>
          <xs:maxLength value="15"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
</xs:complexType>

<xs:complexType name="DecodedCharacteristics">
    <xs:complexContent>
      <xs:extension base="ccd:DataItem">
        <xs:sequence>
          <xs:choice minOccurs="0">
            <xs:element maxOccurs="999" minOccurs="0" name="characteristic" type="Characteristic"/>
            <xs:sequence>
              <xs:element minOccurs="0" name="CSC13" type="taggedCharsType">
                <xs:annotation>
                  <xs:documentation>Number of bankruptcies/IVA's last 6 years</xs:documentation>
                </xs:annotation>
              </xs:element>
              ...
              <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##targetNamespace" processContents="lax"/>
             </xs:sequence>
          </xs:choice>
          <xs:element maxOccurs="1" minOccurs="1" name="option">
            <xs:simpleType>
              <xs:restriction base="xs:int">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="999"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
</xs:complexType>
```
Having a quick look, my intuition tells me that the second `if` below should be checking the `base_element` instance type instead of `element`:

```python
if self._element and base_element:
    element = self._element.clone(self._element.name)
    if isinstance(element, OrderIndicator):
        for item in reversed(base_element):
            element.insert(0, item)
```

At least that solves the problem for me (see my commit below).

**Comment by magixx** [comment]
I've tried your fix and no errors occur anymore but I've yet to compare the output to something like SoapUI.

**Comment by moiseshiraldo** [comment]
I've just tried the latest version (0.23.0) and this problem seems to be fixed now.

**Comment by magixx** [comment]
Yep running the `python3 -mzeep` command now with version 0.23 seems to properly display the endpoint options so this ticket can be closed. Now I need to figure out how to use the endpoints with all the xsd/imports that original and further endpoints had to do.
