### ISSUE TITLE
Parsing WSDL returns TypeError: argument to reversed() must be a sequence 

### ISSUE THREAD

**Issue by kritsanapong** [mvantellingen/python-zeep#260]
Hi,

I am using zeep version 0.22.0 and was trying to parse a WSDL file, but got the error message "TypeError: argument to reversed() must be a sequence"

1. zeep version 0.22.0 on Python 3.4.4
2. WSDL location at https://webservices.sandbox.netsuite.com/wsdl/v2013_2_0/netsuite.wsdl
3. Example script
`
python -mzeep https://webservices.sandbox.netsuite.com/wsdl/v2013_2_0/netsuite.wsdl
`
4. Exception

```
Traceback (most recent call last):
   File "c:\Python34\Lib\runpy.py", line 170, in _run_module_as_main
      "__main__", mod_spec)
   File "c:\Python34\Lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\__main__.py", line 85, in <module>
      main(args)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\__main__.py", line 74, in main
      client = Client(args.wsdl_file, transport=transport)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\client.py",line 69, in __init__
      self.wsdl = Document(wsdl, self.transport)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\wsdl\wsdl.py", line 61, in __init__
      root_definitions = Definition(self, document, self.location)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\wsdl\wsdl.py", line 154, in __init__
      self.parse_types(doc)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\wsdl\wsdl.py", line 268, in parse_types
      self.types.add_documents(schema_nodes, self.location)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\xsd\schema.py", line 42, in add_documents
      document.resolve()
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\xsd\schema.py", line 275, in resolve
      schema.resolve()
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\xsd\schema.py", line 287, in resolve
      _resolve_dict(self._types)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\xsd\schema.py", line 279, in _resolve_dict
      new = obj.resolve()
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\xsd\types.py", line 416, in resolve
      self._resolved = self.extend(self._extension)
   File "D:\src\workspace\env\partner_service\lib\site-packages\zeep\xsd\types.py", line 456, in extend
      for item in reversed(base_element):
TypeError: argument to reversed() must be a sequence
```

Let me know if you need further information
Thanks,

**Comment by fmalina** [comment]
I experienced the same error. Using jaceksnet fork I was able to read WSDL.

    # sudo pip3 install -e git+git://github.com/jaceksnet/python-zeep.git#egg=python-zeep

    >>> from zeep import Client
    >>> WSDL_URL = 'https://webservices.sandbox.netsuite.com/wsdl/v2016_1_0/netsuite.wsdl'
    >>> client = Client(WSDL_URL)
    >>> client.service.ping()

Then I got:
AttributeError: Service has no operation 'ping'

**Comment by mvantellingen** [comment]
Should be fixed in master (thanks again @jaceksnet )

**Comment by mvantellingen** [comment]
Just did a quick 0.22.1 release containing the fix.
