### ISSUE TITLE
Error parsing a nightmare of a wsdl.

### ISSUE THREAD

**Issue by leefrankeFNC** [mvantellingen/python-zeep#262]
This is for a Siebel web service. I've been using this web service for a decade or more and I'll readily admit it is a complete nightmare.

I literally just started with Python so I'm sure I'm making some rookie mistakes.

The zeep version is the latest build (downloaded yesterday).

I attempted the first step:

python -mzeep "C:\Users\lfranke\Documents\Siebel\ITG\WebServices\Inbound\FNC Service Request.WSDL"

Here is the complete output from that:

C:\Users\lfranke>python -mzeep "C:\Users\lfranke\Documents\Siebel\ITG\WebService
s\Inbound\FNC Service Request.WSDL"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code exec code in run_globals
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\__main__.py", line 85, in <module>
    main(args)
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\__main__.py", line 74, in main
    client = Client(args.wsdl_file, transport=transport)
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\client.py", line 69, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\wsdl\wsdl.py",line 59, in __init__
    document = self._load_content(location)
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\wsdl\wsdl.py",line 127, in _load_content
    return load_external(location, self.transport, self.location)
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\parser.py", line 23, in load_external
    return parse_xml(response, base_url)
  File "C:\Python27\lib\site-packages\zeep-0.22.0-py2.7.egg\zeep\parser.py", line 15, in parse_xml
    raise XMLSyntaxError("Invalid XML content received (%s)" % exc)
zeep.exceptions.XMLSyntaxError: Invalid XML content received (xmlns:xsdLocal0: 'http://www.siebel.com/xml/Service Request Interface' is not a valid URI, line 3,
 column 17)

I'll attach the wsdl as a text file.
[FNC Service Request.txt](https://github.com/mvantellingen/python-zeep/files/597670/FNC.Service.Request.txt)

Here is the gist:
[WSDL](https://gist.github.com/leefrankeFNC/9040618355b4b54221bcbe449aa3e31f)

**Comment by mvantellingen** [comment]
So it seems lxml (better yet libxml2) throws an error when parsing the xml:

```console
$ xmllint broken.xml 
broken.xml:3: namespace error : xmlns:xsdLocal0: 'http://www.siebel.com/xml/Service Request Interface' is not a valid URI
 xmlns:xsdLocal0="http://www.siebel.com/xml/Service Request Interface"
```

Maybe this can be fixed by using a recoverer parser or something, need to look into it :)

**Comment by mvantellingen** [comment]
This should now work with the strict mode setting, see http://docs.python-zeep.org/en/master/client.html#strict-mode 

So use ``Client(wsdl, strict=False)``
