### ISSUE TITLE
Unable to parse "unbounded" elements

### ISSUE THREAD

**Issue by stavdav** [mvantellingen/python-zeep#286]
I am new to SOAP clients but have found your module pretty straightforward to work with. I've tried to solve my issue before posting.

I'll try and give you as much information as possible. I'm trying to work with Betdaq wsdl API:
[http://api.betdaq.com/v2.0/API.wsdl](url)

When running services that return unbounded sequences, I get an error when it tries to parse the response:

The Error:
`Traceback (most recent call last):
  File "E:\Projects\Programming\LiClipse\Betdaq\main.py", line 111, in <module>
    print(bd.ListSelectionsChangedSince(209475502))
  File "E:\Projects\Programming\LiClipse\Betdaq\main.py", line 64, in ListSelectionsChangedSince
    return self.readOnly.service.ListSelectionsChangedSince(listSelectionsChangedSinceRequest = marketId, _soapheaders = {'ExternalApiHeader' : self.header})
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\bindings\soap.py", line 113, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\bindings\soap.py", line 151, in process_reply
    return operation.process_reply(doc)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\bindings\soap.py", line 313, in process_reply
    return self.output.deserialize(envelope)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\messages\soap.py", line 75, in deserialize
    body_result = self._deserialize_body(body)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\messages\soap.py", line 364, in _deserialize_body
    result = self.body.parse(xmlelement, self.wsdl.types)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\xsd\elements.py", line 275, in parse
    xmlelement, schema, allow_none=allow_none, context=context)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\xsd\types.py", line 312, in parse_xmlelement
    elements, schema, name, context=context)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\xsd\indicators.py", line 464, in parse_xmlelements
    xmlelements, schema, name, context=context)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\xsd\elements.py", line 308, in parse_xmlelements
    xmlelement, schema, allow_none=True, context=context)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\xsd\elements.py", line 275, in parse
    xmlelement, schema, allow_none=allow_none, context=context)
  File "C:\Users\Ross\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\xsd\types.py", line 321, in parse_xmlelement
    raise XMLParseError("Unexpected element %r" % elements[0].tag)
zeep.exceptions.XMLParseError: Unexpected element '{http://www.GlobalBettingExchange.com/ExternalAPI/}Selections'`

The logger says the response XML is:

`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<soap:Body>
		<ListSelectionsChangedSinceResponse xmlns="http://www.GlobalBettingExchange.com/ExternalAPI/">
			<ListSelectionsChangedSinceResult>
				<ReturnStatus Code="0" Description="Success" CallId="5c81dca8-822d-43a5-9575-3f6cce5dc9b2" />
				<Timestamp>2016-12-20T19:39:45.1572110+00:00</Timestamp>
				<Selections Id="54826454" Name="6 Dew Hank" DisplayOrder="1" IsHidden="false" Status="8" ResetCount="0" WithdrawalFactor="0.00" MarketId="8697676" SelectionSequenceNumber="209475563" CancelOrdersTime="2016-12-19T22:00:58.4470000+00:00">
					<SettlementInformation SettledTime="2016-12-19T22:00:58.6300000+00:00" VoidPercentage="0.00" LeftSideFactor="0.00" RightSideFactor="100.00" SettlementResultString="Lose " />
				</Selections>
				<Selections Id="54826455" Name="3 Hello Mate" DisplayOrder="2" IsHidden="false" Status="8" ResetCount="0" WithdrawalFactor="0.00" MarketId="8697676" SelectionSequenceNumber="209475564" CancelOrdersTime="2016-12-19T22:00:58.4470000+00:00">
					<SettlementInformation SettledTime="2016-12-19T22:00:58.6300000+00:00" VoidPercentage="0.00" LeftSideFactor="0.00" RightSideFactor="100.00" SettlementResultString="Lose " />
				</Selections>
				<Selections Id="54826456" Name="4 Sheldon Storm" DisplayOrder="3" IsHidden="false" Status="8" ResetCount="0" WithdrawalFactor="0.00" MarketId="8697676" SelectionSequenceNumber="209475565" CancelOrdersTime="2016-12-19T22:00:58.4470000+00:00">
					<SettlementInformation SettledTime="2016-12-19T22:00:58.6300000+00:00" VoidPercentage="0.00" LeftSideFactor="0.00" RightSideFactor="100.00" SettlementResultString="Lose " />
				</Selections>
				<Selections Id="54826702" Name="10 Jammy Dodger" DisplayOrder="10" IsHidden="false" Status="8" ResetCount="0" WithdrawalFactor="0.00" MarketId="8697697" SelectionSequenceNumber="209477757" CancelOrdersTime="2016-12-19T23:03:57.7170000+00:00">
					<SettlementInformation SettledTime="2016-12-19T23:03:57.9300000+00:00" VoidPercentage="0.00" LeftSideFactor="0.00" RightSideFactor="100.00" SettlementResultString="Lose " />
				</Selections>
			</ListSelectionsChangedSinceResult>
		</ListSelectionsChangedSinceResponse>
	</soap:Body>
</soap:Envelope>`

I added some print commands to see what elements where being passed in the types.py:

`
            print (elements)
            print (self.elements_nested)
            for name, element in self.elements_nested:
                try:                    
                    result = element.parse_xmlelements(
                        elements, schema, name, context=context)
                    
                    if result:
                        init_kwargs.update(result)
                except UnexpectedElementError as exc:
                    raise XMLParseError(exc.message)

            Check if all children are consumed (parsed)
            if elements:                
                raise XMLParseError("Unexpected element %r" % elements[0].tag)
`

elements:
`deque([<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}ListSelectionsChangedSinceResult at 0x2267b558048>])
deque([<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}ReturnStatus at 0x2267b558088>, 
	<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}Timestamp at 0x2267b5580c8>, 
	<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}Selections at 0x2267b558148>, 
	<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}Selections at 0x2267b5581c8>, 
	<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}Selections at 0x2267b558208>, 
	<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}Selections at 0x2267b558248>)
deque([])
deque([<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}SettlementInformation at 0x2267b558088>])
deque([])`

self.elements_nested:
`[('_value_1', <Sequence([<Element(name='ListSelectionsChangedSinceResult', type=<zeep.xsd.dynamic_types.ListSelectionsChangedSinceResponse object at 0x000001F549583208>)>])>)]
[('_value_1', <Sequence([<Element(name='ReturnStatus', type=<zeep.xsd.dynamic_types.ReturnStatus object at 0x000001F548CA36A0>)>, <Element(name='Timestamp', type=<zeep.xsd.builtins.DateTime object at 0x000001F548D30AC8>)>, <Element(name='Selections', type=<zeep.xsd.dynamic_types.ListSelectionsChangedSinceResponseItem object at 0x000001F548CA3AC8>)>])>)]
[]
[('_value_1', <Sequence([<Element(name='SettlementInformation', type=<zeep.xsd.dynamic_types.SettlementInformationType object at 0x000001F548CA3F98>)>])>)]
[]`

There does seem to be an issue with sequences of elements.

**Comment by aquasync** [comment]
I'm hitting the same issue, did you end up finding a solution to this?

**Comment by stavdav** [comment]
I remember the issue and I did get round it somehow. I know which repo I used it for. I'll look into it tomorrow (just got my phone at the moment).

**Comment by aquasync** [comment]
Did you manage to find the code by chance? It seems that suds works with it as-is, but would rather use zeep if at all possible.

**Comment by stavdav** [comment]
I looked at the project I used it on. I added it to Bitbucket about 6 weeks after I posted this question so I think I must have solved it before the initial commit. Below is the script that used zeep, hope there's something that works for you. I remember posting the issue, I don't remember what solved it.

```
"""
Betdaq API Client - 2016-7

Version: 1.2

Connects to Betdaq WSDL API. Returning responses for ran requests

PEP 8 naming is ignored so the functions match the API.

"""

import zeep
import logging
from logging.config import fileConfig
from requests.exceptions import ConnectionError

fileConfig('logging_file.ini', disable_existing_loggers=False)

# API settings
wsdl = "http://api.betdaq.com/v2.0/API.wsdl"
username = "xxxxx"
password = "xxxxx"
languageCode = "en"
version = 2
currency = "GBP"
# Decimal (1), Fractional (2) or American (3)
PriceFormat = 1
minimum_balance = 210
stake = 2.00
second_odds = 4.3

class Betdaq:
    def __init__(self):
        """ Initialise zeep connection to Betdaq API services"""
        self.readOnly = zeep.Client(wsdl=wsdl, service_name="ReadOnlyService", strict=False)
        self.secure = zeep.Client(wsdl=wsdl, service_name="SecureService", strict=False)
        self.factory = self.readOnly.type_factory('ns0')
        self.header = self.factory.ExternalApiHeader(version=version,
                                                     languageCode=languageCode,
                                                     username=username,
                                                     password=password)
        print("Betdaq client initialised")

    #---Basic setup: query - response. If error log a generic API connection issue---#
    # Read Only Services
    def GetCurrentSelectionSequenceNumber(self):
        try:
            response = self.readOnly.service.GetCurrentSelectionSequenceNumber(_soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def GetEventSubTreeNoSelections(self, EventClassifierIds):
        try:
            request = self.factory.GetEventSubTreeNoSelectionsRequest(_value_1={'EventClassifierIds': EventClassifierIds})
            response = self.readOnly.service.GetEventSubTreeNoSelections(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except Exception as e:
            logging.info("%s" % e)
            return False

    def GetEventSubTreeWithSelections(self, EventClassifierIds):
        try:
            request = self.factory.GetEventSubTreeWithSelectionsRequest(_value_1={'EventClassifierIds': EventClassifierIds})
            response = self.readOnly.service.GetEventSubTreeWithSelections(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except Exception as e:
            logging.info("%s" % e)
            return False

    def GetMarketInformation(self, MarketIds):
        try:
            request = self.factory.GetMarketInformationRequest(_value_1={'MarketIds': MarketIds})
            response =  self.readOnly.service.GetMarketInformation(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
        
    # OK but For and Against only works for 1
    def GetPrices(self, marketId, ThresholdAmount=stake, NumberForPricesRequired=1, NumberAgainstPricesRequired=1):
        try:
            request = self.factory.GetPricesRequest(_value_1={'MarketIds': marketId},
                                                            ThresholdAmount=ThresholdAmount,
                                                            NumberForPricesRequired=NumberForPricesRequired,
                                                            NumberAgainstPricesRequired=NumberAgainstPricesRequired)
            response = self.readOnly.service.GetPrices(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    # OK when None returned not checked other than that
    def ListMarketWithdrawalHistory(self, MarketId):
        try:
            request = self.factory.ListMarketWithdrawalHistoryRequest(_value_1={'MarketId': MarketId})
            response = self.readOnly.service.ListMarketWithdrawalHistory(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
               
    def ListSelectionsChangedSince(self, SelectionSequenceNumber):
        if not type(SelectionSequenceNumber) == int:
            logging.info("Sequence Number not integer")
            return False
        try:
            request = self.factory.listSelectionsChangedSinceRequest(SelectionSequenceNumber=SelectionSequenceNumber)
            response = self.readOnly.service.ListSelectionsChangedSince(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
        
    # Fail - can't parse multiple events
    def ListTopLevelEvents(self):
        try:
            request = self.factory.ListTopLevelEventsRequest()
            response = self.readOnly.service.ListTopLevelEvents(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
        
    # Secure Services
    # Cancel Orders
    def CancelAllOrders(self):
        try:
            response = self.secure.service.CancelAllOrders( _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def CancelAllOrdersOnMarket(self, MarketIds):
        try:
            request = self.factory.CancelAllOrdersOnMarketRequest(_value_1={'MarketIds': MarketIds})
            response = self.secure.service.CancelAllOrdersOnMarket(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def CancelOrders(self, OrderHandle):
        try:
            request = self.factory.CancelOrdersRequest(OrderHandle=OrderHandle)
            response = self.secure.service.CancelOrders(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def ChangePassword(self, Password):
        try:
            request = self.factory.ChangePasswordRequest(Password)
            response = self.secure.service.ChangePassword(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
    
    # Heartbeat Stuff
    def RegisterHeartbeat(self, ThresholdMs=6000, HeartbeatAction=1):
        try:
            request = self.factory.RegisterHeartbeatRequest(ThresholdMs, HeartbeatAction)
            response = self.secure.service.RegisterHeartbeat(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def ChangeHeartbeatRegistration(self, ThresholdMs= 6000, HeartbeatAction= 1):
        try:
            request = self.factory.ChangeHeartbeatRegistrationRequest(ThresholdMs, HeartbeatAction)
            response = self.secure.service.ChangeHeartbeatRegistration(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def DeregisterHeartbeat(self):
        try:
            response = self.secure.service.DeregisterHeartbeat(_soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
    

    def GetAccountBalances(self):
        try:
            request = self.factory.GetAccountBalancesRequest()
            response = self.secure.service.GetAccountBalances(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False

    def GetOrderDetails(self, OrderId):
        try:
            request = self.factory.GetOrderDetailsRequest(OrderId)
            response = self.secure.service.GetOrderDetails(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except Exception as e:
            logging.info("%s" % e)
            return False

    def ListAccountPostings(self, StartTime, EndTime):
        try:
            request = self.factory.ListAccountPostingsRequest(StartTime, EndTime)
            response = self.secure.service.ListAccountPostings(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
        
    # OK but never returned anything
    def ListBlacklistInformation(self):
        try:
            response = self.secure.service.ListBlacklistInformation(_soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
        
    # OK but nothing returned yet
    def ListBootstrapOrders(self, SequenceNumber):
        try:
            request = self.factory.ListBootstrapOrdersRequest(SequenceNumber)
            response = self.secure.service.ListBootstrapOrders(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
    # OK but nothing returned yet
    def ListOrdersChangedSince(self, SequenceNumber):
        try:
            request = self.factory.ListOrdersChangedSinceRequest(SequenceNumber)
            response = self.secure.service.ListOrdersChangedSince(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("API connection issue")
            return False
        
    # OK
    def PlaceOrdersNoReceipt(self, SelectionId, Stake, Price, ExpectedWithdrawalSequenceNumber, Polarity=2, ExpectedSelectionResetCount=1):
        try:
            order = self.factory.SimpleOrderRequest(SelectionId=SelectionId,
                                                    Stake=Stake,
                                                    Price=Price,
                                                    Polarity=Polarity,
                                                    ExpectedSelectionResetCount=ExpectedSelectionResetCount,
                                                    ExpectedWithdrawalSequenceNumber=ExpectedWithdrawalSequenceNumber)
            request = self.factory.PlaceOrdersNoReceiptRequest(Orders= {'Order' : order}, WantAllOrNothingBehaviour= False)
            response = self.secure.service.PlaceOrdersNoReceipt(request, _soapheaders={'ExternalApiHeader' : self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("No API connection issue")
            return False
    
    def PlaceOrdersWithReceipt(self, SelectionId, Stake, Price, Polarity=2, ExpectedSelectionResetCount=1):
        try:
            order = self.factory.Order(SelectionId= SelectionId,
                                       Stake= Stake,
                                       Price= Price,
                                       Polarity= Polarity,
                                       ExpectedSelectionResetCount= ExpectedSelectionResetCount,
                                       ExpectedWithdrawalSequenceNumber= True)
            request = self.factory.PlaceOrdersWithReceiptRequest(order)
            response = self.secure.service.PlaceOrdersWithReceipt(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("No API connection issue")
            return False
        
    # OK
    def Pulse(self):
        try:
            return self.secure.service.Pulse(_soapheaders= {'ExternalApiHeader' : self.header})
        except ConnectionError:
            logging.info("No API connection issue")
            return False
    
    def UpdateOrdersNoReceipt(self, BetId, DeltaStake, Price, ExpectedSelectionResetCount, ExpectedWithdrawlSequenceNumber):
        try:
            request = self.factory.UpdateOrdersNoReceiptRequest(BetId=BetId,
                                                                DeltaStake=DeltaStake,
                                                                Price=Price,
                                                                ExpectedSelectionResetCount=ExpectedSelectionResetCount,
                                                                ExpectedWithdrawlSequenceNumber=ExpectedWithdrawlSequenceNumber)
            response = self.secure.service.UpdateOrdersNoReceipt(request, _soapheaders={'ExternalApiHeader': self.header})
            return self.CheckResponse(response)
        except ConnectionError:
            logging.info("No API connection issue")
            return False
    
    # Non Service
    def CheckResponse(self, response):
        """
        Check return status
        """
        code = response['ReturnStatus']['Code']
        # Success
        if code == 0:
            return response

        ### Cover all return false ###
        # Failure
        logging.info(response['ReturnStatus']['Description'])
        
        # ResourceError
        if code == 1:            
            return False
            
        # SystemError
        elif code == 2:            
            return False
            
        # InvalidPassword
        elif code == 405:            
            return False
            
        # PunterIsBlacklisted
        elif code == 406:            
            return False
            
        # PunterNotAuthorisedForAPI
        elif code == 533:            
            return False
        
        # EventClassifierDoesNotExist
        elif code == 5:
            return False
        
    def MarketStatus(self, code):
        if not code:
            logging.info("Market Finished")
            return False
        if type(code) != int:
            logging.info("Market Status not Integer")
            return False
        if code == 1:
            logging.info("Market Inactive")
            # The Market is not active and has never had any Orders issued against it.
            return True
        elif code == 2:
            logging.info("Market Active")
            # The Market it active (that is, Orders can be issued against it).
            return True
        elif code == 3:
            logging.info("Market Suspended")
            # The Market is not currently active but it has not yet been completed.
            return False
        elif code == 4:
            logging.info("Market Completed")
            # The Market is completed. No further Orders can be issued against the Market but the result of the Market is either not yet known or has not yet been entered.
            return False
        elif code == 6:
            logging.info("Market Settled")
            # The Market has been fully settled.
            return False
        elif code == 7:
            logging.info("Market Voided")
            # The Market has been voided. All matched Orders in this Market have also been voided.
            return False

    def OrderStatus(self, response):
        code = response
        if code == 1:
            # Unmatched (1)
            # The order is active and has some amount available for matching (the order may be partially matched).
            pass
        elif code == 2:
            # Matched (2)
            # The order has not been settled and it does not have any unmatched amount. 
            # Either the order was fully matched or it was partially matched and then cancelled.
            pass
        elif code == 3:
            # Cancelled (3)
            # This order has been cancelled and at least some of the order was unmatched at the time of expiration..
            return False
        elif code == 4:
            # Settled (4)
            # The order has been settled.
            pass
        elif code == 5:
            # Void (5)
            # The order has been voided.
            return False
        elif code == 6:
            # Suspended (6)
            # At least some of this order is unmatched but the order is suspended and is not available for matching..
            pass
        
    def PostingCategory(self, response):
        code = response
        if code == 1:
            # Settlement (1)
            # This posting resulted from the settlement, unsettlement or resettlement of a specific order.
            pass
        elif code == 2:
            # Commission (2)
            # This posting resulting from the charging of commission on market settlement, unsettlement or resettlement.
            pass
        elif code == 3:
            # Other (3)
            # This posting resulted from any other cause (for example, a lodgement or withdrawal).
            pass

    def SelectionStatus(self, response):
        code = response
        if code == 1:
            # Inactive (1)
            # The Selection is not active and has never had any Orders issued against it.
            pass
        elif code == 2:
            # Active (2)
            # The Selection is active (that is, Orders can be issued against it).
            pass
        elif code == 3:
            # Suspended (3)
            # Orders can not currently be placed on this Selection.
            pass
        elif code == 4:
            # Withdrawn (4)
            # The Entrant explicitly referenced by the Selection has withdrawn 
            # from the Event and so Orders can no longer be placed on this Selection.
            pass
        elif code == 9:
            # BallotedOut (9)
            # The Entrant explicitly referenced by the Selection has been balloted-out.
            pass
        elif code == 5:
            # Voided (5)
            # Orders can no longer be placed on this Selection and Orders previously placed for or against the Selection have been voided.
            pass
        elif code == 6:
            # Completed (6)
            # The Selection is completed. No further Orders can be issued against the Selection but the result of the Selection 
            # is either not yet known or has not yet been entered.
            pass
        elif code == 8:
            # Settled (8)
            # This Selection has already been settled. Individual selections can be settled in advance of other selections
            # in the market being settled (early settlement).
            pass
        
    def OrderResponse(self, response):
        code = response
        if code == 11:
            logging.info("SelectionDoesNotExist")
            pass
        elif code == 15:
            logging.info("MarketNotActive")
            pass
        elif code == 17:
            logging.info("SelectionNotActive")
            pass
        elif code == 22:
            logging.info("NoUnmatchedAmount")
            pass
        elif code == 25:
            logging.info("PunterReservationPerMarketExceeded")
            pass
        elif code == 114:
            logging.info("ResetHasOccurred")
            pass
        elif code == 128:
            logging.info("TradingCurrentlySuspended")
            pass
        elif code == 131:
            logging.info("InvalidOdds")
            pass
        elif code == 136:
            logging.info("WithdrawalSequenceNumberIsInvalid")
            pass
        elif code == 137:
            logging.info("MaximumInputRecordsExceeded")
            pass
        elif code == 208:
            logging.info("PunterSuspended")
            pass
        elif code == 240:
            logging.info("PunterProhibitedFromPlacingOrders")
            pass
        elif code == 241:
            logging.info("InsufficientPunterFunds")
            pass
        elif code == 271:
            logging.info("OrderAPIInProgress")
            pass
        elif code == 302:
            logging.info("PunterIsSuspendedFromTrading")
            pass
        elif code == 305:
            logging.info("ExpiryTimeInThePast")
            pass
        elif code == 406:
            logging.info("PunterIsBlacklisted")
            pass
        elif code == 597:
            logging.info("MarketIsForRealMoney")
            pass
        elif code == 598:
            logging.info("MarketIsForPlayMoney")
            pass
        
    def OrderAction(self, response):
        code = response        
        if code == 1:
            logging.info("Placed")
            pass
        elif code == 2:
            logging.info("ExplicitlyUpdated")
            pass
        elif code == 3:
            logging.info("Matched")
            pass
        elif code == 4:
            logging.info("CancelledExplicitly")
            pass
        elif code == 5:
            logging.info("CancelledByReset ")
            pass
        elif code == 6:
            logging.info("CancelledOnInRunning")
            pass
        elif code == 7:
            logging.info("Expired")
            pass
        elif code == 8:
            logging.info("MatchedPortionRepricedByR4")
            pass
        elif code == 9:
            logging.info("UnmatchedPortionRepricedByR4")
            pass
        elif code == 10:
            logging.info("UnmatchedPortionCancelledByWithdrawal")
            pass
        elif code == 11:
            logging.info("Voided")
            pass
        elif code == 12:
            logging.info("Settled")
            pass
        elif code == 13:
            logging.info("Suspended")
            pass
        elif code == 14:
            logging.info("Unsuspended")
            pass
        elif code == 15:
            logging.info("ExpiredByMatching")
            pass
        elif code == 16:
            logging.info("Unsettled")
            pass
        elif code == 17:
            logging.info("Unmatched")
            pass
        elif code == 18:
            logging.info("MatchedPortionRepriced")
            pass
        elif code == 19:
            logging.info("CreatedFromLightweightPrice")
            pass
        elif code == 20:
            logging.info("CancelledOnComplete")
            pass
    
if __name__ == "__main__":
    bd = Betdaq()
    print(bd.GetAccountBalances())
```

**Comment by aquasync** [comment]
Thanks for digging that up! Reminds me of [this xkcd](https://xkcd.com/979/)... The only mods I made were for zeep changes, namely using settings=zeep.Settings(strict=False) in the client constructors.

Getting account balance as in your script worked fine, however it still borks ListTopLevelEvents - returning just the one:

```
Betdaq client initialised
{
    'ReturnStatus': {
        'Code': 0,
        'Description': 'Success',
        'CallId': 'ceeeff90-8d44-4da2-a567-f1a920138e4b',
        'ExtraInformation': None
    },
    'Timestamp': datetime.datetime(2021, 12, 1, 10, 4, 20, 70640, tzinfo=<FixedOffset '+00:00'>),
    'EventClassifiers': {
        'EventClassifiers': [],
        'Markets': [],
        'Id': 100004,
        'Name': 'Horse Racing',
        'DisplayOrder': 1,
        'IsEnabledForMultiples': True,
        'ParentId': 1
    },
    '_raw_elements': deque([<Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8c00>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8c40>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8c80>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8cc0>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8d00>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8d40>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8d80>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8dc0>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8e00>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8e40>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8e80>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8ec0>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8f00>, <Element {http://www.GlobalBettingExchange.com/ExternalAPI/}EventClassifiers at 0x7f4acb0d8f40>])
}
```

Somehow setting strict to False bypasses whatever that exception, but in the process loses the ability to handle sequences properly. Anyway appreciate your effort digging this up! More just documenting this for the next traveller to this bug report...

**Comment by stavdav** [comment]
I noticed the strict=False in repo history but I just thought posting the code would be better.

I probably did something stupid like mod the zeep that was on the computer (it was 5 years ago, I'm better now).

**Comment by aquasync** [comment]
Haha yeah I started down that path, but ended up going a different way - I've managed to hack the wsdl into something that zeep accepts in strict mode. The issue seems to be with the handling of occurs for extensions of sequence types (and everything in this extends from the base response type) - the below just directly inlines base response and that seems to work around the issue for me.

```
import lxml.etree
import copy

wsdl = lxml.etree.fromstring(open('API.wsdl', 'rt').read())
ns = {'xs': 'http://www.w3.org/2001/XMLSchema'}
# manually inline the abstract baseresponse type into all the extensions...
base = wsdl.xpath('//xs:complexType[@name="BaseResponse"]', namespaces=ns)[0]
exts = wsdl.xpath('//xs:extension[@base="BaseResponse"]', namespaces=ns)
for ext in exts:
    ext.tag = '{http://www.w3.org/2001/XMLSchema}complexType'
    del ext.attrib['base']
    for i, child in enumerate(base.iterchildren()):
        ext.insert(i, copy.deepcopy(child))
    # combine elements...
    children = list(ext.iterchildren())
    if len(children) >= 2 and children[0].tag == children[1].tag and children[0].tag == '{http://www.w3.org/2001/XMLSchema}sequence':
        for child in children[1].iterchildren():
            # propagate minOccurs/maxOccurs
            child.attrib.update(children[1].attrib)
            children[0].append(child)
        ext.remove(children[1])
    # move into parent
    assert ext.getparent().tag == '{http://www.w3.org/2001/XMLSchema}complexContent'
    assert len(list(ext.getparent().iterchildren())) == 1
    assert ext.getparent().getparent().tag == '{http://www.w3.org/2001/XMLSchema}complexType'
    parent = ext.getparent().getparent()
    parent.remove(ext.getparent())
    for child in ext.iterchildren():
        parent.append(child)

with open('APIx.wsdl', 'wb') as f:
    f.write(lxml.etree.tostring(wsdl))
```
