### ISSUE TITLE
NotImplementedError: schemaLocation is required

### ISSUE THREAD

**Issue by eriktelepovsky** [mvantellingen/python-zeep#30]
I can't get rid of the error using following command:

`python -mzeep https://online.gls-czech.com/webservices/soap_server.php?wsdl` 

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File ".../lib/python2.7/site-packages/zeep/__main__.py", line 73, in <module>
    main(args)
  File ".../lib/python2.7/site-packages/zeep/__main__.py", line 62, in main
    client = Client(args.wsdl_file, transport=transport)
  File ".../lib/python2.7/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = WSDL(wsdl, self.transport)
  File ".../lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 34, in __init__
    root_definitions = Definitions(self, document, self.location)
  File ".../lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 106, in __init__
    self.schema = self.parse_types(doc)
  File ".../lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 229, in parse_types
    self.wsdl._parser_context, self.location)
  File ".../lib/python2.7/site-packages/zeep/xsd/schema.py", line 46, in __init__
    visitor.visit_schema(node)
  File ".../lib/python2.7/site-packages/zeep/xsd/visitor.py", line 82, in visit_schema
    self.process(node, parent=parent)
  File ".../lib/python2.7/site-packages/zeep/xsd/visitor.py", line 40, in process
    result = visit_func(self, node, parent)
  File ".../lib/python2.7/site-packages/zeep/xsd/visitor.py", line 95, in visit_import
    raise NotImplementedError("schemaLocation is required")
NotImplementedError: schemaLocation is required
```

Any ideas?

Thank you.

**Comment by mvantellingen** [comment]
Thanks for the detailed report, I've fixed a number of issues so that the wsdl is parsed correctly.

Can you give the master branch a new try?
