### ISSUE TITLE
Int[] in request would cause an error

### ISSUE THREAD

**Issue by dshingarev** [mvantellingen/python-zeep#300]
I'm on 0.24.0 and having some issues with sending array of integers to service.
I made a dirty fix that solves the problem for me for now but obviously is not good enough, as I don't have enough knowledge of that part of the library: https://github.com/dshingarev/python-zeep/tree/array-of-int-fix. 

Error Message:
Traceback (most recent call last):
......
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/wsdl/bindings/soap.py", line 107, in send
    options=options)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/wsdl/bindings/soap.py", line 65, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/wsdl/definitions.py", line 165, in create
    return self.input.serialize(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/wsdl/messages/soap.py", line 48, in serialize
    self.body.render(body, body_value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/elements.py", line 336, in render
    self._render_value_item(parent, value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/elements.py", line 354, in _render_value_item
    return self.type.render(node, value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/types.py", line 356, in render
    element.render(parent, element_value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/indicators.py", line 182, in render
    element.render(parent, element_value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/elements.py", line 336, in render
    self._render_value_item(parent, value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/elements.py", line 354, in _render_value_item
    return self.type.render(node, value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/types.py", line 356, in render
    element.render(parent, element_value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/indicators.py", line 182, in render
    element.render(parent, element_value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/elements.py", line 336, in render
    self._render_value_item(parent, value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/elements.py", line 354, in _render_value_item
    return self.type.render(node, value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/types.py", line 356, in render
    element.render(parent, element_value)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zeep/xsd/indicators.py", line 175, in render
    if name in value:
TypeError: argument of type 'int' is not iterable

All i'm doing to get that is to use array of Int in request's (calc_data):
{
....
"Terms": [24, 36, 48, 72],
....
}

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by mvantellingen** [comment]
I'm closing this issue for now. If in new releases this is still a problem then please let me know so that I can re-open it.

Thanks again for taking the time to report the issue
