### ISSUE TITLE
AttributeError: 'RefGroup' object has no attribute 'attr_name'

### ISSUE THREAD

**Issue by bryntruscott** [mvantellingen/python-zeep#319]
Thanks for all your work on this library, which is working really well for me. I hope you might be able to help with this issue:

1. The version of zeep (or if you are running master the commit hash/date)
zeep 0.25.0

2. The WSDL you are using
https://aeradminapi.aeris.com/AerAdmin_WS_5_0/ws?wsdl

3. An example script
https://gist.github.com/bryntruscott/d3a7451bc85c6339a329c8784cb18a33

I am seeing the following exception during the call to getDeviceDetail() in the script. Appears to be during the request send phase, so the faked argument values I have used here aren't the problem (it does the same with the real values)

  WARNING:zeep.wsdl.bindings.soap:Forcing soap:address location to HTTPS
  Traceback (most recent call last):
    File "test_aeris_wsdl.py", line 23, in <module>
      deviceID={'imsi': IMSI})
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/client.py", line 41, in __call__
      self._op_name, args, kwargs)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 107, in send
    options=options)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 65, in _create
      serialized = operation_obj.create(*args, **kwargs)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 165, in create
      return self.input.serialize(*args, **kwargs)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/wsdl/messages/soap.py", line 46, in serialize
      body_value = self.body(*args, **kwargs)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 45, in __call__
      instance = self.type(*args, **kwargs)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/xsd/types/complex.py", line 40, in __call__
      return self._value_class(*args, **kwargs)
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/xsd/valueobjects.py", line 43, in __init__
      elm_values = container.default_value
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/cached_property.py", line 53, in __get__
      return obj_dict.setdefault(name, self.func(obj))
  File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/xsd/elements/indicators.py", line 26, in default_value
    (name, element.default_value) for name, element in self.elements
  File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/cached_property.py", line 53, in __get__
    return obj_dict.setdefault(name, self.func(obj))
  File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/xsd/elements/indicators.py", line 53, in elements
    for name, elm in self.elements_nested:
    File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/cached_property.py", line 53, in __get__
      return obj_dict.setdefault(name, self.func(obj))
  File "/Users/bryn/Develop/BBOXX/SMART-Network-Adapters/venv-network-adapters/lib/python2.7/site-packages/zeep/xsd/elements/indicators.py", line 78, in elements_nested
      name = generator_2.create_name(elm.attr_name)
  AttributeError: 'RefGroup' object has no attribute 'attr_name'

**Comment by mvantellingen** [comment]
Should be fixed, thanks

**Comment by bryntruscott** [comment]
Works fine now. Thanks a lot!
