### ISSUE TITLE
Type Error exception

### ISSUE THREAD

**Issue by PavelGrOr** [mvantellingen/python-zeep#340]
I catch type error exception when I try to connect to WSDL with Zeep 1.0.0. I get:

```
Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\zeep\parser.py", line 14, in parse_xml
    return fromstring(content, parser=parser, base_url=base_url)
  File "c:\Python34\lib\site-packages\defusedxml\lxml.py", line 140, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src\lxml\lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src\lxml\lxml.etree.c:76696)
  File "src\lxml\parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:115101)
  File "src\lxml\parser.pxi", line 1711, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:113677)
  File "src\lxml\parser.pxi", line 1051, in lxml.etree._BaseParser._parseUnicodeDoc (src\lxml\lxml.etree.c:107847)
  File "src\lxml\parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:102150)
  File "src\lxml\parser.pxi", line 694, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:103800)
  File "src\lxml\parser.pxi", line 624, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:102712)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 3, column 9

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Python34\lib\site-packages\zeep\wsdl\bindings\soap.py", line 148, in process_reply
    doc = parse_xml(content)
  File "c:\Python34\lib\site-packages\zeep\parser.py", line 16, in parse_xml
    raise XMLSyntaxError("Invalid XML content received (%s)" % exc)
zeep.exceptions.XMLSyntaxError: Invalid XML content received (Start tag expected, '<' not found, line 3, column 9)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\cl.py", line 142, in <module>
    print(client())
  File "c:\cl.py", line 117, in client
    client, operation, response)
  File "c:\Python34\lib\site-packages\zeep\wsdl\bindings\soap.py", line 152, in process_reply
    % (response.status_code, response.content))
zeep.exceptions.TransportError: Server returned HTTP status 200 (
            <!-- The response from the server -->
        )
```
WSDL file: https://gist.github.com/PavelGrOr/a1987aee9a9351ee464a08a930eab6d7

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.
