### ISSUE TITLE
error while pushing data to server, requesting data works.

### ISSUE THREAD

**Issue by MG-developer1** [mvantellingen/python-zeep#342]
I would like to pick your brain about an issue I'm having.

Everything works fine when I request data out of the soap web service. However when I'm trying to create a new customer it gives me an error.

```Traceback (most recent call last):
File "script.py", line 112, in <module>
response = client.service.AddNewCustomer(customerData=customerData, clientContext=clientContext)
File "/usr/local/lib/python3.6/site-packages/zeep/client.py", line 41, in __call__
self._op_name, args, kwargs)
File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 113, in send
return self.process_reply(client, operation_obj, response)
File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 149, in process_reply
return self.process_error(doc, operation)
File "/usr/local/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 236, in process_error
detail=fault_node.find('detail'))
zeep.exceptions.Fault: Remote call failed: Code = (CBRWP006) Message = (Failure on message processing)
```

I think I have found the difference in the 2 type of requests. When requesting the details of a customer this is in the documentation:
Input wsdl:documentation, use = literal

For the function to create a customer this is described in the documentation:
Input soap:body, use = literal

Correct me if I'm wrong but that seems to be the difference between the 2 types of requests.

Versions: Python 3.6 & Zeep 0.25

Code:
```python
import zeep
from zeep.transports import Transport
from deep import Client

transport_auth = Transport(http_auth=(username, password))
client = Client(wsdl=wsdl, transport=transport_auth)

factory = client.type_factory('ns0')
customerData = factory.CustomerInsertData()
customerData.AddressData = factory.AddressDataType()
customerData.AddressData.AddressLine1 = "test street"
customerData.AddressData.City = "amazing city"
customerData.AddressData.CountryId = "NL"
customerData.AddressData.CountryIdType = "Internal"
customerData.AddressData.Nata = False
customerData.AddressData.ZipCode = "1000AA"

etc...

response = client.service.AddNewCustomer(customerData=customerData, clientContext=clientContext)

print(response.encode("utf-8"))
```

I've configured the logger and this is the input that it creates:

```xml
<soap-env:Body>
<ns0:AddNewCustomer xmlns:ns0="http://www.secret.nl/Retail/1.0">
  <ns0:customerData>
    <ns0:AddressData>
      <ns0:AddressLine1>test street</ns0:AddressLine1>
      <ns0:City>amazing city</ns0:City>
      <ns0:CountryId>NL</ns0:CountryId>
      <ns0:CountryIdType>Internal</ns0:CountryIdType>
      <ns0:Nata>false</ns0:Nata>
      <ns0:ZipCode>1000AA</ns0:ZipCode>
    </ns0:AddressData>
  </ns0:AddNewCustomer>
etc...
</soap-env:Body>
```
Sorry I can't share the WSDL file link because it's a private file. However here are the most important sections related to this one.

```console
Prefixes:
 xsd: http://www.w3.org/2001/XMLSchema
 ns0: http://www.secret.nl/Retail/1.0
 ns1: http://schemas.microsoft.com/2003/10/Serialization/
 ns2: http://www.secret.nl/fault
 ns3: http://schemas.microsoft.com/2003/10/Serialization/Arrays
Global elements:
 ns0:AddNewCustomer(customerData: {AddressData: AddressDataType, etc.., clientContext: clientContext)
Bindings:
 Soap11Binding: {http://www.secret.nl/Retail/1.0
Operations:
  AddNewCustomer(customerData: {AddressData: AddressDataType, etc.., clientContext: clientContext)
```

So my main question is how do I configure zeep in such a way that it will use soap:body in creating the request and push it.

If you've made it this far through my post, thank you!

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by MG-developer1** [comment]
Hi mvantellingen,

There was an issue in the configuration of the server on their side.

Thank you.
