### ISSUE TITLE
Support default QName for the empty string ""

### ISSUE THREAD

**Issue by nicholasli137** [mvantellingen/python-zeep#349]
# Environment

- Python 2.7.6
- zeep version 1.0.0
- wsdl: https://portal.bulkvs.com/api?wsdl
- the script used
```
wsdl = 'https://portal.bulkvs.com/api?wsdl'
client = zeep.Client(wsdl=wsdl)
```
- Error logs
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lucifer/PycharmProjects/cloudpbx/octopod/octopod/e911.py", line 8, in <module>
    client = zeep.Client(wsdl=wsdl)
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 120, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 65, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 157, in __init__
    self.messages = self.parse_messages(doc)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 288, in parse_messages
    msg = parse.parse_abstract_message(self, msg_node)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/parse.py", line 27, in parse_abstract_message
    part_type = qname_attr(part, 'type', tns)
  File "/usr/local/lib/python2.7/dist-packages/zeep/utils.py", line 10, in qname_attr
    return as_qname(value, node.nsmap, target_namespace)
  File "/usr/local/lib/python2.7/dist-packages/zeep/utils.py", line 20, in as_qname
    return etree.QName(namespace, local)
  File "lxml.etree.pyx", line 1735, in lxml.etree.QName.__init__ (src/lxml/lxml.etree.c:55168)
  File "apihelpers.pxi", line 1571, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:29187)
ValueError: Invalid tag name u''
```
# Possible reason for this issue
`BulkVS` WSDL api contains the following field
```xml
<message name="queryAccountResponse">
<part name="result" type="xsd:"/>
</message>
```
# Possible Solution
Update [utils.py](https://github.com/nicholasli137/python-zeep/blob/master/src/zeep/utils.py#L13)

**Comment by mvantellingen** [comment]
Added workaround in 1.1.0
