### ISSUE TITLE
'AnyType' object has no attribute '_attributes_unwrapped'

### ISSUE THREAD

**Issue by mandeepshetty** [mvantellingen/python-zeep#352]
I'm trying to consume ONVIF web services.

Zeep version: 1.0.0
Python 2.7.12

The wsdl from ONVIF is [here](https://www.onvif.org/ver10/network/wsdl/remotediscovery-102.wsdl).

I ran
`python -m zeep https://www.onvif.org/ver10/network/wsdl/remotediscovery-102.wsdl`

and the stack trace is : 

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/__main__.py", line 86, in <module>
    main(args)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/__main__.py", line 75, in main
    client = Client(args.wsdl_file, transport=transport)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/client.py", line 120, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 65, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 156, in __init__
    self.parse_types(doc)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 272, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 100, in add_documents
    document.resolve()
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 360, in resolve
    schema.resolve()
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 370, in resolve
    _resolve_dict(self._elements)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 364, in _resolve_dict
    new = obj.resolve()
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 220, in resolve
    self.resolve_type()
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/elements/element.py", line 217, in resolve_type
    self.type = self.type.resolve()
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/types/base.py", line 80, in resolve
    return retval.resolve()
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/types/complex.py", line 265, in resolve
    self._resolved = self.restrict(self._restriction)
  File "/home/mandeep/.local/lib/python2.7/site-packages/zeep/xsd/types/complex.py", line 338, in restrict
    chain(base._attributes_unwrapped, self._attributes_unwrapped))
AttributeError: 'AnyType' object has no attribute '_attributes_unwrapped'
`

EDIT: Sorry about the wrapped stack trace. I put the stack trace in the "code" markdown after copying it directly from bash. I'll fix it if you let me know how.

**Comment by mvantellingen** [comment]
Thanks, should be fixed master. could you give that a try?

**Comment by mvantellingen** [comment]
In 1.1.0

**Comment by mandeepshetty** [comment]
Thanks for the quick fix ! It works now.
