### ISSUE TITLE
zeep.exceptions.LookupError: No type 'Passport' in namespace urn:types.core_2016_2.platform.webservices.netsuite.com

### ISSUE THREAD

**Issue by olufusepump** [mvantellingen/python-zeep#365]
Hi, 

When trying to fetch an object by type with the get_type method using Zeep 1.1.0, I get an error (zeep.exceptions.LookupError: No type 'Passport' in namespace urn:types.core_2016_2.platform.webservices.netsuite.com). The full traceback is shown below. I have attached an archive containing the WSDL being used (it's Netsuite's which can also be found here https://webservices.netsuite.com/wsdl/v2016_2_0/netsuite.wsdl) as well as a sample script test.py to replicate the error [python-zeep-lookup-bug.zip](https://github.com/mvantellingen/python-zeep/files/804096/python-zeep-lookup-bug.zip). I notice that
 the fork at https://github.com/dolimoon6000/python-zeep doesn't seem to have the error. Could someone help with it? Thanks!

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    Passport = client.get_type('ns1:Passport')
  File "/home/oludolapo/.virtualenvs/python-zeep-lookup-bug/local/lib/python2.7/site-packages/zeep/client.py", line 226, in get_type
    return self.wsdl.types.get_type(name)
  File "/home/oludolapo/.virtualenvs/python-zeep-lookup-bug/local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 121, in get_type
    return self._get_instance(qname, 'get_type', 'type')
  File "/home/oludolapo/.virtualenvs/python-zeep-lookup-bug/local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 219, in _get_instance
    raise last_exception
zeep.exceptions.LookupError: No type 'Passport' in namespace urn:types.core_2016_2.platform.webservices.netsuite.com. Available types are: {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchDateFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}InitializeRefType, {urn:types.core_2016_2.platform.webservices.netsuite.com}GetSelectValueFilterOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchRecordType, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchLongFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}GetAllRecordType, {urn:types.core_2016_2.platform.webservices.netsuite.com}SignatureAlgorithm, {urn:types.core_2016_2.platform.webservices.netsuite.com}CalendarEventAttendeeResponse, {urn:types.core_2016_2.platform.webservices.netsuite.com}DeletedRecordType, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchMultiSelectFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchStringFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchEnumMultiSelectFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchDate, {urn:types.core_2016_2.platform.webservices.netsuite.com}RecordType, {urn:types.core_2016_2.platform.webservices.netsuite.com}DurationUnit, {urn:types.core_2016_2.platform.webservices.netsuite.com}GetCustomizationType, {urn:types.core_2016_2.platform.webservices.netsuite.com}AsyncStatusType, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchTextNumberFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}InitializeType, {urn:types.core_2016_2.platform.webservices.netsuite.com}SearchDoubleFieldOperator, {urn:types.core_2016_2.platform.webservices.netsuite.com}InitializeAuxRefType
```

**Comment by mvantellingen** [comment]
python -mzeep <wsdl> shows that you should use ns0 instead of ns1

**Comment by olufusepump** [comment]
You're correct. My mistake. Thanks a bunch!
