### ISSUE TITLE
Error when passing in soap headers

### ISSUE THREAD

**Issue by ekarlso** [mvantellingen/python-zeep#368]
version: 1.1
wsdl: http://ws-test.infotorg.no/xml/EVRY/InfotorgKjoeretoey/2013-10-07/InfotorgKjoeretoey.wsdl
Example:

```python
    headers = {"Brukersesjon": {
        "distribusjonskanal": "PTP",
        "systemnavn": "plato",
        "brukernavn": user,
        "passord": password
    }}
    client.service.hentTekniskeData("RK11132", _soapheaders=headers)
```

I then get an error: 
```
Traceback (most recent call last):
  File "it_test.py", line 4, in <module>
    infotorget.get_plate_info("RK11132")
  File "/home/ekarlso/projects/evry/plato/plato/plate_info/infotorget.py", line 30, in get_plate_info
    client.service.hentTekniskeData("RK11132", _soapheaders=headers)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 109, in send
    options=options)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 67, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 165, in create
    return self.input.serialize(*args, **kwargs)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 42, in serialize
    header = self._serialize_header(headers_value, nsmap)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 316, in _serialize_header
    elm.render(header, headers_value[name], ['header', name])
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 162, in render
    self._render_value_item(parent, value, render_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 180, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 195, in render
    element.render(parent, element_value, child_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 190, in render
    element.render(parent, element_value, child_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 566, in render
    self.child.render(parent, value, render_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 190, in render
    element.render(parent, element_value, child_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 566, in render
    self.child.render(parent, value, render_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 190, in render
    element.render(parent, element_value, child_path)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 391, in render
    result = self._find_element_to_render(item)
  File "/home/ekarlso/projects/evry/plato/.venv/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 435, in _find_element_to_render
    score = element.accept(choice_value)
AttributeError: 'Group' object has no attribute 'accept'
```

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by ekarlso** [comment]
WSDL = "http://ws-test.infotorg.no/xml/EVRY/InfotorgKjoeretoey/2013-10-07/InfotorgKjoeretoey.wsdl"
client = zeep.Client(WSDL)

header = {
    "Brukersesjon": {
        "brukernavn": user,
        "passord": password,
        "systemnavn": "plato",
        "distribusjonskanal": "PTP"
    }
}
client.service.hentTekniskeData("RK11132", _soapheaders=header)

**Comment by mvantellingen** [comment]
Can you give the master branch a try? (See b4b28a2a33918e7c1f2cc37a82f03937997f9f59)

**Comment by mvantellingen** [comment]
So this one can be closed? 🙄
