### ISSUE TITLE
Non-proper UTF8 response gives xml.etree.XMLSyntaxError

### ISSUE THREAD

**Issue by OrangGeeGee** [mvantellingen/python-zeep#397]
Versions: zeep-1.3.0, lxml-3.7.3

Seems when receiving not properly UTF8 encoded response, you get an error
```
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xF6 0x67 0x6C 0x69, line 1, column 26563
```

Here's an example gist which is a cut down version of [src/zeep/loader.py parse_xml function](https://github.com/mvantellingen/python-zeep/blob/master/src/zeep/loader.py#L21) that reproduces problem I am facing and a possible solution.
https://gist.github.com/OrangGeeGee/af501e0abcffc03562e681ee5755f063

The solution is taken from a similar issue https://github.com/KimiNewt/pyshark/issues/116.
My solution is ugly and feels dirty, so hopefully you have some better ideas how to make zeep compatible with such responses.

Oh those crazy old school SOAP services.. :)

Also pasting in the original traceback of the error with [this PR](https://github.com/mvantellingen/python-zeep/pull/396) applied.:
```
Traceback (most recent call last):
  File "C:\Users\anthony\sources\python-zeep\src\zeep\loader.py", line 44, in parse_xml
    return fromstring(content, parser=parser, base_url=base_url)
  File "C:\Users\anthony\AppData\Local\Programs\Python\Python36\lib\site-packages\defusedxml\lxml.py", line 143, in fromstring
    rootelement = _etree.fromstring(text, parser, base_url=base_url)
  File "src\lxml\lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src\lxml\lxml.etree.c:78994)
  File "src\lxml\parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:118325)
  File "src\lxml\parser.pxi", line 1736, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:117005)
  File "src\lxml\parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:111249)
  File "src\lxml\parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:105093)
  File "src\lxml\parser.pxi", line 706, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:106801)
  File "src\lxml\parser.pxi", line 635, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:105655)
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xF6 0x67 0x6C 0x69, line 1, column 26563

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\anthony\sources\python-zeep\src\zeep\wsdl\bindings\soap.py", line 148, in process_reply
    doc = parse_xml(content, self.transport)
  File "C:\Users\anthony\sources\python-zeep\src\zeep\loader.py", line 46, in parse_xml
    raise XMLSyntaxError("Invalid XML content received (%s)" % exc.msg)
zeep.exceptions.XMLSyntaxError: Invalid XML content received (Input is not proper UTF-8, indicate encoding !
Bytes: 0xF6 0x67 0x6C 0x69, line 1, column 26563)

Traceback (most recent call last):
<...>
  File "C:\Users\anthony\sources\python-zeep\src\zeep\client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "C:\Users\anthony\sources\python-zeep\src\zeep\wsdl\bindings\soap.py", line 115, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Users\anthony\sources\python-zeep\src\zeep\wsdl\bindings\soap.py", line 152, in process_reply
    % (response.status_code, response.content))
zeep.exceptions.TransportError: Server returned HTTP status 200 (b'<?xml version="1.0" encoding="UTF-8"?><...>')
```

**Comment by mvantellingen** [comment]
Thanks, are you able to provide an example script as described in the documentation? That would speed up the development on my end

**Comment by OrangGeeGee** [comment]
Issue solved by fixing SOAP API's responses to include proper UTF-8 characters.
Closing this one. Thanks for the great work on zeep!
