### ISSUE TITLE
Bad handshake Error

### ISSUE THREAD

**Issue by MaxOvcharov** [mvantellingen/python-zeep#398]
I try to create SOAP client
```
import os
from zeep import Client
from zeep.wsse.signature import Signature

key_filename = "/etc/ssl/certs/cert.key.pem"
cert_filename = "/etc/ssl/certs/cert.crt.pem"

client = Client('https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2?wsdl', wsse=Signature(key_filename, cert_filename))
```
And have this exception:
```
Traceback (most recent call last):
  File "/home/max/bot_project/Bots_Django/TelegramBot/bot/simple_soap_client.py", line 19, in <module>
    wsse=Signature(key_filename, cert_filename))
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/client.py", line 120, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 76, in __init__
    document = self._get_xml_document(location)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 137, in _get_xml_document
    location, self.transport, self.location, strict=self.strict)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/loader.py", line 66, in load_external
    content = transport.load(url)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/transports.py", line 111, in load
    content = self._load_remote_data(url)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/transports.py", line 126, in _load_remote_data
    response = self.session.get(url, timeout=self.load_timeout)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```
How can I fix this exception and what's wrong with my code?

**Comment by mvantellingen** [comment]
See http://docs.python-zeep.org/en/master/transport.html#transports (the verify option). If that doesn't solve it then perhaps the requests docs have more info. Basically zeep uses requests for the http communication with the server

**Comment by MaxOvcharov** [comment]
I also try something like this:
```
import os
from requests import Session
from zeep import Client
from zeep.transports import Transport
from zeep.wsse.signature import Signature

key_filename = "/etc/ssl/certs/cert.key.pem"
cert_filename = "/etc/ssl/certs/cert.crt.pem"

session = Session()
session.verify = False
transport = Transport(session=session)

client = Client('https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2?wsdl',
                       , transport=transport,  wsse=Signature(key_filename, cert_filename))
```
But it doesn't solved my problem

**Comment by marksteward** [comment]
The issue here is that although you can use create_service to create a proxy to a different address, this doesn't work if your WSDL is behind a generic web proxy and refers to other resources.

To make this work, you can override Transport (it's not documented, but the interface is pretty simple):

```
class ProxyTransport(Transport):
    def __init__(self, maps, **kwargs):
        self.maps = maps
        super(ProxyTransport, self).__init__(**kwargs)

    def map_url(self, url):
        for src, dest in self.maps.items():
            if url.startswith(src):
                return url.replace(src, dest)
        return url

    def get(self, address, params, headers):
        address = self.map_url(address)
        return super(ProxyTransport, self).get(address, params, headers)

    def post(self, address, message, headers):
        address = self.map_url(address)
        return super(ProxyTransport, self).post(address, message, headers)

    def post_xml(self, address, envelope, headers):
        address = self.map_url(address)
        return super(ProxyTransport, self).post_xml(address, envelope, headers)

    def load(self, url):
        url = self.map_url(url)
        return super(ProxyTransport, self).load(url)

...
tranport = ProxyTransport(maps={'https://unreachable.host.invalid/': 'https://37.230.149.6:10004/'})
client = Client('https://unreachable.host.invalid/service?WSDL', transport=transport)
```

(untested)
