### ISSUE TITLE
wsdl fails to import

### ISSUE THREAD

**Issue by froodster** [mvantellingen/python-zeep#40]
Far from a SOAP expert here, so all I can really do is post the fault!
but the following:
``` python
from zeep import Client`
wsdl='https://qa-api.ukmail.com/Services/UKMAuthenticationServices/UKMAuthenticationService.svc?wsdl'
client = zeep.Client(wsdl=wsdl)
```
fails with:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 45, in __init__
    self.wsdl = WSDL(wsdl, self.transport)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 35, in __init__
    root_definitions.resolve_imports()
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 138, in resolve_imports
    binding.resolve(self)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/definitions.py", line 164, in resolve
    self.port_type = definitions.port_types[self.port_name.text]
KeyError: u'{http://www.UKMail.com/Services/Contracts/ServiceContracts}IUKMAuthenticationService'
```
The wsdl file for this service is:
```xml
<?xml version="1.0" encoding="utf-8"?><wsdl:definitions name="UKMAuthenticationService" targetNamespace="http://www.UKMail.com/Services" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:tns="http://www.UKMail.com/Services" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:i0="http://tempuri.org/" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex"><wsdl:import namespace="http://tempuri.org/" location="https://qa-api.ukmail.com/Services/UKMAuthenticationServices/UKMAuthenticationService.svc?wsdl=wsdl1"/><wsdl:types/><wsdl:service name="UKMAuthenticationService"><wsdl:port name="BasicHttpEndpoint_IUKMAuthenticationService" binding="i0:BasicHttpEndpoint_IUKMAuthenticationService"><soap:address location="https://qa-api.ukmail.com/Services/UKMAuthenticationServices/UKMAuthenticationService.svc"/></wsdl:port></wsdl:service></wsdl:definitions>
```
Many thanks for your time

**Comment by mvantellingen** [comment]
Thanks for the good bugreport! I've just refactored the wsdl import resolving which should fix this. Could you give the master branch a try?

``pip install https://github.com/mvantellingen/python-zeep/archive/master.zip#egg=zeep``

**Comment by froodster** [comment]
Hi, thanks for the speedy response.

I'm getting the same fault with the dev 0.7 version I'm afraid!

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.virtualenvs/django/local/lib/python2.7/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/home/david/.virtualenvs/django/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 59, in __init__
    root_definitions.resolve_imports()
  File "/home/david/.virtualenvs/django/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 173, in resolve_imports
    binding.resolve(self)
  File "/home/david/.virtualenvs/django/local/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 184, in resolve
    self.port_type = definitions.port_types[self.port_name.text]
KeyError: u'{http://www.UKMail.com/Services/Contracts/ServiceContracts}IUKMAuthenticationService'
```

**Comment by mvantellingen** [comment]
My bad, I've responded to the issue before pushing the changes. Could you give it another shot? (re-install zeep)

**Comment by froodster** [comment]
Excellent, it's not erroring during import now, I'll pick up on this tomorrow morning/tonight (UK here) and confirm that it's importing correctly, but no errors so all looks good. 

Cheers
