### ISSUE TITLE
Error in 'Security' header

### ISSUE THREAD

**Issue by MaxOvcharov** [mvantellingen/python-zeep#403]
I try to parse response,

```
from requests import Session
from zeep import Client
from zeep.transports import Transport
from zeep.wsse.signature import Signature

from settings import KEY_FILENAME, CERT_FILENAME
session = Session()
session.verify = False
transport = Transport(session=session)
r = session.get('https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2?wsdl',
                cert=(CERT_FILENAME, KEY_FILENAME))
client = Client('https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2?wsdl',
                wsse=Signature(KEY_FILENAME, CERT_FILENAME), transport=transport)

# client.wsdl.dump()
client.service.getAllLpusInfo(returnBranches=True, externalSystemId='MPGU')
```

 but in processing I got this error. What's wrong with my code?
```
</weekDay><workItem><from>09:00</from><to>16:00</to></workItem></weekDaySchedule></lpuWorkSchedule><phones>(499) 248-79-35</phones><director>&#1051;&#1077;&#1074;&#1080;&#1085; &#1052;&#1080;&#1093;&#1072;&#1080;&#1083; &#1045;&#1092;&#1080;&#1084;&#1086;&#1074;&#1080;&#1095;</director><subordination>&#1075;&#1086;&#1088;&#1086;&#1076;&#1089;&#1082;&#1072;&#1103;</subordination><hasPharmacy>1</hasPharmacy><hasEmergencyAidStation>&#1085;&#1077;&#1090;</hasEmergencyAidStation><hasPediatricDepartment>&#1085;&#1077;&#1090;</hasPediatricDepartment><parentLpu><id>10507603</id><lpuNumber>1</lpuNumber><lpuName>&#1055;&#1089;&#1080;&#1093;&#1080;&#1072;&#1090;&#1088;&#1080;&#1095;&#1077;&#1089;&#1082;&#1072;&#1103; &#1082;&#1083;&#1080;&#1085;&#1080;&#1095;&#1077;&#1089;&#1082;&#1072;&#1103; &#1073;&#1086;&#1083;&#1100;&#1085;&#1080;&#1094;&#1072; &#8470; 1 &#1080;&#1084;. &#1053;.&#1040;. &#1040;&#1083;&#1077;&#1082;&#1089;&#1077;&#1077;&#1074;&#1072;</lpuName></parentLpu></return></ns2:getAllLpusInfoResponse></soap:Body></soap:Envelope>
Traceback (most recent call last):
  File "/home/max/bot_project/Bots_Django/TelegramBot/TelegramBot/simple_soap_client.py", line 47, in <module>
    client.service.getAllLpusInfo(returnBranches=True, externalSystemId='MPGU')
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 115, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 155, in process_reply
    client.wsse.verify(doc)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsse/signature.py", line 43, in verify
    verify_envelope(envelope, self.certfile)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsse/signature.py", line 199, in verify_envelope
    security = header.find(QName(ns.WSSE, 'Security'))
AttributeError: 'NoneType' object has no attribute 'find'
```

```

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by MaxOvcharov** [comment]
OK! Here it is:

```
from lxml import etree
import pretend
from requests import Session
from zeep import Client
from zeep.transports import Transport
from zeep.wsse.signature import Signature

from settings import KEY_FILENAME, CERT_FILENAME

session = Session()
session.verify = False
transport = Transport(session=session)
r = session.get('https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2?wsdl',
                cert=(CERT_FILENAME, KEY_FILENAME))
client = Client('https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2?wsdl',
                wsse=Signature(KEY_FILENAME, CERT_FILENAME), transport=transport)

node = client.service._binding.create_message("getAllLpusInfo", returnBranches=True, externalSystemId='MPGU')
print etree.tostring(node, pretty_print=True)
```
The output is:
```
/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:getAllLpusInfo xmlns:ns0="http://api.service.soap.emias.lanit.ru/">
      <returnBranches>true</returnBranches>
      <externalSystemId>MPGU</externalSystemId>
    </ns0:getAllLpusInfo>
  </soap-env:Body>
</soap-env:Envelope>
```

**Comment by mvantellingen** [comment]
That doens't seem like something I can run :-)

Again, please see the documentation to which I provided a link

**Comment by MaxOvcharov** [comment]
I have another example with debug logger: 

```
print http_get.getDoctorsInfo(omsNumber='9988889785000068', birthDate=datetime.datetime(2011, 04, 14),
                              externalSystemId='MPGU')
```
request log:
```
zeep.transports: HTTP Post to https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Header>
    <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#id-29580d1e-12d8-464d-913d-0387266faee1">
<Transforms>
<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>iuKtZPomDI5mK4CiQNcxOm23OOc=</DigestValue>
</Reference>
<Reference URI="#id-0cafe668-c5b6-46fa-8315-d0c921c8fa85">
<Transforms>
<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>Dxoh0i5y9AlhY+4+pX+j+DNns9Q=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>JWOUCxRkuxow0tXp9kkXgzaZM69lkSqp8D3gSnrNsDD0vfZbeeKmjXUxN+D2PSRc
eHLY+BeQP4MXlqsOvqmaaHWhhSq4eebERAJpXf1gtm0ww/6Lf+Zulu0j/TMBzBcn
f9psMA1tljQM6OkdyFPyxTyhBlCsYM3LOq72H+TMHI4=</SignatureValue>
<KeyInfo>
<wsse:SecurityTokenReference><X509Data>


<X509Certificate> ************ </X509Certificate>
<X509IssuerSerial>
<X509IssuerName>CN=TestMedCA,O=Mosgorzdrav,C=RU</X509IssuerName>
<X509SerialNumber>5698664170551774949</X509SerialNumber>
</X509IssuerSerial>
</X509Data>
</wsse:SecurityTokenReference></KeyInfo>
</Signature>
      <ns0:Timestamp xmlns:ns0="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" ns0:Id="id-0cafe668-c5b6-46fa-8315-d0c921c8fa85"/>
    </wsse:Security>
  </soap-env:Header>
  <soap-env:Body xmlns:ns0="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" ns0:Id="id-29580d1e-12d8-464d-913d-0387266faee1">
    <ns0:getDoctorsInfo xmlns:ns0="http://api.service.soap.emias.lanit.ru/">
      <omsNumber>9988889785000068</omsNumber>
      <birthDate>2011-04-14T00:00:00</birthDate>
      <externalSystemId>MPGU</externalSystemId>
    </ns0:getDoctorsInfo>
  </soap-env:Body>
</soap-env:Envelope>
```
response log:
```
zeep.transports: HTTP Response from https://37.230.149.6:10004/emias-soap-service/PGUServicesInfo2 (status: 200):
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Fault><faultcode xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">soap-env:Server</faultcode><faultstring>PATIENT_NOT_FOUND</faultstring><detail><ns2:exception xmlns:ns2="http://api.service.soap.emias.lanit.ru/">&#1055;&#1072;&#1094;&#1080;&#1077;&#1085;&#1090; &#1085;&#1077; &#1085;&#1072;&#1081;&#1076;&#1077;&#1085;</ns2:exception></detail></soap:Fault></soap:Body></soapenv:Envelope>
Traceback (most recent call last):
  File "/home/max/bot_project/Bots_Django/TelegramBot/TelegramBot/simple_soap_client.py", line 76, in <module>
    externalSystemId='MPGU')
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 115, in send
    return self.process_reply(client, operation_obj, response)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 155, in process_reply
    client.wsse.verify(doc)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsse/signature.py", line 43, in verify
    verify_envelope(envelope, self.certfile)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/zeep/wsse/signature.py", line 199, in verify_envelope
    security = header.find(QName(ns.WSSE, 'Security'))
AttributeError: 'NoneType' object has no attribute 'find'
```
At the end I have AttributeError. Why this happens?

**Comment by MaxOvcharov** [comment]
I can't send you the documentation to which you provided a link. This service use ssl certificate.

**Comment by MaxOvcharov** [comment]
I think that this is due to set to False verification  

```
session = Session()
session.verify = False
```

**Comment by mvantellingen** [comment]
I'm sorry, but it seems this requires a lot of investigation from my end to solve due to the fact that you can't provided any example script. I might have the free time for this eventually but not anytime soon. You can always look into commercial support from me.
