### ISSUE TITLE
HTTPBasicAuth not working

### ISSUE THREAD

**Issue by Devligue** [mvantellingen/python-zeep#437]
Zeep: 1.6.0
Python 3.6.0

The wsdl is not public so I cant provide it.

Example:
```
from requests import Session
from requests.auth import HTTPBasicAuth  # or HTTPDigestAuth, or OAuth1, etc.
from zeep import Client
from zeep.transports import Transport

session = Session()
session.auth = HTTPBasicAuth(user, password)
client = Client('https://url/to/my_wsdl.wsdl',
    transport=Transport(session=session))
```

Error:
```
File "C:\Python36-32\lib\site-packages\zeep\client.py", line 124, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\wsdl.py", line 82, in __init__
    root_definitions.resolve_imports()
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\wsdl.py", line 234, in resolve_imports
    binding.resolve(self)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\definitions.py", line 128, in resolve
    operation.resolve(definitions)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\bindings\soap.py", line 428, in resolve
    self.output.resolve(definitions, self.abstract.output_message)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\messages\soap.py", line 285, in resolve
    self.body = self._resolve_body(info['body'], definitions, parts)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\messages\soap.py", line 423, in _resolve_body
    element = part.element.clone()
AttributeError: 'NoneType' object has no attribute 'clone'
```

**Comment by mvantellingen** [comment]
Hi,

Thanks for the report. It is unfortunately missing an example script as explained in the documentation (see http://docs.python-zeep.org/en/master/reporting_bugs.html). This is also mentioned when you create the issue on github.

I realise this will result in extra work on your side, but I can really use the extra help.

**Comment by Devligue** [comment]
I can not give you any more information and examples because all example scripts that are present in [provided instruction](http://docs.python-zeep.org/en/master/reporting_bugs.html) start with the line:
`client = Client('YOUR-WSDL')`
And since my wsdl needs authorization I need to use this code:
```
session = Session()
session.auth = HTTPBasicAuth(user, password)
client = Client('https://url/to/my_wsdl.wsdl',
    transport=Transport(session=session))
```
 Instead of the line provided in instruction. And guess what - This gives the same error! Which is:
`AttributeError: 'NoneType' object has no attribute 'clone'`
Because otherwise, just using your examples I will just get:
`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: my_wsdl`
which will tell you even less.

But ok. If you need this just because "this is how issue should be presented" then here you go:
Example 1:
```
from lxml import etree
from zeep import Client

client = Client('my_wsdl')

# client.service.OPERATION_NAME(*args, **kwargs) becomes
node = client.create_message(
    client.service, 'OPERATION_NAME', *args, **kwargs)

print(etree.tostring(node, pretty_print=True))
```
```
File "C:\Python36-32\lib\site-packages\zeep\client.py", line 124, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\wsdl.py", line 79, in __init__
    document = self._get_xml_document(location)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\wsdl.py", line 140, in _get_xml_document
    location, self.transport, self.location, strict=self.strict)
  File "C:\Python36-32\lib\site-packages\zeep\loader.py", line 69, in load_external
    content = transport.load(url)
  File "C:\Python36-32\lib\site-packages\zeep\transports.py", line 111, in load
    content = self._load_remote_data(url)
  File "C:\Python36-32\lib\site-packages\zeep\transports.py", line 127, in _load_remote_data
    response.raise_for_status()
  File "C:\Python36-32\lib\site-packages\requests\models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: my_wsdl
```

Example 2: (NOTE: I am not even replacing the operation name because the error is thrown before that)
```
import pretend  # pip install pretend

from zeep import Client
from zeep.transports import Transport

# Replace YOUR-WSDL and OPERATION_NAME with the wsdl url
# and the method name you are calling. The response
# needs to be set in the content=""" """ var.

client = Client('my_wsdl')
response = pretend.stub(
    status_code=200,
    headers={},
    content="""
        <!-- The response from the server -->
    """)

operation = client.service._binding._operations['OPERATION_NAME']
result = client.service._binding.process_reply(
    client, operation, response)

print(result)
```
```
File "C:\Python36-32\lib\site-packages\zeep\client.py", line 124, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\wsdl.py", line 79, in __init__
    document = self._get_xml_document(location)
  File "C:\Python36-32\lib\site-packages\zeep\wsdl\wsdl.py", line 140, in _get_xml_document
    location, self.transport, self.location, strict=self.strict)
  File "C:\Python36-32\lib\site-packages\zeep\loader.py", line 69, in load_external
    content = transport.load(url)
  File "C:\Python36-32\lib\site-packages\zeep\transports.py", line 111, in load
    content = self._load_remote_data(url)
  File "C:\Python36-32\lib\site-packages\zeep\transports.py", line 127, in _load_remote_data
    response.raise_for_status()
  File "C:\Python36-32\lib\site-packages\requests\models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: my_wsdl
```

**Comment by mvantellingen** [comment]
I don't need it just because, I need it so that I can spend less of my spare time on your issue.

**Comment by Devligue** [comment]
Imagine that it isn't my life priority either. I have encountered bug and tried to solve it. I gave you all information and surrounding condition I had and knew about. Yet you ask me three times for the same thing. Well I don't have any more info. Please be more specific about what you want because the instruction you keep sending me is useless in my case.

**Comment by ravi9884** [comment]
@Devligue you sir are rude for someone asking for help!!

**Comment by Devligue** [comment]
@ravi9884 Well, it may look like it from this issue. And to be honest I was quite angry when writing last response. But the truth is that this issue was my third contact with author of Zeep. First one was on StackOverflow where I described my issue in detail asking for help, there he asked me to open an issue here. But before I did, I found that somone had this problem before (another issue) so I wrote there only a comment to show that I also have this problem. We got exact the same answer. So I have opened my own issue and described my problem again. Just to get exact same answer "follow the bug report template". But guess what? I can not tell him any more about the bug that I already did. I do not know anything more, and I did all steps from template that I was able to reproduce.

So now imagine that I did not have to do this bug reporting at all. I do not really need this Zeep package, because there are at least couple of others that I can use insted. I just felt like helping, and decided to let someone know that there probably is a bug in their software. And all I get is being tossed around from issue to issue, from site to site. Maybe I overeacted, but how I was treated was not nice either.

**Comment by grajpurohithar** [comment]
I have the same issue while calling a soap service.
Python : 3.6
Zeep : 2.5.0

Example:
```
from requests import Session
from requests.auth import HTTPBasicAuth  # or HTTPDigestAuth, or OAuth1, etc.
from zeep import Client
from zeep.transports import Transport

session = Session()
session.auth = HTTPBasicAuth(user, password)
client = Client('https://url/to/my_wsdl.wsdl', transport=Transport(session=session))
```

Error:
``` 
Traceback (most recent call last):
  File "UsingZeep.py", line 17, in <module>
    client = Client('https://demo.net/enterprise/soap?ServiceName=DemoManagementService&wsdl', transport=Transport(session=session))
  File "venvenv/lib/python3.6/site-packages/zeep/client.py", line 134, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "venvenv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 81, in __init__
    root_definitions = Definition(self, document, self.location)
  File "venvenv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 180, in __init__
    self.parse_types(doc)
  File "venvenv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 313, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "venvenv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 106, in add_documents
    document = self.create_new_document(node, location)
  File "venvenv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 207, in create_new_document
    schema.load(self, node)
  File "venvenv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 422, in load
    visitor.visit_schema(node)
  File "venvenv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 137, in visit_schema
    self.process(child, parent=node)
  File "venvenv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "venvenv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 196, in visit_import
    strict=self.schema.strict)
  File "venvenv/lib/python3.6/site-packages/zeep/loader.py", line 72, in load_external
    content = transport.load(url)
  File "venvenv/lib/python3.6/site-packages/zeep/transports.py", line 110, in load
    content = self._load_remote_data(url)
  File "venvenv/lib/python3.6/site-packages/zeep/transports.py", line 126, in _load_remote_data
    response.raise_for_status()
  File "venvenv/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.w3.org/2005/05/xmlmime

```
