### ISSUE TITLE
Throws ImportError: cannot import name python_2_unicode_compatible

### ISSUE THREAD

**Issue by Geosynopsis** [mvantellingen/python-zeep#46]
Cannot start the client. Throws the error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-62-d5a333816fcc>", line 1, in <module>
    from zeep import Client
  File "/usr/lib/pycharm-5.0.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/__init__.py", line 1, in <module>
    from zeep.client import Client  # noqa
  File "/usr/lib/pycharm-5.0.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 4, in <module>
    from zeep.wsdl import Document
  File "/usr/lib/pycharm-5.0.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/__init__.py", line 1, in <module>
    from zeep.wsdl.wsdl import Document  # noqa
  File "/usr/lib/pycharm-5.0.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/wsdl.py", line 12, in <module>
    from zeep.wsdl import definitions, http, soap
  File "/usr/lib/pycharm-5.0.4/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/definitions.py", line 4, in <module>
    from six import python_2_unicode_compatible
ImportError: cannot import name python_2_unicode_compatible

**Comment by mvantellingen** [comment]
Hi,

Could you give version 0.7.0 a chance? The previous versions didn't specify the six version correctly

**Comment by mvantellingen** [comment]
Closing for now, be free to re-open if that didn't fix the issue (verify by checking `pip freeze | grep six`
