### ISSUE TITLE
Parsing of wsdl fails

### ISSUE THREAD

**Issue by vlinhart** [mvantellingen/python-zeep#47]
Hello,
I'm trying to use this SOAP service:

http://destservices.touricoholidays.com/DestinationsService.svc?wsdl

the library fails like this:

```python
from zeep import Client
client = Client('http://destservices.touricoholidays.com/DestinationsService.svc?wsdl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 59, in __init__
    root_definitions.resolve_imports()
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 185, in resolve_imports
    binding.resolve(self)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 187, in resolve
    operation.resolve(definitions)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 325, in resolve
    self.input.resolve(definitions, self.abstract.input)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 109, in resolve
    self._info['header'], definitions, parts)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 128, in _resolve_header
    message = definitions.messages[message_name]
KeyError: u'{http://touricoholidays.com/WSDestinations/2008/08/Contracts}DestinationRequest_Headers'
```

Any ideas?
Thanks

**Comment by mvantellingen** [comment]
It does work with zeep==0.6.0. Seems like a refactor in the wsdl importing broke this, i'll look at it later

**Comment by mvantellingen** [comment]
Just uploaded 0.7.1 with a fix for this. Thanks for the issue report and let me know if you run into any more issues 👍
