### ISSUE TITLE
SOAP request XML message return by zeep don't define basic xsd type.

### ISSUE THREAD

**Issue by willibix** [mvantellingen/python-zeep#470]
Hi,

I have a issue with basic xsd type when sending a request.

So basicly, when I call the SOAP service that I'm using with a method that required a string (xsd:string), the type is not defile in the xml message that is send by zeep. According to the support of the service provider, those are required for their service to work. It's also true for other basic xsd type like integer (xsd:integer).

Using Zeep 2.1.1
When i call this:
```
# -*- coding: utf-8 -*-
"""This is the code used to test the Baton SOAP webservice"""

from zeep import Client
from zeep.transports import Transport
from requests import Session
from requests.auth import HTTPBasicAuth

SESSION = Session()
SESSION.auth = HTTPBasicAuth('something', 'something')

URL = 'http://10.0.0.1:8080/Baton/Tasks/vtasks.wsdl'
CLIENT = Client(wsdl=URL, transport=Transport(session=SESSION))

RESULT = CLIENT.service.result(taskId='0000015ca2e45f838136c6b6000a0000000000ab')
```
 it return me a error message:
```
Traceback (most recent call last):
  File "TestBatonZeep.py", line 15, in <module>
    RESULT = CLIENT.service.result(taskId='0000015ca2e45f838136c6b6000a0000000000ab')
  File "C:\Python27\lib\site-packages\zeep\client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 120, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 173, in process_reply
    return self.process_error(doc, operation)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 275, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: Processing Failure
```
So I puted the real call in comment and called the "create message" instead :
```
# -*- coding: utf-8 -*-
"""This is the code used to test the Baton SOAP webservice"""

from lxml import etree
from zeep import Client
from zeep.transports import Transport
from requests import Session
from requests.auth import HTTPBasicAuth

SESSION = Session()
SESSION.auth = HTTPBasicAuth('something', 'something')

URL = 'http://10.0.0.1:8080/Baton/Tasks/vtasks.wsdl'
CLIENT = Client(wsdl=URL, transport=Transport(session=SESSION))

#RESULT = CLIENT.service.result(taskId='0000015ca2e45f838136c6b6000a0000000000ab')

node = CLIENT.create_message(CLIENT.service, 'result', taskId='0000015ca2e45f838136c6b6000a0000000000ab')

print etree.tostring(node, pretty_print=True)
```
And the XML message sent by zeep look like this:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:result xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      <taskId>0000015ca2e45f838136c6b6000a0000000000ab</taskId>
    </ns0:result>
  </soap-env:Body>
</soap-env:Envelope>
```
But according to the service provider, it should look like this:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:result xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      <taskId xsi:type="xsd:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId>
    </ns0:result>
  </soap-env:Body>
</soap-env:Envelope>
```
or this:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:result xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      <taskId xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId>
    </ns0:result>
  </soap-env:Body>
</soap-env:Envelope>
```
Also, for reference, here's the XML message zeep send when the parameter is an array of string.

Call this:
```
# -*- coding: utf-8 -*-
"""This is the code used to test the Baton SOAP webservice"""

from lxml import etree
from zeep import Client
from zeep.transports import Transport
from requests import Session
from requests.auth import HTTPBasicAuth

SESSION = Session()
SESSION.auth = HTTPBasicAuth('admin', 'admin')

URL = 'http://10.0.0.1:8080/Baton/Tasks/vtasks.wsdl'
CLIENT = Client(wsdl=URL, transport=Transport(session=SESSION))

#RESULT = CLIENT.service.taskInfo(taskIds=['0000015ca2e45f838136c6b6000a0000000000ab'])

node = CLIENT.create_message(CLIENT.service, 'taskInfo', taskIds=['0000015ca2e45f838136c6b6000a0000000000ab'])

print etree.tostring(node, pretty_print=True)
```
Return that:
```
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:taskInfo xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      <taskIds>
        <item xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">0000015ca2e45f838136c6b6000a0000000000ab</item>
      </taskIds>
    </ns0:taskInfo>
  </soap-env:Body>
</soap-env:Envelope>
```

Which work fine with the service I used since the detail of the type are define.

Also if it can help, [ here's the WSDL for the service that I used ](https://gist.github.com/willibix/57db51a5fc16ae2688899b5c7d01088c)

Is there a way around this? Is it something that can or have to be fix in zeep?

**Comment by willibix** [comment]
Is there a way to force zeep to declare the string type or other basic xsd type that are not defined in the XML tag? Right now the SOAP request XML message that calls a function with string value as parameters send by zeep look like this:

<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:result xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      **<taskId>0000015ca2e45f838136c6b6000a0000000000ab</taskId>**
    </ns0:result>
  </soap-env:Body>
</soap-env:Envelope>


But, in some case (like with the SOAP API of the "Baton" File-based QC software I'm trying to use) the XML message needs to look like this:

<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:result xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      **<taskId xsi:type="xsd:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId>**
    </ns0:result>
  </soap-env:Body>
</soap-env:Envelope>

Or This:

<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:result xmlns:ns0="http://10.0.0.1:8080/Baton/Tasks/">
      **<taskId xsi:type="xsd:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId>**
    </ns0:result>
  </soap-env:Body>
</soap-env:Envelope>

I really need help on this one! It's stopping me in my development and no other SOAP client module in Python really work fine other than zeep at the moment! Is it possible to work around this. Or is it something that can be added in zeep? I don't know, like passing the string parameters with this _taskId=xsd.String("My String")_ would return a string with is type declares in the XML tag like this _<taskId xsi:type="xsd:string">My String</taskId>_ or something of the sort.

**Comment by mvantellingen** [comment]
I'm not really following, sorry.

Zeep detects these (relevant) calls:
```
result(taskId: xsd:string) -> out: ns0:ArrayOf_xsd_stringType
taskInfo(taskIds: ns0:ArrayOf_xsd_stringType) -> out: xsd:string
```

So you will use these as:
```
client.service.result("0000015ca2e45f838136c6b6000a0000000000ab")
client.service.taskInfo(["0000015ca2e45f838136c6b6000a0000000000ab"])
```

There is no need to set xsi:type on the result() call since it is already defined as a xsd:string type.

**Comment by willibix** [comment]
I'll try to explain more clearly and more directly my issue.

So when you call this `client.service.result(taskId="0000015ca2e45f838136c6b6000a0000000000ab")`, the result function is sent to the service by zeep in a XML wrapped message that contain the following XML tag defining the string parameter: `<taskId>0000015ca2e45f838136c6b6000a0000000000ab</taskId>`. So my issue reside in this XML tag: the service return me a error because he expect the string parameter sent in the XML soap message to actually look like this  <taskId xsi:type="xsd:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId> or this `<taskId xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId>` (explicitly define the taskId XML tag as a string). So what I'm looking for is a way to send the XML message with the XML tag for the string parameter that look like one of those 2 other way.

Is it more clear now? Can some one help me with this?

**Comment by willibix** [comment]
P.S: The request work fine when I send it with SOAP UI and this is how the XML message actually look in SOAP UI for the "result" function service request:

```
<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tas="http://10.0.0.171:8080/Baton/Tasks/">
   <soapenv:Header/>
   <soapenv:Body>
      <tas:result soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
         <taskId xsi:type="xsd:string">0000015ca2e45f838136c6b6000a0000000000ab</taskId>
      </tas:result>
   </soapenv:Body>
</soapenv:Envelope>
```

**Comment by willibix** [comment]
Is my bug report still unclear... do you need more example or explanation...

**Comment by mvantellingen** [comment]
No sorry, it's just that it is summer + volunteer work + a busy schedule. I'll look at it asap

**Comment by tonysepia** [comment]
+1 having the same issue.
Essentially, some SOAP servers expect to see the type in the tag like this:
` i:type="b:string" xmlns:b="http://www.w3.org/2001/XMLSchema"`

otherwise they return an error:
zeep.exceptions.Fault: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://xxxxx. The InnerException message was 'Element Value from namespace http://schemas.datacontract.org/2004/07/xxxx cannot have child contents to be deserialized as an object. Please use XmlNode[] to deserialize this pattern of XML.'.  Please see InnerException for more details.

This is because deserializer expects to see the object type

**Comment by tonysepia** [comment]
I have found a way to get zeep to generate the following tag, which is what the SOAP server expects:

    value = zeep.xsd.AnyObject(zeep.xsd.String(), "my string value")

This results in:

    <ns1:Value xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">my string value</ns1:Value>

**Comment by ahfee88** [comment]
I am having the same issue.
Is there been any updates on this issue?

**Comment by gmarinella9** [comment]
> I have found a way to get zeep to generate the following tag, which is what the SOAP server expects:
> 
> ```
> value = zeep.xsd.AnyObject(zeep.xsd.String(), "my string value")
> ```
> 
> This results in:
> 
> ```
> <ns1:Value xmlns:xs="http://www.w3.org/2001/XMLSchema" xsi:type="xs:string">my string value</ns1:Value>
> ```

how you create the Element <Value> ?
