### ISSUE TITLE
nillable elements not serialized correctly

### ISSUE THREAD

**Issue by wolfadactyl** [mvantellingen/python-zeep#51]
Looks like there's an issue with nillable elements where objects that are None get converted to '' which then throws an error when being serialized. Given a message with either of these elements:

```
<s:element minOccurs="1" maxOccurs="1" name="LongId" nillable="true" type="s:long"/>
<s:element minOccurs="1" maxOccurs="1" name="DateOfBirth" nillable="true" type="s:dateTime"/>
```

An error will be thrown as follows:

```
zeep.exceptions.Fault: System.Web.Services.Protocols.SoapException: Server was unable to read request. ---> System.InvalidOperationException: There is an error in XML document (1, 954). ---> System.FormatException: The string '' is not a valid AllXsd value.
   at System.Xml.Schema.XsdDateTime..ctor(String text, XsdDateTimeFlags kinds)
   at System.Xml.XmlConvert.ToDateTime(String s, XmlDateTimeSerializationMode dateTimeOption)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read10_NullableOfDateTime(Boolean checkType)
```

I have not dug deeply into the issue but I would assume the same is the case for all types, not just those two.

**Comment by mvantellingen** [comment]
hi @wolfadactyl. I wasn't yet able to reproduce it (see linked commit). Can you proved the generated xml?

``client.service._binding.create_message('Operation', arg1, arg2 etc)`` ?

**Comment by wolfadactyl** [comment]
Hmm, all of the issues I've had so far have had minOccurs=1, so maybe that has something to do with it? My xml otherwise looks functionally equivalent to yours:

```
<soap-env:Envelope xmlns:ns0=“{ns}” xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:PostMsg>
      <ns0:Msg>
        <ns0:id>{id}</ns0:id>
        <ns0:Obj1>
          <ns0:DateOfBirth/>
          <ns0:LongId/>
        </ns0:Obj1>
      </ns0:Msg>
    </ns0:PostMsg>
  </soap-env:Body>
</soap-env:Envelope>
```

**Comment by mvantellingen** [comment]
Are you able to provide a WSDL? That makes it easier for me to look into

**Comment by wolfadactyl** [comment]
Hmm I can't provide the actual WSDL, but here's a dumbed down version that should suffice with some additional cases:
```
<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns=“http://tests.python-zeep.org/“ xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace=“http://tests.python-zeep.org/”>
	<wsdl:types>
		<s:schema elementFormDefault="qualified" targetNamespace=“http://tests.python-zeep.org/“>
			<s:element name="PostMessage”>
				<s:complexType>
					<s:sequence>
						<s:element minOccurs="0" maxOccurs="1" name=“Message” type="tns:MessageType”/>
					</s:sequence>
				</s:complexType>
			</s:element>
			<s:complexType name=“MessageType”>
				<s:sequence>
					<s:element minOccurs="0" maxOccurs="1" name=“Id” type="s:string"/>
					<s:element minOccurs="0" maxOccurs="1" name=“Info” type="tns:MessageInfo”/>
				</s:sequence>
			</s:complexType>
			<s:complexType name=“MessageInfo”>
				<s:sequence>
					<s:element minOccurs="1" maxOccurs="1" name=“ValueDec” nillable="true" type="s:decimal"/>
					<s:element minOccurs="1" maxOccurs="1" name=“DateOfBirth” nillable="true" type="s:dateTime"/>
					<s:element minOccurs="1" maxOccurs="1" name=“LongId” nillable="true" type="s:long"/>
					<s:element minOccurs="1" maxOccurs="1" name="Code" nillable="true" type="tns:Code"/>
					<s:element minOccurs="1" maxOccurs="1" name=“OtherId" nillable="true" type="s:int"/>
				</s:sequence>
			</s:complexType>
			<s:simpleType name="Code">
				<s:restriction base="s:string">
					<s:enumeration value="Null"/>
					<s:enumeration value=“0001"/>
					<s:enumeration value=“0010”/>
					<s:enumeration value=“0101”/>
				</s:restriction>
			</s:simpleType>
		</s:schema>
	</wsdl:types>
	<wsdl:message name="PostMessageSoapIn">
		<wsdl:part name="parameters" element="tns:PostMessage”/>
	</wsdl:message>
	<wsdl:message name="PostMessageSoapOut”>
		<wsdl:part name="parameters" element="tns:PostMessageResponse"/>
	</wsdl:message>
	<wsdl:portType name=“SoapMessages”>
		<wsdl:operation name="PostMessage”>
			<wsdl:input message="tns:PostMessageSoapIn"/>
			<wsdl:output message="tns:PostMessageSoapOut"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="SoapMessages" type="tns:SoapMessages">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="PostMessage”>
			<soap:operation soapAction=“http://tests.python-zeep.org/PostMessage” style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name=“SoapMessages”>
		<wsdl:port name=“SoapMessages” binding="tns:SoapMessages">
			<soap:address location=“http://tests.python-zeep.org/SoapMessages.asmx"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
```

**Comment by mvantellingen** [comment]
Thanks! Do you also have a code snippet how you call zeep? 

```python
import zeep
from lxml import etree

client = zeep.Client('bla.wsdl')

node = client.service._binding.create_message('PostMessage', {'Info': {}})
print etree.tostring(node, pretty_print=True)
```

```xml
<soap-env:Envelope xmlns:ns0="http://tests.python-zeep.org/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:PostMessage>
      <ns0:Message>
        <ns0:Info>
          <ns0:ValueDec/>
          <ns0:DateOfBirth/>
          <ns0:LongId/>
          <ns0:Code/>
          <ns0:OtherId/>
        </ns0:Info>
      </ns0:Message>
    </ns0:PostMessage>
  </soap-env:Body>
</soap-env:Envelope>```

**Comment by wolfadactyl** [comment]
Right now I'm just building the message objects separately, so I'm doing something along these lines:
```
import datetime
import zeep

client = Client(‘http://tests.python-zeep.org/SoapMessages.wsdl’,
                service_name=‘SoapMessages’,
                port_name=‘SoapMessages’)
message_info = client.get_type(‘{http://tests.python-zeep.org/}MessageInfo’)
message_info_data = {
	‘Code': "0001",
	‘DateOfBirth’: datetime.datetime.now()
}

message = client.get_type(‘{http://tests.python-zeep.org/}MessageType’)
message_data = {
	‘Id’: 1,
	‘MessageInfo’: message_info(**message_info_data),
}
client.service.PostMessage(Message=message(**message_data))
```

I had previously tried sending a dict with the values directly (as you did), but changed it to this when I had to massage some of the data.

**Comment by mvantellingen** [comment]
The `MessageInfo` should be `Info`, so i'm testing it with the following script:

```python
import zeep
import datetime
from lxml import etree

client = zeep.Client('bla.wsdl')

message_info = client.get_type('{http://tests.python-zeep.org/}MessageInfo')
message_info_data = {
    'Code': '0001',
    'DateOfBirth': datetime.datetime.now()
}

message = client.get_type('{http://tests.python-zeep.org/}MessageType')
message_data = {
    'Id': 1,
    'Info': message_info(**message_info_data),
}
node = client.service._binding.create_message('PostMessage', Message=message(**message_data))
print etree.tostring(node, pretty_print=True)
```


Which outputs

```xml
<soap-env:Envelope xmlns:ns0="http://tests.python-zeep.org/" xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns0:PostMessage>
      <ns0:Message>
        <ns0:Id>1</ns0:Id>
        <ns0:Info>
          <ns0:ValueDec/>
          <ns0:DateOfBirth>2016-06-08T22:31:40</ns0:DateOfBirth>
          <ns0:LongId/>
          <ns0:Code>0001</ns0:Code>
          <ns0:OtherId/>
        </ns0:Info>
      </ns0:Message>
    </ns0:PostMessage>
  </soap-env:Body>
</soap-env:Envelope>

**Comment by wolfadactyl** [comment]
I think the issue might have been when the values passed in were None (instead of just not adding the value). I don't have the changes in front of me at the moment to check, but something like this for the info portion should break all of those serializations:
```
message_info_data = {
    'Code': None,
    'DateOfBirth': None,
    'ValueDec': None,
    'LongId': None,
    'OtherId': None,
}
```

**Comment by wolfadactyl** [comment]
@mvantellingen were you able to repro the issue with this data?

**Comment by mvantellingen** [comment]
Hi @wolfadactyl, sorry but I haven't been able to reproduce or completely understand your problem yet. If you have a test case which I can run which exhibits the issue then that would make things faster to solve.

**Comment by mvantellingen** [comment]
I've refactored quite a bit, can you check with the new 0.11.0 release?

**Comment by wolfadactyl** [comment]
Can do, probably won't get back to it until ~ next week sometime, but I'll see if I can check it out before then.

**Comment by mvantellingen** [comment]
Might be fixed on master. Let me know if it isn't and I re-open it.

**Comment by wolfadactyl** [comment]
Have finally come back around to this, just wanted to close the loop and note that the issue appears to be resolved now. Thanks!
