### ISSUE TITLE
error parsing wsdl

### ISSUE THREAD

**Issue by vlinhart** [mvantellingen/python-zeep#52]
hello, again I've encountered some cursed wsdl which won't parse, please have a look:
```python
from zeep import Client
>>> client = Client('http://demo-hotelws.touricoholidays.com/HotelFlow.svc?wsdl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 58, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 146, in __init__
    self.parse_imports(doc)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 236, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 149, in __init__
    self.messages = self.parse_messages(doc)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 337, in parse_messages
    msg = definitions.AbstractMessage.parse(self, msg_node)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 61, in parse
    part_element = definitions.schema.get_element(part_element)
  File "/envs/roomstorm/local/lib/python2.7/site-packages/zeep/xsd/schema.py", line 136, in get_element
    name.text, ', '.join(self._elements), self))
KeyError: "No such element: u'{http://tourico.com/webservices/hotelv3}SearchHotels' (Only have ) (from: <Schema(location='http://demo-hotelws.touricoholidays.com/HotelFlow.svc?wsdl=wsdl0')>)"
```

**Comment by mvantellingen** [comment]
Should be fixed now. Issue was that the wsdl contained multiple xsd:schema's in one definition which import other schema's.

**Comment by vlinhart** [comment]
:+1: awesome, thank you very much!
