### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by ameniawy** [mvantellingen/python-zeep#526]
I am using zeep version 2.2.0
The wsdl I'm using is wsdl = 'http://37.153.109.99/reseller/ws/?wsdl'
example script:

```python
from __future__ import unicode_literals

import json

from zeep import Client as ZeepClient
from zeep.cache import SqliteCache
from zeep.transports import Transport
from zeep.helpers import serialize_object as zeep_serialize_object

wsdl = 'http://37.153.109.99/reseller/ws/?wsdl'
transport = Transport(cache=SqliteCache())
client = ZeepClient(wsdl=wsdl, transport=transport)
client.set_default_soapheaders({
    "AuthHeader": {
        "ResellerCode": "xx",
        "Username": "xx",
        "Password": "xx"
    }
})
location = {
    "City": {
        "CityCode": "HAM"
    }
}
date_range = {
    "Start": "2017-08-23",
    # "Start": "2017-08-08",
    "End": "2017-08-25"
    # "End": "2017-08-12"
}
rooms = [
    {
        "Room": {
            "Adults": 2,
            "Children": 0
        }
    }
]

filters = {
        "AvailableOnly": 1,
        "Nationality": {
            "ID": 96
        }
}
data = client.service.Hotel_GetAvailability(DateRange=date_range, Rooms=rooms, Filters=filters, Location=location)
data_serialized = zeep_serialize_object(data)
print data_serialized
```

response:
```
Traceback (most recent call last):
  File "TBSAvailability.py", line 66, in <module>
    data = client.service.Hotel_GetAvailability(DateRange=date_range, Rooms=rooms, Filters=filters, Location=location)
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/bindings/soap.py", line 110, in send
    options=options)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/definitions.py", line 197, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/messages/soap.py", line 66, in serialize
    self.body.render(body, body_value)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 249, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 249, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/indicators.py", line 487, in render
    element.render(parent, choice_value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 247, in render
    element.type.render(parent, element_value, None, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 220, in render
    attr_value = value[name] if name in value else NotSet
TypeError: argument of type 'NoneType' is not iterable
```

The zeep client seems to have a problem with the Location object.

**Comment by mvantellingen** [comment]
Should be fixed on master, can you try?

**Comment by ameniawy** [comment]
@mvantellingen yes, thank you for the fix. Cheers
