### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by luanfonceca** [mvantellingen/python-zeep#527]
Hi folks, i am getting this error when i try to create a client based on a wsdl file with Zeep. Can you guys help me out here? I never had worked with soap web services before.

Traceback:
```
Traceback (most recent call last):
  File "BE-zeep.py", line 5, in <module>
    zeep.Client(wsdl=wsdl)
  File "/Users/.../lib/python3.6/site-packages/zeep/client.py", line 123, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "/Users/.../lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
    root_definitions.resolve_imports()
  File "/Users/.../lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 237, in resolve_imports
    service.resolve(self)
  File "/Users/.../lib/python3.6/site-packages/zeep/wsdl/definitions.py", line 295, in resolve
    is_resolved = port.resolve(definitions)
  File "/Users/.../lib/python3.6/site-packages/zeep/wsdl/definitions.py", line 267, in resolve
    force_https)
  File "/Users/.../lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 197, in process_service_port
    address_node = xmlelement.find('soap:address', namespaces=self.nsmap)
AttributeError: 'NoneType' object has no attribute 'get'

```
WSDL file:
```
https://dr-hml.neurotech.com.br/services/soap/porting?wsdl
```

Package Versions:
```
zeep==2.3.0
Python==3.6.1
```

Script:
```py
import zeep

wsdl = 'https://dr-hml.neurotech.com.br/services/soap/porting?wsdl'
zeep.Client(wsdl=wsdl)
```

**Comment by luanfonceca** [comment]
cc @renatooliveira

**Comment by ParityB1t** [comment]
Also running into this issue and looking into it myself

**Comment by ParityB1t** [comment]
I have managed to track down the bug to being in lxml rather than zeep. it seems my version of lxml is outdated, and hence throwing a `StopIteration` exception, which is causing `find()` to return `None`. 

@luanfonceca What is your lxml version?

**Comment by mvantellingen** [comment]
Can you give master a try?

**Comment by deronnax** [comment]
@mvantellingen : I was able to reproduce the bug with the latest stable release (2.3.0). I gave a try with master (6dce326), I can confirm it's fixed.

**Comment by ParityB1t** [comment]
@luanfonceca I just realised there was an error in the .wsdl from my side, which gave the error (soap12 tags specified in soap binding). so it may be that
