### ISSUE TITLE
Cannot unittest with tox | ImportError: cannot import name parse_qname

### ISSUE THREAD

**Issue by gGonz** [mvantellingen/python-zeep#529]
I was trying to use zeep `v2.3.0` to make an integration with a 3rd party SOAP service in one of my projects, I've added some unittests and when calling tox to run the suite I got a weird import error:

```
apps/markets/mx/cierto/handlers.py:6: in <module>
    from zeep import Client
.tox/django/lib/python2.7/site-packages/zeep/__init__.py:1: in <module>
    from zeep.client import CachingClient, Client  # noqa
.tox/django/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
.tox/django/lib/python2.7/site-packages/zeep/client.py:5: in <module>
    from zeep.transports import Transport
.tox/django/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
.tox/django/lib/python2.7/site-packages/zeep/transports.py:9: in <module>
    from zeep.wsdl.utils import etree_to_string
.tox/django/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
.tox/django/lib/python2.7/site-packages/zeep/wsdl.py:7: in <module>
    from zeep.types import Schema
.tox/django/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:171: in load_module
    py.builtin.exec_(co, mod.__dict__)
.tox/django/lib/python2.7/site-packages/zeep/types.py:8: in <module>
    from zeep.utils import parse_qname
E   ImportError: cannot import name parse_qname
```

I looked at the source code of `v2.3.0` and noticed that there are no any `wsdl.py` inside `src/zeep`, so made a `ls -l` inside tox site-packages directory to see what's installed in zeep's directory and found that actually there is a `wsdl.py` file, aside as other files not present in the repo:

```
$ ls -l .tox/django/lib/python2.7/site-packages/zeep/
total 220
-rw-r--r--    1 python   python          215 Aug  7 23:10 __init__.py
-rw-r--r--    1 python   python          437 Aug  7 23:10 __init__.pyc
-rw-r--r--    1 python   python         2601 Aug  7 23:10 __main__.py
-rw-r--r--    1 python   python         2855 Aug  7 23:10 __main__.pyc
drwxr-xr-x    2 python   python         4096 Aug  7 23:10 asyncio
-rw-r--r--    1 python   python         4709 Aug  7 23:10 cache.py
-rw-r--r--    1 python   python         6160 Aug  7 23:10 cache.pyc
-rw-r--r--    1 python   python         9535 Aug  7 23:10 client.py
-rw-r--r--    1 python   python        11114 Aug  7 23:10 client.pyc
-rw-r--r--    1 python   python         2398 Aug  7 23:10 exceptions.py
-rw-r--r--    1 python   python         5473 Aug  7 23:10 exceptions.pyc
-rw-r--r--    1 python   python         2040 Aug  7 23:10 helpers.py
-rw-r--r--    1 python   python         2289 Aug  7 23:10 helpers.pyc
-rw-r--r--    1 python   python         3609 Aug  7 23:10 loader.py
-rw-r--r--    1 python   python         4388 Aug  7 23:10 loader.pyc
-rw-r--r--    1 python   python          761 Aug  7 23:10 ns.py
-rw-r--r--    1 python   python         1039 Aug  7 23:10 ns.pyc
-rw-r--r--    1 python   python         1393 Aug  7 23:10 parser.py
-rw-r--r--    1 python   python         1928 Aug  7 23:10 parser.pyc
-rw-r--r--    1 python   python         2293 Aug  7 23:10 plugins.py
-rw-r--r--    1 python   python         3198 Aug  7 23:10 plugins.pyc
-rw-r--r--    1 python   python         4788 Aug  7 23:10 transports.py
-rw-r--r--    1 python   python         5163 Aug  7 23:10 transports.pyc
-rw-r--r--    1 python   python        10456 Aug  7 23:10 types.py
-rw-r--r--    1 python   python        10456 Aug  7 23:10 types.pyc
-rw-r--r--    1 python   python         2332 Aug  7 23:10 utils.py
-rw-r--r--    1 python   python         3212 Aug  7 23:10 utils.pyc
-rw-r--r--    1 python   python         1188 Aug  7 23:10 wsa.py
-rw-r--r--    1 python   python         1523 Aug  7 23:10 wsa.pyc
drwxr-xr-x    4 python   python         4096 Aug  7 23:10 wsdl
-rw-r--r--    1 python   python         6835 Aug  7 23:10 wsdl.py
-rw-r--r--    1 python   python         6240 Aug  7 23:10 wsdl.pyc
drwxr-xr-x    2 python   python         4096 Aug  7 23:10 wsse
drwxr-xr-x    4 python   python         4096 Aug  7 23:10 xsd
-rw-r--r--    1 python   python         5327 Aug  7 23:10 xsd.py
-rw-r--r--    1 python   python         9457 Aug  7 23:10 xsd.pyc
```

By opening the `wsdl.py` file to see its contents I noticed that it in fact is the same as the `src/zeep/wsdl/wsdl.py` but with leading comments stripped. Downloaded the wheel from PyPi and extracted it, is the same that I have installed on my machine. Same for `v2.2.0`

Seems that for somewhat reason the wheel have messed up with files.

BTW, importing from shell works fine.

**Comment by gGonz** [comment]
Added `--no-binary=zeep` to mi requirements file to install from source instead of wheel, worked fine.

**Comment by mvantellingen** [comment]
Hm interesting, i've changed setup.py a bit, can you give master a try?

**Comment by gGonz** [comment]
I manually built the wheel from master, installed on my tox virtualenv and worked like a charm. Extracted it and noted that it was properly generated, all files seems to be en place :+1: 

Thanks!

**Comment by gGonz** [comment]
BTW, `find_packages` is now imported but not used :stuck_out_tongue_closed_eyes:

**Comment by gGonz** [comment]
Hi, this occurred again with `2.4.0`, now with the `xop` module inside `zeep.wsdl.messages`, extracted the wheel and the issue is because a `zeep.wsdl.messages.py` file, stack trace of the import error:

```
Traceback (most recent call last):                                                                       
  File "/home/python/backend/kiwi/apps/markets/mx/services/cierto/tasks.py", line 23, in create_cierto_user                                                                                                         
    client = CiertoSoapClient()                                                                          
  File "/home/python/backend/kiwi/apps/markets/mx/services/cierto/soap.py", line 37, in __init__         
    transport=transport                                                                                  
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/zeep/client.py", line 123, in __init__                                                                                                    
    self.wsdl = Document(wsdl, self.transport, strict=strict)                                            
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 81, in __init__                                                                                                  
    root_definitions = Definition(self, document, self.location)                                         
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 183, in __init__                                                                                                 
    self.bindings = self.parse_binding(doc)          
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 394, in parse_binding                                                                                            
    from zeep.wsdl import bindings                                                                       
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/zeep/wsdl/bindings/__init__.py", line 1, in <module>                                                                                      
    from .soap import Soap11Binding, Soap12Binding  # noqa                                                
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 171, in load_module                                                                                   
    py.builtin.exec_(co, mod.__dict__)                                                                   
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_                                                                                                       
    exec2(obj, globals, locals)                     
  File "<string>", line 7, in exec2                 
  File "/home/python/backend/kiwi/.tox/django/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 13, in <module>                                                                                         
    from zeep.wsdl.messages.xop import process_xop
ImportError: No module named xop
```
```
$ ls -l .tox/django/lib/python2.7/site-packages/zeep/wsdl/
total 224
-rw-r--r--    1 python   ggonz          416 Aug 29 18:26 __init__.py
-rw-r--r--    1 python   ggonz          588 Aug 29 18:27 __init__.pyc
-rw-r--r--    1 python   ggonz         2109 Aug 29 18:26 attachments.py
-rw-r--r--    1 python   ggonz         3779 Aug 29 18:27 attachments.pyc
-rw-r--r--    1 python   ggonz         8443 Aug 29 18:26 base.py
-rw-r--r--    1 python   ggonz         9065 Aug 29 18:27 base.pyc
drwxr-xr-x    2 python   ggonz         4096 Aug 29 18:27 bindings
-rw-r--r--    1 python   ggonz         8607 Aug 29 18:26 definitions.py
-rw-r--r--    1 python   ggonz        12282 Aug 29 18:27 definitions.pyc
-rw-r--r--    1 python   ggonz         5938 Aug 29 18:26 http.py
-rw-r--r--    1 python   ggonz         7100 Aug 29 18:27 http.pyc
drwxr-xr-x    2 python   ggonz         4096 Aug 29 18:27 messages
-rw-r--r--    1 python   ggonz        20586 Aug 29 18:26 messages.py
-rw-r--r--    1 python   ggonz        20761 Aug 29 18:27 messages.pyc
-rw-r--r--    1 python   ggonz         6816 Aug 29 18:26 parse.py
-rw-r--r--    1 python   ggonz         6963 Aug 29 18:27 parse.pyc
-rw-r--r--    1 python   ggonz        12721 Aug 29 18:26 soap.py
-rw-r--r--    1 python   ggonz        12984 Aug 29 18:27 soap.pyc
-rw-r--r--    1 python   ggonz         1061 Aug 29 18:26 utils.py
-rw-r--r--    1 python   ggonz         1497 Aug 29 18:27 utils.pyc
-rw-r--r--    1 python   ggonz        14760 Aug 29 18:26 wsdl.py
-rw-r--r--    1 python   ggonz        14404 Aug 29 18:27 wsdl.pyc
```

**Comment by thegrymek** [comment]
I have same errors using zeep with tox and setup.py

Last version of zeep is 2.4.0, so to get `master` branch you have to trick pip.

In `setup.py` add zeep in dependency link with fixed version

```
setup(
   name='my_package',
   install_requires=['zeep==999.0.0'],
   dependency_links=['https://github.com/mvantellingen/python-zeep/tarball/master#egg=zeep-999.0.0']
)
```

Solution above is taken from:
https://stackoverflow.com/questions/26061610/pip-install-dependency-links

Pip first search and download packages from `pypy` and then from github. If you manually increase the version (ex. to 999.0.0), then you will force pip to install package directly from github.

Next in `tox.ini` add to your `[testenv]` line:
```
[testenv]
install_command = pip install {opts} {packages} --process-dependency-links
```

to force pip to install packages from `dependency_links` in `setuppy`. By default pip does ignore and warns you about that.

**Comment by gGonz** [comment]
A workaround is to add `--no-binary=zeep` to your requirements or directly to `pip install`, I have mine like this:
```
...
zeep==2.4.0 --no-binary=zeep
...
```

**Comment by thegrymek** [comment]
I dont use requirements. I use setup.py

**Comment by thegrymek** [comment]
Hi, with version == 2.5.0 problem for me is solved.

**Comment by gGonz** [comment]
I can confirm that v2.5.0 also solves the problem for me, no need to add the `--no-binary` option anymore. Thanks! 👍
