### ISSUE TITLE
"Service has no operation...", but this exist!

### ISSUE THREAD

**Issue by Luzcka** [mvantellingen/python-zeep#535]
Hi Michael!

Thank you for your work on Zeep, it is an amazing SOAP lib!!

Using the Python script (below) I receive an error:
AttributeError: Service has no operation 'retornaDadosComcap'

This appears don't find the method name... But, using the site "http://www.soapclient.com/soaptest.html" to test, it work normally!
(few times it fail because the machine is slow)

I believe that the WSDL is not "bad", but it's not impossible or discarded...

WSDL-----------------------------------------------------

<definitions targetNamespace="urn:udesc.service">
	<types>
		<xsd:schema targetNamespace="urn:udesc.service">
			<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>				
		</xsd:schema>
	</types>
	<message name="retornaDadosComcapRequest">
		<part name="dataInicial" type="xsd:string"/>
		<part name="dataFinal" type="xsd:string"/>
		<part name="chave" type="xsd:string"/>
	</message>
	<message name="retornaDadosComcapResponse">
		<part name="return" type="xsd:json"/>
	</message>
	<portType name="udesc.servicePortType">
		<operation name="retornaDadosComcap">
			<documentation>Retorna um json</documentation>
			<input message="tns:retornaDadosComcapRequest"/>
			<output message="tns:retornaDadosComcapResponse"/>
		</operation>
	</portType>
	<binding name="udesc.serviceBinding" type="tns:udesc.servicePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="retornaDadosComcap">
			<soap:operation soapAction="urn:udesc.retornaDadosComcap#retornaDadosComcap" style="rpc"/>
			<input>
				<soap:body use="encoded" namespace="urn:udesc.retornaDadosComcap" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:udesc.retornaDadosComcap" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="udesc.service">
		<port name="udesc.servicePort" binding="tns:udesc.serviceBinding">
			<soap:address location="http://189.90.55.34/geo_fpolis/nusoap/serverWsUdesc.php"/>
		</port>
	</service>
</definitions>

-------------------------------------------------------------------------

A valid response from de site soapclient.com with an invalid key: -------------------------------------

<SOAP-ENV:Envelope>
	<SOAP-ENV:Body>
		<ns1:retornaDadosComcapResponse>
			<return xsi:type="xsd:json">
				{"ok":"1",results":[{"ok":"2","error":"Chave de seguranca invalida!"}]}
			</return>
		</ns1:retornaDadosComcapResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

--------------------------------------------------------------------------------------

Python Script:------------------------------------------------------------------------------------

# -*- coding: utf-8 -*-
"""
Spyder Editor
"""
import zeep

wsdl = 'http://189.90.55.34/geo_fpolis/nusoap/serverWsUdesc.php?wsdl'
client = zeep.Client(wsdl=wsdl)

print(client.service.retornaDadosComcap('01/01/2017', '21/01/2017', 'xxx'))

Complete run output------------------------------------------------------------------

Python 3.5.3 |Anaconda 4.4.0 (64-bit)| (default, Mar  6 2017, 11:58:13)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

runfile('/home/pabloernesto/Documents/Development/Python/ZeepSoapClient.py', wdir='/home/pabloernesto/Documents/Development/Python')
/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/wsdl/wsdl.py:329: UserWarning: The wsdl:message for '{urn:udesc.service}retornaDadosComcapResponse' contains an invalid part ('return'): invalid xsd type or elements
  warnings.warn(str(exc))
/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/wsdl/definitions.py:130: UserWarning: The wsdl:operation 'retornaDadosComcap' was not found in the wsdl:portType '{urn:udesc.service}udesc.servicePortType'
  warnings.warn(str(exc))
Traceback (most recent call last):

  File "<ipython-input-1-ff121bcca37c>", line 1, in <module>
    runfile('/home/pabloernesto/Documents/Development/Python/ZeepSoapClient.py', wdir='/home/pabloernesto/Documents/Development/Python')

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/pabloernesto/Documents/Development/Python/ZeepSoapClient.py", line 13, in <module>
    print(client.service.retornaDadosComcap(dataInicial='01/01/2017', dataFinal='21/01/2017', chave='c71e6cb9bb5de2d12ade57b21922c9d1'))

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/client.py", line 56, in __getattr__
    return self[key]

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/client.py", line 67, in __getitem__
    raise AttributeError('Service has no operation %r' % key)

AttributeError: Service has no operation 'retornaDadosComcap'

--------------------------------------------------------------------------------------

Thanks in advance!
Pablo Ernesto Vigneaux Wilton

Environment:

Ubuntu 61.04 64bits (VM)
Python 3.5.3 :: Anaconda 4.4.0 (64-bit)
Conda version 4.3.24
Spyder version 3.1.4
Zeep version 2.2.0 (installed using: conda install -c conda-forge zeep)
Conda Environment: soap_env

Hi Michael!

Thank you for your work on Zeep, it is an amazing SOAP lib!!

Using the Python script (below) I receive an error:
AttributeError: Service has no operation 'retornaDadosComcap'

This appears don't find the method name... But, using the site "http://www.soapclient.com/soaptest.html" to test, it work normally!
(few times it fail because the machine is slow)

Using Suds it recognize the method but I receive an error because the response have Json data... (TypeNotFound: Type not found: '(json, http://www.w3.org/2001/XMLSchema, )')

I believe that the WSDL is not "bad", but it's not impossible or discarded...

WSDL-----------------------------------------------------

<definitions targetNamespace="urn:udesc.service">
	<types>
		<xsd:schema targetNamespace="urn:udesc.service">
			<xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
			<xsd:import namespace="http://schemas.xmlsoap.org/wsdl/"/>				
		</xsd:schema>
	</types>
	<message name="retornaDadosComcapRequest">
		<part name="dataInicial" type="xsd:string"/>
		<part name="dataFinal" type="xsd:string"/>
		<part name="chave" type="xsd:string"/>
	</message>
	<message name="retornaDadosComcapResponse">
		<part name="return" type="xsd:json"/>
	</message>
	<portType name="udesc.servicePortType">
		<operation name="retornaDadosComcap">
			<documentation>Retorna um json</documentation>
			<input message="tns:retornaDadosComcapRequest"/>
			<output message="tns:retornaDadosComcapResponse"/>
		</operation>
	</portType>
	<binding name="udesc.serviceBinding" type="tns:udesc.servicePortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="retornaDadosComcap">
			<soap:operation soapAction="urn:udesc.retornaDadosComcap#retornaDadosComcap" style="rpc"/>
			<input>
				<soap:body use="encoded" namespace="urn:udesc.retornaDadosComcap" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</input>
			<output>
				<soap:body use="encoded" namespace="urn:udesc.retornaDadosComcap" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
			</output>
		</operation>
	</binding>
	<service name="udesc.service">
		<port name="udesc.servicePort" binding="tns:udesc.serviceBinding">
			<soap:address location="http://189.90.55.34/geo_fpolis/nusoap/serverWsUdesc.php"/>
		</port>
	</service>
</definitions>

-------------------------------------------------------------------------

A valid response from de site soapclient.com with an invalid key: -------------------------------------

<SOAP-ENV:Envelope>
	<SOAP-ENV:Body>
		<ns1:retornaDadosComcapResponse>
			<return xsi:type="xsd:json">
				{"ok":"1",results":[{"ok":"2","error":"Chave de seguranca invalida!"}]}
			</return>
		</ns1:retornaDadosComcapResponse>
	</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

--------------------------------------------------------------------------------------

Python Script:------------------------------------------------------------------------------------

# -*- coding: utf-8 -*-
"""
Spyder Editor
"""
import zeep

wsdl = 'http://189.90.55.34/geo_fpolis/nusoap/serverWsUdesc.php?wsdl'
client = zeep.Client(wsdl=wsdl)

print(client.service.retornaDadosComcap('01/01/2017', '21/01/2017', 'xxx'))

Complete run output------------------------------------------------------------------

Python 3.5.3 |Anaconda 4.4.0 (64-bit)| (default, Mar  6 2017, 11:58:13)
Type "copyright", "credits" or "license" for more information.

IPython 5.3.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

runfile('/home/pabloernesto/Documents/Development/Python/ZeepSoapClient.py', wdir='/home/pabloernesto/Documents/Development/Python')
/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/wsdl/wsdl.py:329: UserWarning: The wsdl:message for '{urn:udesc.service}retornaDadosComcapResponse' contains an invalid part ('return'): invalid xsd type or elements
  warnings.warn(str(exc))
/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/wsdl/definitions.py:130: UserWarning: The wsdl:operation 'retornaDadosComcap' was not found in the wsdl:portType '{urn:udesc.service}udesc.servicePortType'
  warnings.warn(str(exc))
Traceback (most recent call last):

  File "<ipython-input-1-ff121bcca37c>", line 1, in <module>
    runfile('/home/pabloernesto/Documents/Development/Python/ZeepSoapClient.py', wdir='/home/pabloernesto/Documents/Development/Python')

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/pabloernesto/Documents/Development/Python/ZeepSoapClient.py", line 13, in <module>
    print(client.service.retornaDadosComcap(dataInicial='01/01/2017', dataFinal='21/01/2017', chave='c71e6cb9bb5de2d12ade57b21922c9d1'))

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/client.py", line 56, in __getattr__
    return self[key]

  File "/home/pabloernesto/anaconda3/lib/python3.5/site-packages/zeep/client.py", line 67, in __getitem__
    raise AttributeError('Service has no operation %r' % key)

AttributeError: Service has no operation 'retornaDadosComcap'

--------------------------------------------------------------------------------------

Thanks in advance!
Pablo Ernesto Vigneaux Wilton

Environment:

Ubuntu 61.04 64bits (VM)
Python 3.5.3 :: Anaconda 4.4.0 (64-bit)
Conda version 4.3.24
Spyder version 3.1.4
Zeep version 2.2.0 (installed using: conda install -c conda-forge zeep)
Conda Environment: soap_env

**Comment by mvantellingen** [comment]
Could you please format your issue correctly and add an example script as requested?

**Comment by Luzcka** [comment]
I just did it. 
Sorry for my mistake, I have attached an example too.

Thanks

**Comment by nsimonov** [comment]
Hello, Luzcka!
Have you solved your problem?
I have the same error ((

**Comment by n00blet** [comment]
@Luzcka was this issue resolved by any chance ??

**Comment by Luzcka** [comment]
Hi!

Sorry for the late reply, I really tried for a time but without success...
I never tried again... It's possible that the interface (origin) had a bad
structure, but in this case is a good approach have any report about it.

Pablo Ernesto Vigneaux Wilton
