### ISSUE TITLE
ValueError: All strings must be XML compatible

### ISSUE THREAD

**Issue by Flauschbaellchen** [mvantellingen/python-zeep#538]
Zeep version: 2.3.0

If a value contains special characters an error is raised while creating the XML post request:
Example:
```
{ 'title': 'tmp\x0b foobar' }
```
This happens with "very" special characters like `\v`, `\b`, `\f` etc.
More HTML/ASCII-like characters like `&` or `ö` are escaped normally to `&amp;` and `&ouml;` etc.
```
File "C:\Python34\lib\site-packages\zeep\client.py", line 41, in __call__
  File "C:\Python34\lib\site-packages\zeep\wsdl\bindings\soap.py", line 110, in send
  File "C:\Python34\lib\site-packages\zeep\wsdl\bindings\soap.py", line 68, in _create
  File "C:\Python34\lib\site-packages\zeep\wsdl\definitions.py", line 197, in create
  File "C:\Python34\lib\site-packages\zeep\wsdl\messages\soap.py", line 66, in serialize
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
  File "C:\Python34\lib\site-packages\zeep\xsd\types\complex.py", line 249, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\indicators.py", line 241, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
  File "C:\Python34\lib\site-packages\zeep\xsd\types\complex.py", line 249, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\indicators.py", line 241, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
  File "C:\Python34\lib\site-packages\zeep\xsd\types\complex.py", line 249, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\indicators.py", line 241, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
  File "C:\Python34\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
  File "C:\Python34\lib\site-packages\zeep\xsd\types\simple.py", line 71, in render
  File "lxml.etree.pyx", line 942, in lxml.etree._Element.text.__set__ (src\lxml\lxml.etree.c:46289)
  File "apihelpers.pxi", line 695, in lxml.etree._setNodeText (src\lxml\lxml.etree.c:20947)
  File "apihelpers.pxi", line 683, in lxml.etree._createTextNode (src\lxml\lxml.etree.c:20823)
  File "apihelpers.pxi", line 1393, in lxml.etree._utf8 (src\lxml\lxml.etree.c:27119)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

Is there something like "best practice" to workaround this issue?
As this can happen to all text attributes of all objects it would be much work to filter them explicitly on creation of the zeep-object.
Would it be possible to let zeep handle those errors more gracefully?

**Comment by mvantellingen** [comment]
hm, perhaps we need to explicitly wrap it in a cdata element?

**Comment by Flauschbaellchen** [comment]
Hi @mvantellingen, thanks for your response to this issue.
Is there anything we can test/do to further resolve this?

Currently, we implemented a wrapper that recursively replaces the special codes with spaces.
Doing so allows us to workaround the exception but changes the data transmitted leaving an inconsistency between client and server.

Just for reference, the code for the workaround:
`_soap_client.factory` within the wrapper holds `zeep.Client(...).type_factory(...)`.
Usage along this line: `get_soap_client_type_factory().myDataType(attr1, attr2)`

```python
class SoapClientFactoryWrapper:
    def __getattr__(self, object_name):
        def getattr_inner(*args, **kwargs):
            args = self._replace(args)
            for key, value in kwargs.items():
                kwargs[key] = self._replace(value)

            return getattr(_soap_client.factory, object_name)(*args, **kwargs)
        return getattr_inner

    def _replace(self, value):
        if isinstance(value, str):
            return value.replace("\x0b", " ").replace("\x0c", " ").replace("\x08", " ")

        if isinstance(value, list):
            return list([self._replace(v) for v in value])

        if isinstance(value, tuple):
            return tuple(list([self._replace(v) for v in value]))

        if isinstance(value, dict):
            for k, v in value.items():
                value[k] = self._replace(v)
            return value

        # unknown type
        return value

def get_soap_client_type_factory():
    return SoapClientFactoryWrapper()

**Comment by raheem1316** [comment]
i'm getting this error in zeep .. 

Traceback (most recent call last):
  File "C:\Users\Raheem Shaik\Desktop\practise1.py", line 651, in <module>
    result = client.service.leadmanagementLeadserviceListuserlead(accessToken,role,attributes,conditionFilters,filters,limit,leadIndex,dueAmountFilter)
  File "C:\Python27\lib\site-packages\zeep\client.py", line 45, in __call__
    self._op_name, args, kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 110, in send
    options=options)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\definitions.py", line 197, in create
    return self.input.serialize(*args, **kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\messages\soap.py", line 64, in serialize
    self.body.render(body, body_value)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\types\complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\elements\element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "C:\Python27\lib\site-packages\zeep\xsd\types\simple.py", line 74, in render
    parent.text = self.xmlvalue(value)
  File "C:\Python27\lib\site-packages\zeep\xsd\types\builtins.py", line 30, in _wrapper
    self.__class__.__name__))
ValueError: The String type doesn't accept collections as value
