### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'microsecond'

### ISSUE THREAD

**Issue by ameniawy** [mvantellingen/python-zeep#540]
1. Zeep version: 2.3 latest with master
2. WSDL = http://37.153.109.99/reseller/ws/?wsdl
3. Script
`
```
from __future__ import unicode_literals

import json
import time
from datetime import date, datetime

from zeep import Client as ZeepClient
from zeep.cache import SqliteCache
from zeep.transports import Transport
from zeep.helpers import serialize_object as zeep_serialize_object

wsdl = 'http://37.153.109.99/reseller/ws/?wsdl'
transport = Transport(cache=SqliteCache())
client = ZeepClient(wsdl=wsdl, transport=transport)
client.set_default_soapheaders({
    "AuthHeader": {
        "ResellerCode": "xx",
        "Username": "xx",
        "Password": "xx"
    }
})

itinerary = {
    "Route": [
        {
            "Origin": {
                "CityID": 2881  # Berlin
            },
            "Destination": {
                "CityID": 4548  # Munich
            },
            "Date": "2017-09-01",
            "TimeWindow": {
                'Mode': "departure",
                'Start': "12:00:00",
                'End': "17:00:00"
            }
        },
        {
            "Origin": {
                "CityID": 2881  # Berlin
            },
            "Destination": {
                "CityID": 4548  # Munich
            },
            "Date": "2017-09-01",
            "TimeWindow": {
                'Mode': "departure",
                'Start': "12:00:00",
                'End': "17:00:00"
            }
        }

    ]
}
passengers = [{
    "Passenger": {
        "PTC": "ADT",
        "Count": 1
    }
}]

filters = []

data = client.service.Air_LowFareSearch(
    Itinerary=itinerary, Passengers=passengers, Filters=filters)
data_serialized = zeep_serialize_object(data)


def myconverter(o):
    if isinstance(o, datetime):
        return o.__str__()


print json.dumps(data_serialized, default=myconverter)
```
`

4. response:
```
`Traceback (most recent call last):
  File "TBSAirService.py", line 69, in <module>
    Itinerary=itinerary, Passengers=passengers, Filters=filters)
  File "/usr/local/lib/python2.7/dist-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/bindings/soap.py", line 110, in send
    options=options)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/definitions.py", line 197, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/messages/soap.py", line 64, in serialize
    self.body.render(body, body_value)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 189, in render
    self._render_value_item(parent, val, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 226, in render
    attribute.render(parent, attr_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/attribute.py", line 33, in render
    value = self.type.xmlvalue(value)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/builtins.py", line 32, in _wrapper
    return func(self, value)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/builtins.py", line 150, in xmlvalue
    if value.microsecond:
AttributeError: 'unicode' object has no attribute 'microsecond'
```
`

**Comment by mvantellingen** [comment]
Should be fixed in master, the issue was that the object expected a time object instead of a string
