### ISSUE TITLE
Zeep fails to parse WSDL

### ISSUE THREAD

**Issue by inchoate** [mvantellingen/python-zeep#542]
Hi,

Great job on Zeep—we're big fans! We're trying to onboard a new user but have two problems. The first is shown in this ticket. (The second is that we're not having any success making authenticated calls against the WS-Security-based services.)

> 1. The version of zeep (or if you are running master the commit hash/date)
```
zeep (2.3.0)
```
The error occurs in both Python2.7 and Python3.6.

> 2. The WSDL you are using

WSDL: ` https://ven.auth.ws.realogyfg.com/AuthenticationService/AuthenticationMgmt.svc?wsdl`

> 3. An example script

```
 python3 -mzeep https://ven.auth.ws.realogyfg.com/AuthenticationService/AuthenticationMgmt.svc?wsdl
```
and the error produced is:
```
Service: AuthenticationManagementService
     Port: OblixEndpoint (Soap11Binding: {http://rfg.realogy.com/Btt/AuthenticationManagement/Services/2009/05}OblixEndpoint)
         Operations:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/vertrees/.virtualenvs/zeep_test/lib/python3.6/site-packages/zeep/__main__.py", line 92, in <module>
    main(args)
  File "/Users/vertrees/.virtualenvs/zeep_test/lib/python3.6/site-packages/zeep/__main__.py", line 87, in main
    client.wsdl.dump()
  File "/Users/vertrees/.virtualenvs/zeep_test/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 128, in dump
    print('%s%s' % (' ' * 12, six.text_type(operation)))
  File "/Users/vertrees/.virtualenvs/zeep_test/lib/python3.6/site-packages/zeep/wsdl/definitions.py", line 191, in __str__
    retval = u'%s(%s)' % (self.name, self.input.signature())
  File "/Users/vertrees/.virtualenvs/zeep_test/lib/python3.6/site-packages/zeep/wsdl/messages/soap.py", line 135, in signature
    parts = [self.body.type.signature(schema=self.wsdl.types, standalone=False)]
AttributeError: 'NoneType' object has no attribute 'type'
```

Thanks for any help!

**Comment by mvantellingen** [comment]
Should be fixed in master
