### ISSUE TITLE
ValueError: Invalid tag name u'$Proxy96ServiceSoapBinding'

### ISSUE THREAD

**Issue by flashhacker** [mvantellingen/python-zeep#544]
Hi,
1. zeep version: 2.3.0
2. WSDL file:
- https://gist.github.com/flashhacker/0717b324593566b0c61f8fbb07d03560
- https://gist.github.com/flashhacker/d7143b0f1704e353c8298df60cfd7b8e

3. Example script https://gist.github.com/flashhacker/45153b963605af553d12e8cc53c2b5fc
Problem: https://gist.github.com/flashhacker/a9f8dc7810681b9b115388984b8b3e98

**Comment by flashhacker** [comment]
Strange, because the "suds" module is working correctly. Please help to solve this problem. Thx.

**Comment by mvantellingen** [comment]
Can you provide an example script that i can run. This requires work from my end. Thx.

**Comment by flashhacker** [comment]
> Can you provide an example script that i can run. This requires work from my end. Thx.

Please,
**Example script** https://gist.github.com/flashhacker/45153b963605af553d12e8cc53c2b5fc
```python
from zeep import Client
client = Client('http://localhost/cmdbuild/services/soap/Webservices?wsdl')
```

**Problem**: https://gist.github.com/flashhacker/a9f8dc7810681b9b115388984b8b3e98
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    client = Client('http://localhost/cmdbuild/services/soap/Webservices?wsdl')
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/client.py", line 123, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/wsdl/wsdl.py", line 81, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/wsdl/wsdl.py", line 183, in __init__
    self.bindings = self.parse_binding(doc)
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/wsdl/wsdl.py", line 414, in parse_binding
    binding = binding_class.parse(self, binding_node)
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 231, in parse
    name = qname_attr(xmlelement, 'name', definitions.target_namespace)
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/utils.py", line 13, in qname_attr
    return as_qname(value, node.nsmap, target_namespace)
  File "/home/mak/.local/lib64/python2.7/site-packages/zeep/utils.py", line 39, in as_qname
    return etree.QName(target_namespace, value)
  File "src/lxml/lxml.etree.pyx", line 1831, in lxml.etree.QName.__init__ (src/lxml/lxml.etree.c:62626)
  File "src/lxml/apihelpers.pxi", line 1630, in lxml.etree._tagValidOrRaise (src/lxml/lxml.etree.c:33940)
ValueError: Invalid tag name u'$Proxy96ServiceSoapBinding'


```

**Comment by cesarlvielma** [comment]
Hey There.
Any solution to this issue? I am getting the same problem using 

from zeep import Client
from requests import Session
from zeep.transports import Transport

session = Session()
session.verify = False

client = Client('https://localhost/services/XMSSendTxnService?wsdl')
result = client.service.createXMTransaction()`
