### ISSUE TITLE
signature = security.find(QName(ns.DS, 'Signature')) ===> AttributeError: 'NoneType' object has no attribute 'find'**

### ISSUE THREAD

**Issue by romankolchin** [mvantellingen/python-zeep#562]
I have 2 versions of the same WS. One with ws-security and another one without ws-security.
One that does not use security works fine.
However if I call WS with security zeep generates error:

Traceback (most recent call last):
  File "/my/fcmapi/site/zeep-test.py", line 17, in <module>
    result = client.service.getTaskDetails(100000000132538)
  File "/my/fcmapi/python3/lib/python3.5/site-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/my/fcmapi/python3/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 121, in send
    return self.process_reply(client, operation_obj, response)
  File "/my/fcmapi/python3/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 173, in process_reply
    client.wsse.verify(doc)
  File "/my/fcmapi/python3/lib/python3.5/site-packages/zeep/wsse/signature.py", line 62, in verify
    _verify_envelope_with_key(envelope, key)
  **File "/my/fcmapi/python3/lib/python3.5/site-packages/zeep/wsse/signature.py", line 235, in _verify_envelope_with_key
    signature = security.find(QName(ns.DS, 'Signature'))
AttributeError: 'NoneType' object has no attribute 'find'**

I use wsse.Signature() to authenticate my requests. 
Is this issue with zeep or with my configuration?

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.

**Comment by gibsonxavier** [comment]
Hi, it seems I have a similar issue.
Any help would be appreciated.
Thanks.
