### ISSUE TITLE
KeyError: 'http://schemas.xmlsoap.org/soap/encoding/'

### ISSUE THREAD

**Issue by Nicd** [mvantellingen/python-zeep#58]
I'm trying to parse this file: https://gw.anionline.com/transactiongateway-v1.2/messaging.asmx?WSDL

The parsing crashes with a KeyError. Here's the whole output:

```
$ python -mzeep 'https://gw.anionline.com/transactiongateway-v1.2/messaging.asmx?WSDL'
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nicd/.../virtualenv/lib/python3.5/site-packages/zeep/__main__.py", line 73, in <module>
    main(args)
  File "/Users/nicd/.../virtualenv/lib/python3.5/site-packages/zeep/__main__.py", line 62, in main
    client = Client(args.wsdl_file, transport=transport)
  File "/Users/nicd/.../virtualenv/lib/python3.5/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/Users/nicd/.../virtualenv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 58, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/Users/nicd/.../virtualenv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 148, in __init__
    self.schema = self.parse_types(doc)
  File "/Users/nicd/.../virtualenv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 316, in parse_types
    import_node.set('schemaLocation', schema_ns[namespace])
KeyError: 'http://schemas.xmlsoap.org/soap/encoding/'
```

I tried with the latest master. Is this a bug in zeep or the WSDL file? I'm not experienced in WSDL so I can't tell if it looks valid.

**Comment by mvantellingen** [comment]
Seems like a bug in zeep. I'll look at it asap

**Comment by mvantellingen** [comment]
fixed!
