### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by vchernat** [mvantellingen/python-zeep#615]
Is it possible to force zeep to use TLS 1.2 instead of sslv3?

1. zeep version  2.4.0
2. https://service.bloomberg.com/assets/dl/dlws.wsdl
3. An example script

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dlws.bloomberg.com
Traceback (most recent call last):
  File "/opt/anaconda3/anaconda/lib/python3.5/site-packages/urllib3/contrib/pyopenssl.py", line 441, in wrap_socket
    cnx.do_handshake()
  File "/opt/anaconda3/anaconda/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1716, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/opt/anaconda3/anaconda/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1456, in _raise_ssl_error
    _raise_current_error()
  File "/opt/anaconda3/anaconda/lib/python3.5/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]

Getting an error:
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",)

when connecting to Bloomberg via zeep.

*** See script below: ***

 wsdl_url = 'https://service.bloomberg.com/assets/dl/dlws.wsdl'
    key_filename = "cert.key.pem"
    cert_filename = "cert.crt.pem"

    context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
    context.options |= ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1
    # Returns a named tuple with paths to OpenSSL’s default cafile and capath.
    ssl.get_default_verify_paths()

    session = Session()

    transport = Transport(session=session, timeout=10)  # default timeout is 300 seconds
    client = Client(wsdl_url, transport=transport, wsse=Signature(key_filename, cert_filename))
    print('Connected to Bloomberg via %s' % wsdl_url)

    alt_service = client.bind(service_name='PerSecurityWS', port_name='PerSecurityWSPort')

    ns0_DateRange = client.get_type('ns0:DateRange')
    ns0_Period = client.get_type('ns0:Period')

    # get the type factory and use it to construct Web Service arguments
    factory = client.type_factory('ns0')
    dt_start = datetime.datetime.strptime('24052010', "%d%m%Y").date()
    dt_end = datetime.datetime.strptime('24052011', "%d%m%Y").date()
    period = factory.Period(start=dt_start, end=dt_end)
    date_range = factory.DateRange(period=period)
    quotesHeaders = factory.QuotesHeaders(daterange=date_range)

    # list operations and data types exposed by web services - useful for learning the API
    # client.wsdl.dump()

    imnt = factory.Instrument(id='AGG US',
                              type=factory.InstrumentType('TICKER'),
                              yellowkey=factory.MarketSector('EQUITY'))
    instruments = factory.Instruments(instrument=[imnt])

    # response {statusCode: ns0:ResponseStatus, requestId: xsd:string, responseId: xsd:string}
    response = client.service.submitGetQuotesRequest(headers=quotesHeaders, instruments=instruments)

**Comment by mvantellingen** [comment]
Zeep by default uses the requests library for http communication. So this should be done via requests, see http://docs.python-zeep.org/en/master/transport.html for information about passing a custom session object

**Comment by jaypavia** [comment]
Hello,

I'm also trying to connect to Bloomberg DLWS via Python Zeep SOAP Client API.

However, I'm getting the following error. I passed the DLWS Cert as part of the request.

SAMPLE CODE:
from requests import Session
from zeep import Client
from zeep.transports import Transport

session = Session()
#session.verify = 'DLWSCert.pem'
session.cert = './DLWSCert.pem'
transport = Transport(session=session)
client = Client(
    'https://service.bloomberg.com/assets/dl/dlws.wsdl',
    transport=transport)

print(client)

ERROR:
Traceback (most recent call last):
  File "test-dlws.py", line 19, in <module>
    transport=transport)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/zeep/client.py", line 62, in __init__
    wsdl, self.transport, settings=self.settings)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 82, in __init__
    document = self._get_xml_document(location)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/zeep/wsdl/wsdl.py", line 143, in _get_xml_document
    location, self.transport, self.location, settings=self.settings)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/zeep/loader.py", line 74, in load_external
    content = transport.load(url)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/zeep/transports.py", line 110, in load
    content = self._load_remote_data(url)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/zeep/transports.py", line 126, in _load_remote_data
    response = self.session.get(url, timeout=self.load_timeout)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/dssproxyadmin/venv/lib/python3.5/site-packages/requests/adapters.py", line 511, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='service.bloomberg.com', port=443): Max retries exceeded with url: /assets/dl/dlws.wsdl (Caused by SSLError(SSLError(336265225, '[SSL] PEM lib (_ssl.c:2846)'),))



Thanks for any assistance.
