### ISSUE TITLE
ValueError: No such operation

### ISSUE THREAD

**Issue by nsimonov** [mvantellingen/python-zeep#632]
zeep 2.4.0
wsdl attached here
[example.zip](https://github.com/mvantellingen/python-zeep/files/1530426/example.zip)

Code:
session = Session()
session.auth = HTTPBasicAuth(login,password)
client = Client(wsdl_url,
    transport=Transport(session=session))
node = client.create_message(client.service, 'si_ao_executionreport', OrderId='123')

I get Error:
C:\Users\nsimonov\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\wsdl.py:329: UserWarning: The wsdl:message for '{http://asapcg.com}xmln.ExecutionReportNtPro_4.3' contains an invalid part ('ExecutionReportNtPro_4.3'): invalid xsd type or elements
  warnings.warn(str(exc))
C:\Users\nsimonov\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\definitions.py:130: UserWarning: The wsdl:operation 'si_ao_executionreport' was not found in the wsdl:portType '{http://asapcg.com}si_ao_executionreport'
  warnings.warn(str(exc))
Traceback (most recent call last):
  File "C:\Users\nsimonov\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\definitions.py", line 146, in get
    return self._operations[key]
KeyError: 'si_ao_executionreport'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.2.4\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.2.4\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/nsimonov/PycharmProjects/test_xml/test_soap.py", line 19, in <module>
    node = client.create_message(client.service, 'si_ao_executionreport', user='hi')
  File "C:\Users\nsimonov\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\client.py", line 226, in create_message
    operation_name, args, kwargs, client=self)
  File "C:\Users\nsimonov\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\bindings\soap.py", line 63, in _create
    operation_obj = self.get(operation)
  File "C:\Users\nsimonov\AppData\Local\Programs\Python\Python35\lib\site-packages\zeep\wsdl\definitions.py", line 148, in get
    raise ValueError("No such operation %r on %s" % (key, self.name))
ValueError: No such operation 'si_ao_executionreport' on {http://asapcg.com}si_ao_executionreportBinding

Why I can't call operation si_ao_executionreport?
Why client doesn't have any operations? dictionary is empty.

**Comment by mvantellingen** [comment]
I'm closing this issue due to the low quality of the initial report. You are welcome to create a new issue but please make sure it contains all the relevant information and that it is properly formatted.

Also please remember that this project is opensource and completely unpaid work.
