### ISSUE TITLE
Behaviour on invalid XML

### ISSUE THREAD

**Issue by goetzk** [mvantellingen/python-zeep#637]
Hi,

I'm using zeep 2.4.0. When I run the code below I was expecting an parsing error of some sort (I see from other issues that Zeep does raise them). 
I'm hoping you can suggest a reason why Keep is raising TransportError rather than a validation error, or if there is more information you need me to supply in order to figure that out.

```
>>> # done once in config
>>> import requests
>>> import zeep
>>> from zeep.transports import Transport
>>> 
>>> import urllib3                                                                                                         
>>> urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning) 
>>> 
>>> from django_otp_vip.settings import VIP_WSDL_USERSERVICES_QUERY, VIP_WSDL_USERSERVICES_AUTH, VIP_WSDL_USERSERVICES_MGMT
>>> from django_otp_vip.settings import VIP_CERTIFICATE_PUBLIC, VIP_CERTIFICATE_PRIVATE
>>> session = requests.Session()
>>> adapter = requests_mock.Adapter()
>>> session.cert = (VIP_CERTIFICATE_PUBLIC, VIP_CERTIFICATE_PRIVATE)  
>>> 
>>> transport = Transport(session=session)
>>> 
>>> query_client = zeep.Client( wsdl=VIP_WSDL_USERSERVICES_QUERY, transport=transport)
>>> VIP_WSDL_USERSERVICES_QUERY
'/Users/kgoetz/otp_experiments/django_otp_vip/wsdls/vipuserservices-query-1.8.wsdl'
>>> 
>>> api_xml = """<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><GetUserInfoResponse xmlns="https://schemas.symantec.com/vip/2011/04/vipuserservices"><requestId>81ee6c6a_91ae_4adc_b6d0_cc01e85e2347</requestId><status>0000</status><statusMessage>Success</statusMessage><userId>karl@kgoetz.id.au</userId><userCreati"""
>>> 
>>> @requests_mock.mock()
... def test_func(api_return, session_override):
...     session_override.post('https://userservices-auth.vip.symantec.com/vipuserservices/QueryService_1_8', text=api_return)
...     api_result = query_client.service.getUserInfo(requestId='adfijrfidjio', userId = 'karl@kgoetz.id.au')
... 
>>> test_func(api_xml)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kgoetz/virtualenvs/otp/lib/python2.7/site-packages/requests_mock/mocker.py", line 223, in inner
    return func(*args, **kwargs)
  File "<console>", line 4, in test_func
  File "/Users/kgoetz/virtualenvs/otp/lib/python2.7/site-packages/zeep/client.py", line 41, in __call__
    self._op_name, args, kwargs)
  File "/Users/kgoetz/virtualenvs/otp/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 121, in send
    return self.process_reply(client, operation_obj, response)
  File "/Users/kgoetz/virtualenvs/otp/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 165, in process_reply
    content=response.content)
TransportError: Server returned HTTP status 200 (<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><GetUserInfoResponse xmlns="https://schemas.symantec.com/vip/2011/04/vipuserservices"><requestId>81ee6c6a_91ae_4adc_b6d0_cc01e85e2347</requestId><status>0000</status><statusMessage>Success</statusMessage><userId>karl@kgoetz.id.au</userId><userCreati)
>>> 
```

If it helps, I can confirm this works if the XML is valid.

```
>>> api_xml = """<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><GetUserInfoResponse xmlns="https://schemas.symantec.com/vip/2011/04/vipuserservices"><requestId>81ee6c6a_91ae_4adc_b6d0_cc01e85e2347</requestId><status>0000</status><statusMessage>Success</statusMessage><userId>karl@kgoetz.id.au</userId><userCreationTime>2017-08-15T01:15:14.555Z</userCreationTime><userStatus>LOCKED</userStatus><numBindings>1</numBindings><credentialBindingDetail><credentialId>SYMC21519954</credentialId><credentialType>STANDARD_OTP</credentialType><credentialStatus>ENABLED</credentialStatus><bindingDetail><bindStatus>ENABLED</bindStatus><friendlyName>nexus</friendlyName><lastBindTime>2017-08-17T02:37:51.909Z</lastBindTime><lastAuthnTime>2017-11-09T02:13:00.022Z</lastAuthnTime><lastAuthnId>7CE4BB604887BEAD</lastAuthnId></bindingDetail></credentialBindingDetail></GetUserInfoResponse></S:Body></S:Envelope>"""
>>> 
>>> @requests_mock.mock()
... def test_func(api_return, session_override):
...     session_override.post('https://userservices-auth.vip.symantec.com/vipuserservices/QueryService_1_8', text=api_return)
...     api_result = query_client.service.getUserInfo(requestId='adfijrfidjio', userId = 'karl@kgoetz.id.au')
...     # assert api_result == 'it will not match this'
...     print api_result
... 
>>> test_func(api_xml)
{
    'requestId': '81ee6c6a_91ae_4adc_b6d0_cc01e85e2347',
    'status': '0000',
    'statusMessage': 'Success',
    'detail': None,
    'detailMessage': None,
    'userId': 'karl@kgoetz.id.au',
    'userCreationTime': datetime.datetime(2017, 8, 15, 1, 15, 14, 555000, tzinfo=<isodate.tzinfo.Utc object at 0x10fed3c90>),
    'userStatus': 'LOCKED',
    'numBindings': 1,
[... and so on ...]
}
```

A couple more issues which seemed to have invalid xml, but I can't be sure if they're actually relevant.
#339
#340

**Comment by goetzk** [comment]
A couple more issues which seemed to have invalid xml, but I can't be sure if they're actually relevant.
https://github.com/mvantellingen/python-zeep/issues/339
https://github.com/mvantellingen/python-zeep/issues/340

**Comment by mvantellingen** [comment]
can you give master a try?

**Comment by goetzk** [comment]
Sorry I missed your request previously - I still haven't upgraded but when I do I'll try and remember to update here.
