### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.w3.org/2005/05/xmlmime

### ISSUE THREAD

**Issue by jdrobinson** [mvantellingen/python-zeep#660]
Hello,

I need some assistance with a script that I'm writing to connect to a SOAP service for Symantec's DLP Incident Report and Updating API (v14.5) - https://support.symantec.com/en_US/article.DOC9264.html

I'm currently running into issues in simply connecting to the API with zeep. It seems that the request is trying to authenticate to "https://www.w3.org/2005/05/xmlmine" which obviously won't work. I've provided code samples along with the errors below.

1. The version of zeep: 2.5
2. The WSDL you are using: https://<server_ip>/ProtectManager/services/v2011/incidents?wsdl (internal)

* Interestingly enough, if I remove the ?wsdl from my calls it appears to authenticate fine.

`
wsdl = 'https://<internal_ip>/ProtectManager/services/v2011/incidents?wsdl'

session = Session()
session.auth = HTTPBasicAuth('username', 'password')
session.verify = False
transport = Transport(session=session)

client = Client(wsdl=wsdl, transport=transport)
`

Doesn't matter what I have after that, because I get the following error in the console:

`
"C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\Scripts\python.exe" "C:/Users/<redacted>/PycharmProjects/DLP Reports/dlp.py"
Traceback (most recent call last):
  File "C:/Users/<redacted>/PycharmProjects/DLP Reports/dlp.py", line 36, in <module>
    client = Client(wsdl=wsdl, transport=transport)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\client.py", line 134, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\wsdl\wsdl.py", line 81, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\wsdl\wsdl.py", line 180, in __init__
    self.parse_types(doc)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\wsdl\wsdl.py", line 313, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\schema.py", line 106, in add_documents
    document = self.create_new_document(node, location)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\schema.py", line 207, in create_new_document
    schema.load(self, node)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\schema.py", line 422, in load
    visitor.visit_schema(node)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\visitor.py", line 137, in visit_schema
    self.process(child, parent=node)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\visitor.py", line 210, in visit_import
    schema = self.schema.create_new_document(schema_node, location)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\schema.py", line 207, in create_new_document
    schema.load(self, node)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\schema.py", line 422, in load
    visitor.visit_schema(node)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\visitor.py", line 137, in visit_schema
    self.process(child, parent=node)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\xsd\visitor.py", line 196, in visit_import
    strict=self.schema.strict)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\loader.py", line 72, in load_external
    content = transport.load(url)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\transports.py", line 110, in load
    content = self._load_remote_data(url)
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\zeep\transports.py", line 126, in _load_remote_data
    response.raise_for_status()
  File "C:\Users\<redacted>\PycharmProjects\DLP Reports\venv\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.w3.org/2005/05/xmlmime

Process finished with exit code 1
`

I am able to successfully connect to the API via SOAPUI and run operations. SOAPUI tells me the WSDL has the following Definition Parts:
- incidents?wsdl
- incidents?xsd=1
- incidents?xsd=2
- xmlmine
- incidents?xsd=3
- incidents?xsd=4
- incidents?xsd=5

I can only assume that there is something going on with that reference to xmlmime definition. Any assistance would be greatly appreciated.

**Comment by smsm1** [comment]
I've come across a similar issue where the main WSDL file is publicly available, but the created service does need the Basic Auth. Thus I've had to use an alternative approach of directly using the requests library, and manually creating the XML with parameters, rather than using a soap library.

**Comment by spencer-hanson** [comment]
It looks like this happens when there are multiple definitions of the same wdsl library, ran into the exact same problem as you @jdrobinson 
I ended up using the SUDS python library, as I'm not super familiar with zeep.

`
import requests
import suds_requests
from suds.client import Client
from suds.xsd.doctor import Import, ImportDoctor

session = requests.Session()
session.verify = False
session.auth = (<username>, <password>)


a = ["https://www.w3.org/2005/05/xmlmime",
"https://<ip>/ProtectManager/services/v2011/incidents?wsdl",
"https://<ip>/ProtectManager/services/v2011/incidents?wsdl=1",
"https://<ip>/ProtectManager/services/v2011/incidents?wsdl=2",
"https://<ip>/ProtectManager/services/v2011/incidents?wsdl=3",
"https://<ip>/ProtectManager/services/v2011/incidents?wsdl=4",
"https://<ip>/ProtectManager/services/v2011/incidents?wsdl=5"]

schema_doctor = ImportDoctor()

for b in a:
    schema_url =  b
    schema_import = Import(schema_url)
    schema_doctor.add(schema_import)



client = Client("https://<ip>/ProtectManager/services/v2011/incidents?wsdl", transport=suds_requests.RequestsTransport(session),
                doctor=schema_doctor)


client.service.incidentList()

`
