### ISSUE TITLE
defusedxml.common.EntitiesForbidden Error while Creating Zeep Client

### ISSUE THREAD

**Issue by adeelehsan** [mvantellingen/python-zeep#670]
I am facing following error while creating Zeep Client
defusedxml.common.EntitiesForbidden: EntitiesForbidden(name='dsig', system_id=None, public_id=None)
Below is detail
Traceback (most recent call last):
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/adeel/Documents/sastaticket/sastaticket-api/sastaticketpk/apps/flights/api/v1/views.py", line 69, in post
    flight_data = SabreProvider.retrieve_itinerary('WOAWWR')
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/celery/app/task.py", line 379, in __call__
    return self.run(*args, **kwargs)
  File "/home/adeel/Documents/sastaticket/sastaticket-providers/providers/sabre/sabre_provider.py", line 121, in retrieve_itinerary
    response = SoapCall(wsdl_url, payload, service, action).execute_request()
  File "/home/adeel/Documents/sastaticket/sastaticket-providers/providers/sabre/api/wrapper_soap.py", line 30, in execute_request
    client = wsdl_client(self.wsdl_url)
  File "/home/adeel/Documents/sastaticket/sastaticket-providers/providers/sabre/api/utils.py", line 31, in wsdl_client
    client = zeep.Client(wsdl=url)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/client.py", line 123, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 81, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 180, in __init__
    self.parse_types(doc)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 307, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 112, in add_documents
    document = self.create_new_document(node, location)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 208, in create_new_document
    schema.load(self, node)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 380, in load
    visitor.visit_schema(node)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 137, in visit_schema
    self.process(child, parent=node)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 210, in visit_import
    schema = self.schema.create_new_document(schema_node, location)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 208, in create_new_document
    schema.load(self, node)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/schema.py", line 380, in load
    visitor.visit_schema(node)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 137, in visit_schema
    self.process(child, parent=node)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 196, in visit_import
    strict=self.schema.strict)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/loader.py", line 73, in load_external
    return parse_xml(content, transport, base_url, strict=strict)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/zeep/loader.py", line 47, in parse_xml
    return fromstring(content, parser=parser, base_url=base_url)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/defusedxml/lxml.py", line 145, in fromstring
    check_docinfo(elementtree, forbid_dtd, forbid_entities)
  File "/home/adeel/Documents/sastaticket/venv/lib/python3.6/site-packages/defusedxml/lxml.py", line 127, in check_docinfo
    None, None, None)
defusedxml.common.EntitiesForbidden: EntitiesForbidden(name='dsig', system_id=None, public_id=None)

**Comment by stephan48** [comment]
This is an issue with defusedxml - or rather a security feature - named forbid_entities. This leads to problems with WSDL/XSD files referencing a xmlsig xsd which apparently uses this feature.

For my testing I added a forbid_entities=False to the fromstring call in loader.py. This lead to a working WSDL. Sadly I could not muster time for now, for a propper fix aka passing this throu the instances. 

Maybe you can test this too and report if it solves your issue?

--stephan

**Comment by mvantellingen** [comment]
I'm working on a settings refactor which should make this easy to optionally disable

**Comment by jasonamyers** [comment]
I hit this exact issue today as well.

**Comment by mvantellingen** [comment]
See https://docs.python-zeep.org/en/master/settings.html
