### ISSUE TITLE
Error parsing the eBay Shopping Service WSDL

### ISSUE THREAD

**Issue by matecsaj** [mvantellingen/python-zeep#683]
1. The version of zeep
2.5.0

2. The WSDL used
http://developer.ebay.com/webservices/latest/ShoppingService.wsdl

3. A command line example
python3 -mzeep http://developer.ebay.com/webservices/latest/ShoppingService.wsdl

4. The result
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/__main__.py", line 92, in <module>
    main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/__main__.py", line 81, in main
    client = Client(args.wsdl_file, transport=transport, strict=strict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/client.py", line 134, in __init__
    self.wsdl = Document(wsdl, self.transport, strict=strict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 81, in __init__
    root_definitions = Definition(self, document, self.location)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 180, in __init__
    self.parse_types(doc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/wsdl/wsdl.py", line 313, in parse_types
    self.types.add_documents(schema_nodes, self.location)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/schema.py", line 106, in add_documents
    document = self.create_new_document(node, location)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/schema.py", line 207, in create_new_document
    schema.load(self, node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/schema.py", line 422, in load
    visitor.visit_schema(node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 137, in visit_schema
    self.process(child, parent=node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 544, in visit_complex_type
    kwargs = self.visit_complex_content(children[0], node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 597, in visit_complex_content
    child, node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 752, in visit_extension_complex_content
    element = self.process(child, node)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 73, in process
    result = visit_func(self, node, parent)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/xsd/visitor.py", line 853, in visit_sequence
    assert child.tag in sub_types, child
AssertionError: <Element {urn:ebay:apis:eBLBaseComponents}CallInfo at 0x1105353c8>

**Comment by jsorah** [comment]
It looks like eBay may have a rogue XML element at line `8415` in their WSDL

Removing this seems to allow zeep to parse it:


```
<CallInfo>
	<CallName>FindHalfProducts</CallName>
	<RequiredInput>No</RequiredInput>
</CallInfo>
```

**Comment by matecsaj** [comment]
Confirmed. Good eye sir! Sincerely, thank you. 

I will make a new issue at eBay and link here.

**Comment by mvantellingen** [comment]
fixed in master
