### ISSUE TITLE
response bug - exception str() - utf-8-decoder(?)

### ISSUE THREAD

**Issue by intence** [mvantellingen/python-zeep#699]
Hi, I think I found a bug in the zeep utf-8 decoder, as i always get following error message:
1. zeep version: 2.5.0
2. WSDL: 
https://gist.github.com/intence/fbde531569b18daf8a28c19cacb9f2f2#file-mywsdl-xml 
3. An example script:
```
from zeep import Client
client = Client('http://127.0.0.0:8081/myAutomationService?wsdl')
client.service.getAvailablePresets()
```
4. Zeep error message:
```
Traceback (most recent call last):
  File "./zeep_test_remote.py", line 9, in <module>
    result = client.service.startProtocol()
  File "C:\Python27\lib\site-packages\zeep\client.py", line 45, in __call__
    self._op_name, args, kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 121, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 186, in process_reply
    return self.process_error(doc, operation)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 291, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: <exception str() failed>
```
5. Wireshark dump:
```
POST /myAutomationService HTTP/1.1
Host: 127.0.0.0:8081
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: Zeep/2.5.0 (www.python-zeep.org)
SOAPAction: ""
Content-Type: text/xml; charset=utf-8
Content-Length: 282

<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:getAvailablePresets xmlns:ns0="http://myservice.de/V16.0"/></soap-env:Body></soap-env:Envelope>HTTP/1.1 500 Internal Server Error
Date: Mon, 26 Feb 2018 15:39:32 GMT
Transfer-encoding: chunked
Content-type: text/xml; charset=utf-8

2da
<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope" xmlns=""><faultcode>S:Server</faultcode><faultstring>Das Ausf..hren der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StatemineInterfaceInit&gt;</faultstring><detail><ns2:myException xmlns:ns2="http://myservice.de/V16.0"><errorId></errorId><localizedMsg>Das Ausf..hren der Funktion ist im aktuellen Zustand nicht erlaubt.</localizedMsg><message>Das Ausf..hren der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StatemineInterfaceInit&gt;</message></ns2:myException></detail></S:Fault></S:Body></S:Envelope>
0
```
The message contains the letter "ü" encoded in utf-8.
> Ausf..hren

The dots represent the bytes 'c3' and 'bc'. So I think there might be a bug in the utf-8 decoder of zeep.

**Comment by mvantellingen** [comment]
Could you provide a runnable test-case as explained on http://docs.python-zeep.org/en/master/reporting_bugs.html#errors-when-parsing-the-response ? That would make it easier for me

**Comment by tobirl** [comment]
The mentioned script does not reproduce the same error:

```
response = pretend.stub(status_code=200, headers={}, content="""<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope" xmlns=""><faultcode>S:Server</faultcode><faultstring>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StateDiagnosticInterfaceInit&gt;</faultstring><detail><ns2:DiagException xmlns:ns2="http://myservice.de/V17.0"><errorId></errorId><localizedMsg>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt.</localizedMsg><message>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StateDiagnosticInterfaceInit&gt;</message></ns2:DiagException></detail></S:Fault></S:Body></S:Envelope>""")

operation = client.service._binding._operations['getAvailablePresets'] result=client.service._binding.process_reply(client, operation, response)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "c:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 168, in process_reply
        content=response.content)

zeep.exceptions.TransportError: Server returned HTTP status 200 (<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope" xmlns=""><faultcode>S:Server</faultcode><faultstring>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StateDiagnosticInterfaceInit&gt;</faultstring><detail><ns2:DiagException xmlns:ns2="http://myservice.de/V17.0"><errorId></errorId><localizedMsg>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt.</localizedMsg><message>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StateDiagnosticInterfaceInit&gt;</message></ns2:DiagException></detail></S:Fault></S:Body></S:Envelope>)
```

The Debugging option gives following Output: 

```
client.service.getAvailablePresets()

zeep.transports: HTTP Post to http://127.0.0.0:8081/myAutomationService:
<?xml version='1.0' encoding='utf-8'?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/"><soap-env:Body><ns0:getAvailablePresets xmlns:ns0="http://myservice.de/V17.0"/></soap-env:Body></soap-env:Envelope>

zeep.transports: HTTP Response from http://127.0.0.0:8081/myAutomationService (status: 500):
<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope" xmlns=""><faultcode>S:Server</faultcode><faultstring>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StatemineInterfaceInit&gt;</faultstring><detail><ns2:myException xmlns:ns2="http://myservice.de/V17.0"><errorId></errorId><localizedMsg>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt.</localizedMsg><message>Das Ausführen der Funktion ist im aktuellen Zustand nicht erlaubt. &lt;StatemineInterfaceInit&gt;</message></ns2:myException></detail></S:Fault></S:Body></S:Envelope>

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\zeep\client.py", line 45, in __call__
    self._op_name, args, kwargs)
  File "c:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 121, in send
    return self.process_reply(client, operation_obj, response)
  File "c:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 186, in process_reply
    return self.process_error(doc, operation)
  File "c:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 291, in process_error
    detail=fault_node.find('detail'))
zeep.exceptions.Fault: <exception str() failed>
```

**Comment by tobirl** [comment]
The problem exists only for Python 2.x, as the wrong encoding for the unicode letter u'ü' is used.
The fix may only work for Python 2.x, so there should be a distinction.
