### ISSUE TITLE
'Choice' object has no attribute 'qname'

### ISSUE THREAD

**Issue by dddtc2005** [mvantellingen/python-zeep#70]
Hi, I'm trying to get some SOAP response using following:

```
...
motype = 'AVGMultiSC@http://schemas.example.com/ma/APP/'
response = soapclient.service.Get(motype, {'imsi':imsi}, _soapheader = sessionid)
...
```

But got following issue:

```
Traceback (most recent call last):
  File "test1.py", line 92, in avgmultisc_get
    response = soapclient.service.Get(motype, {'imsi':imsi}, _soapheader = sessionid)
  File "/usr/lib/python2.7/site-packages/zeep/client.py", line 23, in __call__
    self._proxy._client, self._op_name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 292, in send
    client, self.binding_options, operation, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 96, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 127, in process_reply
    return operation.process_reply(doc)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 252, in process_reply
    return self.output.deserialize(node)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 205, in deserialize
    result.append(part.element.parse(elm, self.wsdl.schema))
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 248, in parse_xmlelement
    result = field.parse(element, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 248, in parse_xmlelement
    result = field.parse(element, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 237, in parse_xmlelement
    while field and field.qname != element.tag:
AttributeError: 'Choice' object has no attribute 'qname'

```

Checked in the xsd and found the below parts that may caused this issue:
```
...
	<!-- GetAVGMultiSC MOId: imsi or impi MOType: AVG@http://schemas.example.com/ma/APP/ -->
	<!-- GetResponseAVGMultiSC -->
	<xs:element name="GetResponseAVGMultiSC">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element name="imsi" type="imsiType" />
					<xs:element name="impi" type="impiType" />
				</xs:choice>
				<xs:element name="avgEncryptedK" type="avgEncryptedKType" />
				<xs:element name="avgA4KeyInd" type="avgA4KeyIndType" />
				<xs:element name="avgFSetInd" type="avgFSetIndType" />
				<xs:element name="avgAmf" type="avgAmfType" />
				<xs:element name="avgEncryptedOPc" type="avgEncryptedOPcType" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="imsi" type="imsiType" use="optional">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="imsiAttr" />
					</xs:appinfo>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="impi" type="impiType" use="optional">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="impiAttr" />
					</xs:appinfo>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>
```

Tried in SOAPUI and it was successful
Attached wsdl/xsd for reference
[wsdl_xsd.zip](https://github.com/mvantellingen/python-zeep/files/311125/wsdl_xsd.zip)

**Comment by c-engelhardt-ecoservice** [comment]
Hi,
I have the same issue with the anyType:

```
Traceback (most recent call last):
  File "soap_connection.py", line 161, in sync_soap_object
    zeep_response = zeep_client.service.GetExamName(ATO_ID=connection.ato_id, ATO_KEY=connection.ato_key)
  File "/usr/lib/python2.7/site-packages/zeep/client.py", line 24, in __call__
    self._proxy._client, self._op_name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/definitions.py", line 298, in send
    client, self.binding_options, operation, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 99, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 134, in process_reply
    doc = operation.process_reply(doc)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/soap.py", line 265, in process_reply
    return self.output.deserialize(node)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/messages.py", line 205, in deserialize
    result.append(part.element.parse(elm, self.wsdl.schema))
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 255, in parse_xmlelement
    result = field.parse(element, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/elements.py", line 128, in parse
    return self.type.parse_xmlelement(value, schema)
  File "/usr/lib/python2.7/site-packages/zeep/xsd/types.py", line 242, in parse_xmlelement
    while field and field.qname != element.tag:
AttributeError: 'Any' object has no attribute 'qname'
```

**Comment by dddtc2005** [comment]
Also, a related issue maybe.

I found that the choice_element has to be included, otherwise it fails.

for example if I use:
```
motype = 'EPSMultiSC@http://schemas.example.com/ma/HSS/'
moid = {'imsi': imsi}
moattr = {'CreateEPSMultiSC': {'imsi': imsi, 'msisdn': msisdn, 'epsProfileId': 'example_profile'}}
mesg = soapclient.service._binding.create_message('Create', motype, moid, moattr, _soapheader=sessionid)
logging.debug('EPSMultiSC Create request for IMSI %s: ', imsi)
logging.debug(etree.tostring(mesg, pretty_print=True))

```

Then I got the following errors:
```
Traceback (most recent call last):
  File "test1.py", line 100, in epsmultisc_create
    mesg = soapclient.service._binding.create_message('Create', motype, moid, moattr, _soapheader=sessionid)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/wsdl/soap.py", line 56, in create_message
    serialized = operation.create(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/wsdl/definitions.py", line 245, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/wsdl/messages.py", line 74, in serialize
    self.body.render(body, body_value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/elements.py", line 127, in render
    return self.type.render(node, value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/types.py", line 172, in render
    element.render(parent, sub_value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/elements.py", line 127, in render
    return self.type.render(node, value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/types.py", line 172, in render
    element.render(parent, sub_value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/elements.py", line 127, in render
    return self.type.render(node, value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/types.py", line 169, in render
    element.render(parent, name, value)
  File "/usr/lib/python2.7/site-packages/zeep-0.9.0.dev0-py2.7.egg/zeep/xsd/elements.py", line 221, in render
    choice_value = item.values.get(choice_element.name)
AttributeError: 'list' object has no attribute 'get'

```

But if I include all the choice_element into the request, then it can be passed correctly.
```
moattr = {'CreateEPSMultiSC': {'imsi': imsi, 'msisdn': msisdn, 'epsProfileId': 'HSS-EsmProfile_Default', 'epsExtendedAccessRestriction': '32', 'commonMsisdn': msisdn}}
```

And in the xsd it defines the two choice_element as:
```
<xs:element name="CreateEPSMultiSC">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="imsi" type="imsiType"/>
				<xs:element minOccurs="0" name="msisdn" type="msisdnType"/>
				<xs:element minOccurs="0" name="associationId" type="associationIdType"/>
				<xs:element name="epsProfileId" type="epsProfileIdType"/>
				<xs:element minOccurs="0" name="epsOdb" type="epsOdbType"/>
				<xs:element minOccurs="0" name="epsRoamingAllowed" type="epsRoamingAllowedType"/>
				<xs:element minOccurs="0" name="epsIndividualApnOperatorIdentifierReplacement" type="epsIndividualApnOperatorIdentifierReplacementType"/>
				<xs:element minOccurs="0" name="epsIndividualDefaultContextId" type="epsIndividualDefaultContextIdType"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="epsIndividualContextId" type="epsIndividualContextIdType"/>
				<xs:element minOccurs="0" name="epsIndividualSubscribedChargingCharacteristic" type="epsIndividualSubscribedChargingCharacteristicType"/>
				<xs:element minOccurs="0" name="epsIndividualAmbrMaximalUplinkIpFlow" type="epsIndividualAmbrMaximalUplinkIpFlowType"/>
				<xs:element minOccurs="0" name="epsIndividualAmbrMaximalDownlinkIpFlow" type="epsIndividualAmbrMaximalDownlinkIpFlowType"/>
				<xs:element minOccurs="0" name="epsIndividualRatFrequencyPriorityId" type="epsIndividualRatFrequencyPriorityIdType"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="epsIndividualMappingContextId" type="epsIndividualMappingContextIdType"/>
				<xs:element minOccurs="0" name="epsRoamingRestriction" type="epsRoamingRestrictionType"/>
				
				<xs:choice minOccurs="0">
					<xs:element name="epsAccessRestriction" type="epsAccessRestrictionType"/>
					<xs:element name="epsExtendedAccessRestriction" type="epsExtendedAccessRestrictionType"/>
				</xs:choice>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="epsUserIpV4Address" type="epsUserIpV4AddressType"/>
				<xs:element maxOccurs="unbounded" minOccurs="0" name="epsUserIpV6Address" type="epsUserIpV6AddressType"/>
				<xs:element minOccurs="0" name="epsTenantId" type="epsTenantIdType"/>
				<xs:element minOccurs="0" name="epsSessionTransferNumber" type="epsSessionTransferNumberType"/>
				<xs:element minOccurs="0" name="epsMultimediaPriorityService" type="epsMultimediaPriorityServiceType"/>
				<xs:element minOccurs="0" name="epsZoneCodeSetId" type="epsZoneCodeSetIdType"/>
				<xs:choice minOccurs="0">
					<xs:element name="epsCommonMsisdn" nillable="true" type="epsCommonMsisdnType"/>
					<xs:element name="commonMsisdn" nillable="true" type="epsCommonMsisdnType"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="imsi" type="imsiType" use="required">
				<xs:annotation>
					<xs:appinfo>
						<jaxb:property name="imsiAttr"/>
					</xs:appinfo>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
		<xs:key name="key_imsi">
			<xs:selector xpath="./x:imsi"/>
			<xs:field xpath="."/>
		</xs:key>
		<xs:keyref name="keyref_imsi" refer="key_imsi">
			<xs:selector xpath="."/>
			<xs:field xpath="@imsi"/>
		</xs:keyref>
	</xs:element>
```

The xsd and wsdl already attached above

**Comment by mvantellingen** [comment]
Thanks, I didn't give the parsing of any and choice elements as much attention as the serializing of the values to xml. I'll dive into this asap.

**Comment by mvantellingen** [comment]
hi @dddtc2005, can you give the master branch a try? I've just refactored the logic to parse choice elements.

@c-engelhardt-ecoservice can you open a new issue for this and include an example?

**Comment by mvantellingen** [comment]
@dddtc2005 If the second issue is not solved with this, can you then open a separate issue for this? Bit hard for me to keep track of the issues if various different problems are lumped together in one issue

Thanks!

**Comment by dddtc2005** [comment]
Thanks! Verified the first issue and it's now working. The second one I've opened a new issue, please take a look here: [#74](https://github.com/mvantellingen/python-zeep/issues/74)

Thanks for the great work :)

**Comment by c-engelhardt-ecoservice** [comment]
Sure! You can find it here: [#75](https://github.com/mvantellingen/python-zeep/issues/75)
