### ISSUE TITLE
Builtin type Base64Binary does not work in Python 3

### ISSUE THREAD

**Issue by aisopuro** [mvantellingen/python-zeep#736]
Thanks for taking the time to report an issue!

Since Zeep is a module I've created and currently maintain mostly in my spare
time I need as much information as possible to quickly analyze/fix issues.

Please provide the following information:

1. The version of zeep (or if you are running master the commit hash/date)
2. The WSDL you are using
3. An example script

Also please don't paste WSDL/XSD file contents directly into the issue since 
that makes it hard to read, instead please create a gist at 
https://gist.github.com and link that here.

Please see http://docs.python-zeep.org/en/master/reporting_bugs.html for 
more information.

Python version: 3.5.3
Zeep version: 2.5.0

Using the Maventa WSDL, which has been tested to work in suds: https://testing.maventa.com/apis/v1.1/wsdl

Example script:

```
from zeep import Client
client = Client('https://testing.maventa.com/apis/v1.1/wsdl')
FINVOICE_STR = "A string that is supposed to be a Finvoice xml document"
result = client.service.invoice_put_finvoice(
     dict(
         vendor_api_key='API_KEY',
         user_api_key='USER_KEY',
         company_uuid='COMPANY'),
     finvoice_in=dict(
         files=dict(items=[FINVOICE_STR]),
         filenames=dict(items=['finvoice.xml'])))
```
You do not need to provide actual correct values for `vendor_api_key` etc: the script will fail before authentiation takes place.

The exception raised:
```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/client.py", line 45, in __call__
    self._op_name, args, kwargs)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 110, in send
    options=options)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 197, in create
    return self.input.serialize(*args, **kwargs)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 64, in serialize
    self.body.render(body, body_value)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 126, in render
    self._render_value_item(node, val, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 150, in _render_value_item
    self.restrict.render(parent, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/simple.py", line 74, in render
    parent.text = self.xmlvalue(value)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/builtins.py", line 32, in _wrapper
    return func(self, value)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/builtins.py", line 318, in xmlvalue
    return base64.b64encode(value)
  File "/usr/lib/python3.5/base64.py", line 59, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
TypeError: a bytes-like object is required, not 'str'
```
If we change `FINVOICE_STR` to be `bytes`, this exception is raised instead:
```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/client.py", line 45, in __call__
    self._op_name, args, kwargs)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 110, in send
    options=options)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/definitions.py", line 197, in create
    return self.input.serialize(*args, **kwargs)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/wsdl/messages/soap.py", line 64, in serialize
    self.body.render(body, body_value)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 117, in render
    self.validate(value, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 170, in validate
    self._validate_item(val, render_path)
  File "/var/lib/odoo/.local/lib/python3.5/site-packages/zeep/xsd/elements/any.py", line 197, in _validate_item
    "See http://docs.python-zeep.org/en/master/datastructures.html"
TypeError: Any element received object of type 'bytes', expected lxml.etree._Element or builtins.dict or builtins.str
See http://docs.python-zeep.org/en/master/datastructures.html#any-objects for more information
```

Research:
The `files` element is supposed to be an array of `base64`-encoded xml-files. I traced the problem to the `Base64Binary` definition in `xsd/types/builtins.py`:
```
class Base64Binary(BuiltinType, AnySimpleType):
    accepted_types = six.string_types
    _default_qname = xsd_ns('base64Binary')

    @check_no_collection
    def xmlvalue(self, value):
        return base64.b64encode(value)

    def pythonvalue(self, value):
        return base64.b64decode(value)
```
There's no handling of how `base64` has changed in Python 3, so I tried making the following change:
```
class Base64Binary(BuiltinType, AnySimpleType):
    accepted_types = six.string_types
    _default_qname = xsd_ns('base64Binary')

    @check_no_collection
    def xmlvalue(self, value):
        if six.PY3:
            value = value.encode('utf-8')
        return base64.b64encode(value)

    def pythonvalue(self, value):
        result = base64.b64decode(value)
        if six.PY3:
            result = result.decode('utf-8')
        return result
```
However, that only lead to Maventa returning an internal server error, which makes me suspect that the Zeep pipeline can't handle Python 3 `bytes` if they occur as an element value. I'm not sure what the best way would be to fix this.

**Comment by rphlo** [comment]
Having `accepted_types = (six.binary_type, )` in `Base64Binary` solves the issue for me.

**Comment by petroswork** [comment]
Version 3.1.0 seems to work. Did you try sending the file as binary data (`open(, 'rb').read()`) ?

**Comment by aisopuro** [comment]
I'm not sure anymore @petroswork (sorry, it's been a while), but I mention before the second traceback
> If we change `FINVOICE_STR` to be `bytes`, this exception is raised instead:

Is that what you meant? I believe `open(, 'rb').read()` returns a `bytes` object in Python 3, right?

**Comment by petroswork** [comment]
Yes. Anyway, it works here for type `base64Binary` using zeep 3.1.0 and python 3.6.5.
