### ISSUE TITLE
sometimes crashes when the WSDL has no port binding options

### ISSUE THREAD

**Issue by matecsaj** [mvantellingen/python-zeep#742]
1. The version of zeep (or if you are running master the commit hash/date)
2.5.0

2. The WSDL you are using
http://developer.ebay.com/webservices/Finding/latest/FindingService.wsdl

3. An example script

from zeep import Client
client = Client('http://developer.ebay.com/webservices/Finding/latest/FindingService.wsdl')
print(client.namespaces)
print(client.service)

4. The first print is fine.

{'xsd': 'http://www.w3.org/2001/XMLSchema', 'ns0': 'http://www.ebay.com/marketplace/search/v1/services'}

5. The second print crashes.

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/matecsaj/Library/Preferences/PyCharm2018.1/scratches/scratch_1.py", line 5, in <module>
    print(client.service)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/client.py", line 163, in service
    port_name=self._default_port_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/zeep/client.py", line 217, in bind
    return ServiceProxy(self, port.binding, **port.binding_options)
TypeError: type object argument after ** must be a mapping, not NoneType

**Comment by mvantellingen** [comment]
The issues is actually that the wsdl specifies the address as soap 1.2 node while everything else is soap 1.1. I consider this a bug on the ebay side. 

i hate soap :-)

**Comment by matecsaj** [comment]
Got it. Thanks. Please close the issue.
