### ISSUE TITLE
Signature Verification Failed

### ISSUE THREAD

**Issue by tomerazran** [mvantellingen/python-zeep#814]
Hello,

We are working with zeep 3.1.0 with python 2.7.5 on RHEL 7.3.
We are trying to use WSSE signature with zeep client.
The client is signing the soap envelope with a key pair, and we get a correct answer.
The problem is that the server is signing the soap response with SecurityTokenReference=X509SubjectKeyIdentifier and the client fails to verify the signature.

We get the following exception:

Traceback (most recent call last):
  File "/tmp/test.py", line 23, in <module>
    resp = client.service.Alive()
  File "/usr/lib/python2.7/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/bindings/soap.py", line 184, in process_reply
    client.wsse.verify(doc)
  File "/usr/lib/python2.7/site-packages/zeep/wsse/signature.py", line 63, in verify
    _verify_envelope_with_key(envelope, key)
  File "/usr/lib/python2.7/site-packages/zeep/wsse/signature.py", line 269, in _verify_envelope_with_key
    raise SignatureVerificationFailed()
zeep.exceptions.SignatureVerificationFailed

I have few issues:
1) Does zeep client support the X509SubjectKeyIdentifier? If yes - where do I have to configure the public certificate?
2) I also try to validate the xml document using xmlsec1 --verify command which fails - is that relate?

I'm not able to expose the WSDL and response XML due to security issues.

Tomer.

**Comment by tomerazran** [comment]
I found the problem. The problem is that the web service sign the response using a different certificate. 
I added support for this scenario in pull request #822
