### ISSUE TITLE
Does it support InDesign Server SOAP?

### ISSUE THREAD

**Issue by lohriialo** [mvantellingen/python-zeep#819]
I'm giving a shot trying to call InDesign Server SOAP but running into error 

1.  **zeep:** **3.1.0**
2. **The WSDL:** [InDesign Server SOAP wsdl](https://gist.github.com/lohriialo/5615ca5aa14fb08ed0089697ec7c447e)
3. **Code snippet:**

```
import zeep

# InDesign Server soap running on port 12345
wsdl = 'http://localhost:12345/service?wsdl'
client = zeep.Client(wsdl=wsdl)
body = """
        <?xml version="1.0" encoding="UTF-8"?>
        <SOAP-ENV:Envelope 
            xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" 
            xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" 
            xmlns:IDSP="http://ns.adobe.com/InDesign/soap/">
            <SOAP-ENV:Body>
                <IDSP:RunScript>
                    <IDSP:runScriptParameters>
                        <IDSP:scriptText></IDSP:scriptText>
                        <IDSP:scriptLanguage>javascript</IDSP:scriptLanguage>
                        <IDSP:scriptFile>/Users/username/Desktop/test.jsx</IDSP:scriptFile>
                        <IDSP:scriptArgs>
                            <IDSP:name>arg0</IDSP:name>
                            <IDSP:value>88</IDSP:value>
                        </IDSP:scriptArgs>
                        <IDSP:scriptArgs>
                            <IDSP:name>arg1</IDSP:name>
                            <IDSP:value>some text</IDSP:value>
                        </IDSP:scriptArgs>
                    </IDSP:runScriptParameters>
                </IDSP:RunScript>
            </SOAP-ENV:Body>
        </SOAP-ENV:Envelope>
        """
client.service.RunScript(body)
```
When I made the above soap call, i get the following error

```
/Users/username/PycharmProjects/soap-ids-python/env/bin/python /Users/username/PycharmProjects/soap-ids-python/app.py
Traceback (most recent call last):
  File "/Users/username/PycharmProjects/soap-ids-python/app.py", line 32, in <module>
    client.service.RunScript(body)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 121, in send
    options=options)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/wsdl/definitions.py", line 200, in create
    return self.input.serialize(*args, **kwargs)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/wsdl/messages/soap.py", line 65, in serialize
    self.body.render(body, body_value)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/elements/element.py", line 191, in render
    self._render_value_item(parent, value, render_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/elements/element.py", line 215, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/Users/username/PycharmProjects/soap-ids-python/env/lib/python3.6/site-packages/zeep/xsd/elements/indicators.py", line 228, in render
    element_value = value[name]
TypeError: string indices must be integers
```
I have created InDesign Server WSDL gist here for more clarity of the WSDL: https://gist.github.com/lohriialo/5615ca5aa14fb08ed0089697ec7c447e

More details about InDesign Server SOAP can be found [here](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/indesign/sdk/cs6/server/ids-solutions.pdf)

**Comment by meeuw** [comment]
Given your example I'd use the following:
```python
from zeep import Client

client = Client('http://localhost:12345?wsdl')

RunScriptParameters = client.get_type('ns0:RunScriptParameters')
IDSP_ScriptArg = client.get_type('ns0:IDSP-ScriptArg')

factory = client.type_factory('ns0')

a = IDSP_ScriptArg("arg1", "some text")
p = RunScriptParameters("", "javascript", "", [a])
result = client.service.RunScript(p)
print(result)
```

**Comment by lohriialo** [comment]
This works perfectly!
