### ISSUE TITLE
AssertionError: <Element(name=u'arg0', type=None)> has no name

### ISSUE THREAD

**Issue by a42niem** [mvantellingen/python-zeep#85]
Hi,
I like to use zeep for http://test.idempiere.com/ADInterface/services/compositeInterface?wsdl
When I  run `client.wsdl.dump()` it shows me _Prefixes_ and _Global elements_ and _Global types_ but then _Service_ results in:

> Service: compositeInterface
>      Port: CompositeServiceImplPort (Soap11Binding)
>          Operations:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/zeep-0.10.0.dev0-py2.7.egg/zeep/wsdl/wsdl.py", line 102, in dump
>     print('%s%s' % (' ' * 12, six.text_type(operation)))
>   File "/usr/local/lib/python2.7/dist-packages/zeep-0.10.0.dev0-py2.7.egg/zeep/wsdl/definitions.py", line 239, in __str__
>     retval = u'%s(%s)' % (self.name, self.input.signature())
>   File "/usr/local/lib/python2.7/dist-packages/zeep-0.10.0.dev0-py2.7.egg/zeep/wsdl/messages.py", line 45, in signature
>     result = self.body.type.signature()
>   File "/usr/local/lib/python2.7/dist-packages/zeep-0.10.0.dev0-py2.7.egg/zeep/xsd/types.py", line 206, in signature
>     part = element.signature(name)
>   File "/usr/local/lib/python2.7/dist-packages/zeep-0.10.0.dev0-py2.7.egg/zeep/xsd/elements.py", line 104, in signature
>     assert self.type, '%r has no name' % self
> AssertionError: `<Element(name=u'arg0', type=None)>` has no name

Any idea?
Regards,
Dirk Niemeyer

**Comment by a42niem** [comment]
Problem is solved.
Verified also with http://test.idempiere.com/ADInterface/services/ModelADService?wsdl
Thank you!
