### ISSUE TITLE
zeep SOAP authentication with IPAWS service - advice asked.

### ISSUE THREAD

**Issue by jjbunn** [mvantellingen/python-zeep#850]
Using zeep version 3.1.0, I am trying to interact with the SOAP service at:

https://ipaws-open.net/IPAWS_CAPService/IPAWS?wsdl

My initial goal is to submit a "getACK" SOAP request to this service, but I'm having some problems, described below.

Here is the code I'm using:

    url = "https://ipaws-open.net/IPAWS_CAPService/IPAWS?wsdl"
    settings = Settings(strict=False, xml_huge_tree=True)
    session = Session()
    session.cert = "mycert.pem"
    session.verify = "mycert.pem"
    transport = Transport(session=session, timeout=30)
    client = Client(wsdl=url, transport=transport, settings=settings)

    print client.service._binding_options
    client.service._binding_options['address'] = url
    cap_header = client.get_element('ns3:CAPHeaderTypeDef')
    header_value = cap_header(logonUser='myusername', logonCogId='123456')
    result = client.service.getRequest(requestAPI='REQUEST1', requestOperation='getACK', parameters=[None],  _soapheaders=[header_value])

The output from running this is:

```
{'address': 'https://ipawssoa01:8005/IPAWS_CAPService/IPAWS'}
Traceback (most recent call last):
  File "D:\Dropbox\Applications\PyIPAWS\test.py", line 187, in <module>
    main()
  File "D:\Dropbox\Applications\PyIPAWS\test.py", line 180, in main
    result = client.service.getRequest(requestAPI='REQUEST1', requestOperation='getACK', parameters=[None],  _soapheaders=[header_value])
  File "C:\Python27\lib\site-packages\zeep\proxy.py", line 42, in __call__
    self._op_name, args, kwargs)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 132, in send
    return self.process_reply(client, operation_obj, response)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 194, in process_reply
    return self.process_error(doc, operation)
  File "C:\Python27\lib\site-packages\zeep\wsdl\bindings\soap.py", line 288, in process_error
    detail=etree_to_string(doc))
zeep.exceptions.Fault: Unknown fault occured
```

If I ask for the raw response, using client.settings.raw_response = True, then the result is:

`<Response [500]>`

If I do not change the 'address' from ipawssoa01 to the original url, there is a requests error as it tries to connect to a nonexistant server:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ipawssoa01', port=8005): Max retries exceeded with url: /IPAWS_CAPService/IPAWS (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03B58190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))`

I feel like I'm doing something (or several things!) wrong here, so would really appreciate some help or pointers!

Thanks for all your work on zeep :-)

**Comment by mvantellingen** [comment]
That is a DNS error. The WSDL / XSD probably refers to a domain which no longer exists.

**Comment by gnishad9573** [comment]
from requests.auth import HTTPBasicAuth  # or HTTPDigestAuth, or OAuth1, etc.
from requests import Session
from zeep import Client
from zeep.transports import Transport
session = Session()
username = "ABGPLANET\ONEHRPORTAL"
password = "portal@1234"
url = "http://10.1.207.29:8111/PSIGW/PeopleSoftServiceListeningConnector/PSFT_HR/CI_Z_SP_PERS_DTL_CI.1.wsdl"
session.auth = HTTPBasicAuth(username, password)
client = Client(url,transport=Transport(session=session))
print(client.service.CI_Z_SP_PERS_DTL_CI_G("001670"))

I am getting this error

  self._op_name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/bindings/soap.py", line 121, in send
    options=options)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/bindings/soap.py", line 68, in _create
    serialized = operation_obj.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/definitions.py", line 200, in create
    return self.input.serialize(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/zeep/wsdl/messages/soap.py", line 78, in serialize
    self.body.render(body, body_value)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 203, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 227, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 253, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/indicators.py", line 241, in render
    element.render(parent, element_value, child_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 203, in render
    self._render_value_item(parent, value, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/elements/element.py", line 227, in _render_value_item
    return self.type.render(node, value, None, render_path)
  File "/usr/local/lib/python2.7/dist-packages/zeep/xsd/types/complex.py", line 234, in render
    element.type.render(parent, value, None, child_path)
UnboundLocalError: local variable 'child_path' referenced before assignment
