### ISSUE TITLE
FileNotFound in SOAP request

### ISSUE THREAD

**Issue by freitasdfb** [mvantellingen/python-zeep#915]
Hi,

I'm trying to do a soap request in my website.

The website has a ssl security. I'm setting the verification var to False to make this easily.

But i'm giving this error: 

> requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

This is my code:

```
from requests import Session
from zeep import Client
from zeep.transports import Transport



session = Session()
session.verify = False

transport = Transport(session=session)

req_data = { 'host':'myhost',
        'user':'qware',
        'password':'mypass'
}

wsdl = 'https://mywebsite.pix.com.br/QWWS/QWServiceActions?wsdl'
client = Client(wsdl=wsdl, transport=transport)

print(client.service.getListQWService(**req_data))
```

And this the trace, if a can say this kk

> Traceback (most recent call last):
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\requests\adapters.py", line 449, in send
>     timeout=timeout
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\util\retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
>     self._validate_conn(conn)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
>     conn.connect()
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\connection.py", line 344, in connect
>     ssl_context=context)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\urllib3\util\ssl_.py", line 344, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "d:\python\Lib\ssl.py", line 412, in wrap_socket
>     session=session
>   File "d:\python\Lib\ssl.py", line 853, in _create
>     self.do_handshake()
>   File "d:\python\Lib\ssl.py", line 1117, in do_handshake
>     self._sslobj.do_handshake()
> urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "TestFile.py", line 20, in <module>
>     print(client.service.getListQWService(**req_data))
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\zeep\proxy.py", line 42, in __call__
>     self._op_name, args, kwargs)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\zeep\wsdl\bindings\soap.py", line 124, in send
>     options['address'], envelope, http_headers)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\zeep\transports.py", line 95, in post_xml
>     return self.post(address, message, headers)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\zeep\transports.py", line 67, in post
>     timeout=self.operation_timeout)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\requests\sessions.py", line 581, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\requests\sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\requests\sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "H:\webworkspace\env_pymonitor\lib\site-packages\requests\adapters.py", line 498, in send
>     raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
> 

Someone can help me ?

**Comment by celsowm** [comment]
having the same problem
