### ISSUE TITLE
zeep.exceptions.XMLParseError: No such type:

### ISSUE THREAD

**Issue by Tset-Noitamotua** [mvantellingen/python-zeep#96]
```batch
(ZEEP) user@host C:\_GITHUB\python-zeep-master
$ pip freeze requirements.txt
appdirs==1.4.0
defusedxml==0.4.1
isodate==0.5.4
lxml==3.6.0
pytz==2016.4
requests==2.10.0
six==1.10.0
zeep==0.11.0.dev0
```

```batch
(ZEEP) user@host C:\_GITHUB\python-zeep-master
$ python
Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from zeep import Client
>>> url = 'http://subdomain.company.com/fb/service_name/sc/foobar/wsdl/com/company/bpm/foo/bar/foobar.wsdl'
>>> client = Client(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\client.py", line 48, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 62, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 140, in __init__
    self.parse_imports(doc)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 232, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 142, in __init__
    self.types = self.parse_types(doc)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 284, in parse_types
    self.wsdl._parser_context)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 28, in __init__
    node, transport, location, self._parser_context, location)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 146, in __init__
    visitor.visit_schema(node)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 95, in visit_schema
    self.process(node, parent=parent)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 221, in visit_element
    xsd_type = self.process(child, node)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 380, in visit_complex_type
    item = self.process(child, node)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 630, in visit_sequence

    item = self.process(child, node)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 226, in visit_element
    xsd_type = self._get_type(node_type.text)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 795, in _get_type
    retval = self.schema.get_type(name, default=None)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 203, in get_type
    return self._imports[name.namespace].get_type(name)
  File "C:\Users\user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 210, in get_type
    name.text, self, ', '.join(self._types)))
zeep.exceptions.XMLParseError: No such type: u'{http://com/company/bp/name/fb}FooBarInput' in <SchemaDocument(location='http://subdomain.company.com/fb/service_name/sc/service_name/wsdl/com/company/bp/name/fb/ServiceFault.xsd', tns='http://com/company/bp/name/fb', is_empty=False)> (Only have {http://com/company/bp/name/bf}ServiceFault)
>>>
```

**Note**: I can´t provide the wsdl file, also all urls in above stacktrace are anonymized.

This issue could be related to #79

**Comment by mvantellingen** [comment]
Could you give the master branch a try?

**Comment by Tset-Noitamotua** [comment]
At first attempt nothing happend and I had to interrupt:

```cmd
>>> client = Client(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\client.py", line 48, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 139, in __init__
    self.parse_imports(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 231, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 141, in __init__
    self.types = self.parse_types(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 283, in parse_types
    self.wsdl._parser_context)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 28, in __init__
    node, transport, location, self._parser_context, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 146, in __init__
    visitor.visit_schema(node)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 95, in visit_schema
    self.process(node, parent=parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 137, in visit_import
    location, self.schema._transport, self.parser_context)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\parser.py", line 41, in load_external
    response = transport.load(url)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\transports.py", line 37, in load
    response = self.session.get(url, timeout=self.timeout)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\requests\sessions.py", line 466, in request
    prep.url, proxies, stream, verify, cert
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\requests\sessions.py", line 626, in merge_environment_settings
    env_proxies = get_environ_proxies(url) or {}
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\requests\utils.py", line 568, in get_environ_proxies
    if should_bypass_proxies(url):
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\requests\utils.py", line 556, in should_bypass_proxies
    bypass = proxy_bypass(netloc)
  File "c:\python27\Lib\urllib.py", line 1601, in proxy_bypass
    return proxy_bypass_registry(host)
  File "c:\python27\Lib\urllib.py", line 1568, in proxy_bypass_registry
    fqdn = socket.getfqdn(rawHost)
  File "c:\python27\Lib\socket.py", line 137, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
KeyboardInterrupt
>>>
KeyboardInterrupt
>>>
```

Second attempt:

```cmd
>>> client = Client(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\client.py", line 48, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 139, in __init__
    self.parse_imports(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 231, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 141, in __init__
    self.types = self.parse_types(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 283, in parse_types
    self.wsdl._parser_context)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 28, in __init__
    node, transport, location, self._parser_context, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 146, in __init__
    visitor.visit_schema(node)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 95, in visit_schema
    self.process(node, parent=parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 221, in visit_element
    xsd_type = self.process(child, node)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 405, in visit_complex_type
    element = self.process(child, node)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 601, in visit_sequence

    item = self.process(child, node)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 42, in process
    result = visit_func(self, node, parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 226, in visit_element
    xsd_type = self._get_type(node_type.text)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 769, in _get_type
    retval = self.schema.get_type(name, default=None)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 204, in get_type
    return self._imports[name.namespace].get_type(name)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.11.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 211, in get_type
    name.text, self, ', '.join(self._types)))
zeep.exceptions.XMLParseError: No such type: u'{http://com/company/bpy/pusemuckel/py}PYpusemuckelSaveDocumentInput' in <SchemaDocument(location='http://sportal.company.com/ws/SCpusemuckel_20111111Web/sca/PYpusemuckel_1234asdf/wsdl/com/company/bpy/pusemuckel/py/PYpusemuckelFault.xsd', tns='http://com/company/bpy/pusemuckel/py', is_empty=False)> (Only have {http://com/company/bpy/pusemuckel/py}PYpusemuckelFault)
>>>
```

If I can help some how else, tell me, I´m glad to help!

**Comment by mvantellingen** [comment]
This might be caused by multiple xsd files which define the same target namespace. I still need to create a check for that. Can you see if that is the case?

**Comment by Tset-Noitamotua** [comment]
Sorry for stupid question but how can I check whether multiple xsd are involved?

**Comment by Tset-Noitamotua** [comment]
as I told in #79 the structur of wsdl looks somewhat like this:

```xml
<wsdl:definitions name="foo_Service" targetNamespace="http://com/company/interfaces/Binding">
    <wsdl:import location="Service.wsdl" namespace="http://com/company/interfaces/"></wsdl:import>
    <wsdl:binding name="fooBinding">...</wsdl:binding>
    <wsdl:service name="fooService">
        <wsdl:port binding="this:fooBinding" name="fooPort">
            <soap:address location="http://blabla">
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
```

Here another anynomized extract from our wsdl:

```xml
<wsdl:types>
      <xsd:schema targetNamespace="http://com/company/interfaces" xmlns:tns="http://com/company/interfaces">
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_RetryXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_RetryXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetDocuXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetDocuXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_MoveXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_MoveXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetLinkXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetLinkXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetDocXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetDocXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_DeleteXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_DeleteXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetDoXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetDoXXXtInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_SaveXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_SaveXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetLiXXXOutput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_GetLiXXXInput.xsd"/>
         <xsd:import namespace="http://com/company/foo" schemaLocation="../foo/bar_Fault.xsd"/>
```

**Comment by mvantellingen** [comment]
Could you give the master branch a try again? I've gone through the import handling one more time and added some better error detection there.

**Comment by Tset-Noitamotua** [comment]
I did. This came out:

```cmd
>>> client = Client(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\client.py", line 52, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 61, in __init__
    root_definitions = Definition(self, document, self.location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 144, in __init__
    self.parse_imports(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 236, in parse_imports
    wsdl = Definition(self.wsdl, document, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 146, in __init__
    self.types = self.parse_types(doc)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\wsdl\wsdl.py", line 288, in parse_types
    self.wsdl._parser_context)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 28, in __init__
    node, transport, location, self._parser_context, location)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\xsd\schema.py", line 148, in __init__
    visitor.visit_schema(node)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 102, in visit_schema
    self.process(node, parent=parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 48, in process
    result = visit_func(self, node, parent)
  File "C:\Users\my_user\Envs\ZEEP\lib\site-packages\zeep-0.12.0.dev0-py2.7.egg\zeep\xsd\visitor.py", line 135, in visit_import
    ) % (location, namespace or '(null)', schema._location))
zeep.exceptions.XMLParseError: Conflicting import of schema located at 'http://subdomain.company.ru/ab/WebService/cde/WebServiceExport/wsdl/ru/company/efg/service/pa/PAserviceGetMaxFileSizeInput.xsd' for the namespace 'http://ru/company/efg/service/pa', since the namespace was already imported with the schema located at 'http://subdomain.company.ru/ab/WebService/cde/WebServiceExport/wsdl/ru/company/efg/service/pa/PAserviceGetMaxFileSizeOutput.xsd'
>>>
```

**Comment by mvantellingen** [comment]
Okay so unfortunately the WSDL seems to be invalid. There are some xsd processors which allow multiple schemas with the same target namespace but libxml2 isn't one of them. For this reason I also chose not to support it so that in the future we can leverage the xml validation in lxml

**Comment by Tset-Noitamotua** [comment]
Too bad :-( Same WSDL works with [suds](https://fedorahosted.org/suds/). But as suds seems to be not maintained any more I wanted to schwich to zeep.
