### ISSUE TITLE
Using zeep in Django with USE_TZ setting causes "can't compare offset-naive and offset-aware datetimes" error

### ISSUE THREAD

**Issue by tkocmathla** [mvantellingen/python-zeep#97]
If I use zeep within a Django application that uses sqlite as the backend, and has the USE_TZ setting enabled, zeep throws a timezone offset-related error. 

The datetime coming back from sqlite is timezone-aware, but the datetime stored in `offset` is timezone-naive because [datetime.utcnow() is timezone-naive](https://docs.python.org/2/library/datetime.html#datetime.datetime.utcnow). 

Here's the stack trace:
```
Traceback (most recent call last):
<elided>
  File "/usr/lib/python2.7/site-packages/zeep/client.py", line 45, in __init__
    self.wsdl = Document(wsdl, self.transport)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 60, in __init__
    document = self._load_content(location)
  File "/usr/lib/python2.7/site-packages/zeep/wsdl/wsdl.py", line 117, in _load_content
    location, self.transport, self._parser_context, self.location)
  File "/usr/lib/python2.7/site-packages/zeep/parser.py", line 44, in load_external
    response = transport.load(url)
  File "/usr/lib/python2.7/site-packages/zeep/transports.py", line 24, in load
    response = self.cache.get(url)
  File "/usr/lib/python2.7/site-packages/zeep/cache.py", line 71, in get
    if not self._timeout or created > offset:
TypeError: can't compare offset-naive and offset-aware datetimes
```

**Comment by mvantellingen** [comment]
Fixed in #98 (thanks again!)
